### PR TITLE
Fixes #2175

### LINKED ISSUE #2175: CSW / Missing Links for Documents
The CSW XML for documents only includes links to the document detail page (`http://example.com/documents/3`) and does not include links to the actual document (`http://example.com/documents/3/download`).

For example of CSW XML:

http://geonode.state.gov/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd

For example when harvested by CKAN, see:

https://catalog.data.gov/dataset/syria-displacementrefugees-2015apr17-hiu-u1214-pdf

### PR DESCRIPTION
**Pull request by pjdufour**
Fixes #2175.  For CSW, adds link for documents to point to the download url.

Generates ISO XML like:

```
<gmd:onLine>
  <gmd:CI_OnlineResource>
    <gmd:linkage>
      <gmd:URL>http://localhost:8000/documents/1/download</gmd:URL>
    </gmd:linkage>
    <gmd:protocol>
      <gco:CharacterString>WWW:DOWNLOAD-1.0-http--download</gco:CharacterString>
    </gmd:protocol>
    <gmd:name>
      <gco:CharacterString>.jpg</gco:CharacterString>
    </gmd:name>
    <gmd:description>
      <gco:CharacterString>Test.jpg (Hosted Document Format)</gco:CharacterString>
    </gmd:description>
  </gmd:CI_OnlineResource>
</gmd:onLine>
```

### CODE REVIEW

**Comment by pjdufour** [comment]
So what would make the most sense for enabling downstream projects?

1.  DOCUMENT_TYPE_MAP and ALLOWED_DOCUMENT_TYPES in local_settings.py/settings.py completely override documents/enumerations.py

2.  DOCUMENT_TYPE_MAP and ALLOWED_DOCUMENT_TYPES in local_settings.py/settings.py are checked first and then documents/enumerations.py are checked

I can also have DOCUMENT_MIMETYPE_MAP[ext] fallback to "text/plain" too for good measure.

**Comment by garnertb** [comment]
Another option is to update enumerations.py so you don't have to include the full dicts in settings.py.

Something like:
**enumerations.py**
```
from django.conf import settings
DOCUMENT_TYPE_MAP = {...}
DOCUMENT_TYPE_MAP.update(gettattr(settings, 'DOCUMENT_TYPE_MAP', {})
```

**models.py**
```
DOCUMENT_MIMETYPE_MAP.get(ext, 'text/plain')
```

**Comment by simod** [comment]
+1 this will be good for downstream projects as well.

**Comment by pjdufour** [comment]
Incorporated above suggestions.  Added settings.py vars to update DOCUMENT_TYPE_MAP and DOCUMENT_MIMETYPE_MAP.  I've added the `update` call to the document/models.py functions rather than to enumerations.py.  Existing enumerations don't contain that type of functional/sequential logic so I thought it would make sense to keep it more straightforward.

**Pull request merged**
