### PR TITLE
[Fixes #12639] Adds all assigned group permissions to user

### LINKED ISSUE #12639: User defined permissions will break the permissions exposed by the API
## Expected Behavior

Create and add custom permissions to a user (via group) does not have any effect on handling user permissions.

## Actual Behavior

Adding new permissions to a user, which are not known by GeoNode, raises an exception [while mapping permissions](https://github.com/GeoNode/geonode/blob/33be915e234dbbf0228ebe7639f9e73b161c12a8/geonode/people/models.py#L208-L209) in `people/models.py#perms`.  As a result the API skips the `perms` attribute completely. With the API skipping that attribute, geonode-mapstore-client sees no permissions given to a user. For example a user who has actual contributor permissions, will not have the ability to (for example) add new resources.

## Steps to Reproduce the Problem

See my [discussion about custom permissions](https://github.com/GeoNode/geonode/discussions/12635) to reproduce.

  1. Add new user (id `1001`) to contributor group
  2. Check `/api/v2/users/1001` contains `perms` attribute
  3. Add a custom permission to a group a user belongs to
  4. Check `/api/v2/users/1001` is missing `perms` attribute

## Specifications

  - GeoNode version: 4.3.1 (but would affect older versions, which I did not test)
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details: https://github.com/GeoNode/geonode/discussions/12635

### PR DESCRIPTION
**Pull request by ridoo**
This is a quick proposal to ensure a user gets all permissions assigned, including custom permissions which are unknown to GeoNode but potentially created and needed by contrib apps.

See #12639 and https://github.com/GeoNode/geonode/discussions/12635 for more details

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] PR title must be in the form "[Fixes #<issue_number>] Title of the PR"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by giohappy — APPROVED** [review]

**Comment by giohappy** [comment]
@ridoo the test suite is failing but it doesn't seem related to your PR. Do you have time to check what's wrong?

**Comment by ridoo** [comment]
@giohappy thanks for your review!

AFAICS the PR is on top of 'master' which seem to fail similarly:

https://app.circleci.com/pipelines/github/GeoNode/geonode/17373/workflows/b41015bd-12e7-4918-a767-01a918c53853

I was on sick leave yesterday and, unfortunately, will not have time to dig deeper into it next week (which is a short one for me due to upcoming vacation 🥳).

**Comment by mattiagiupponi** [comment]
Hey @ridoo if you merge master in your branch, the test failing unrelated tests should pass 😄

**Comment by ridoo** [comment]
@mattiagiupponi thanks, shpuld be ready to merge now

**Comment by giohappy** [comment]
>Any chance to get it backported to v4.3.x?`:)

@ridoo technically 4.3.x is not supported anymore now that we have 4.4.x. Can't you upgrade?

**Comment by ridoo** [comment]
Will have to check. Project context, you know?! As there are some major changes I did not dig into yet, I am a bit hesitant. But could also be a chance to catch-up. You can do the merge without waiting on me.

**Pull request merged**
