### PR TITLE
[Fixes #6373] Fix Polish translation

### LINKED ISSUE #6373: Polish translation needs to be fixed
Hi! I (as a Polish native speaker) have noticed that Polish translation of GeoNode is of very poor quality - grammatical mistakes, incorrect translation of some phrases and a lot of missing translations.

### PR DESCRIPTION
**Pull request by OlgaKurek**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
Hi @OlgaKurek as a OSGEO Project we do need a signed CLA for every contribution. You can read more about it here: https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md 
If you plan further PRs I would kindly ask you to sign and drop me a line. I will then introduce your mail address to the CLA bot. If this is a one time contribution I can offer to add this improvements for you as well. Best regards, Toni

**Comment by OlgaKurek** [comment]
The issue is #6373

**Comment by t-book** [comment]
thanks @OlgaKurek should I continue with your files or do you plan further contribution. If the later please contact me if you've signed the CLA.

**Comment by OlgaKurek** [comment]
Hi @t-book I do not plan futher contributions

**Comment by t-book** [comment]
thanks @OlgaKurek I'm closing here in favour for: https://github.com/GeoNode/geonode/pull/6375

**Pull request closed without merging**
