### PR TITLE
[Fixes #6303] GeoServer fails to startup after adding multiple admin users

### LINKED ISSUE #6303: GeoServer fails to startup after adding multiple admin users
## Expected Behavior

GeoServer should start properly

## Actual Behavior
GeoServer container is in an unhealthy state

security-exception

## Steps to Reproduce the Problem

  1. Deploy spc GeoNode using docker-compose
  2. Login to the geoserver interface using the env variables.
  3. Add a couple of users who are admin to the system.
  4. Bring the services down by running docker-compose up -d
  5. Bring the services up again. The GeoServer container will rerun the entry point script and start but the container is in an unhealthy state. All the services are not up because GeoServer is in a continuous loop

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode Docker
  - Platform: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by NyakudyaA**
Fixes #6303 

* Add env variable `EXISTING_DATA_DIR` that allows skipping password reset for the already configured data directory.
* Use env variable `GEOSERVER_DATA_DIR` in entrypoint script to allow volume mount point to be controlled by env variable

### CODE REVIEW

**Comment by afabiani** [comment]
@NyakudyaA any chance to sign the CLA?

**Comment by NyakudyaA** [comment]
> CLA

I am looking at how to do it.

**Comment by NyakudyaA** [comment]
> @NyakudyaA any chance to sign the CLA?

Is there a procedure for this @afabiani

**Comment by t-book** [comment]
> > @NyakudyaA any chance to sign the CLA?
> 
> Is there a procedure for this @afabiani

Yes, please see: https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md
After you have sent your cla to osgeo feel free to ping me. I will add your email to https://github.com/GeoNode/geonode/blob/master/.clabot from then on clabot will accept your PRs

**Comment by afabiani** [comment]
@NyakudyaA did you manage to sign the CLA?

**Comment by NyakudyaA** [comment]
> @NyakudyaA did you manage to sign the CLA?

Yes, I did and sent it to osgeo yesterday

**Comment by afabiani** [comment]
@NyakudyaA ok, I'll add `admire` to the cla bot. Thank you very much.

Just a minor thing, can you please rename this PR title to 

"[Fixes #6303] GeoServer fails to startup after adding multiple admin users"

Thanks.

**Pull request merged**
