### PR TITLE
[Fixes #11335] Hookable logic for the automatic assignment of regions

### LINKED ISSUE #11335: GNIP 95 Hookable logic for the automatic assignment of regions
# GNIP 95 - Hookable logic for the automatic assignment of regions

## Overview

Regions assignment is a feature in GeoNode since the early days. However, it never received attention and, in the end, it never seemed to be working well.
Until a few weeks ago the logic was:

- If no region was assigned for a resource, try the assignment whenever the resource is updated
- Compare the intersection of the resource bbox with regions' bboxes. For any intersecting region:
  - if it's a root region assign it (regions are hierarchical) 
  - if it's a child or leaf, assign it only if the total number of assignable regions is less than 30

The latter rule was probably made to avoid assigning too many regions, In the extreme case of a resource spanning the whole globe it would mean assigning all world countries (which are the default regions preloaded in GeoNode).

Recently a change to the last rule was done to remove the limit of 30 and adopt another way of limiting the assignment:

 - only assign a region if its bbox is completely contained inside the resource bbox or if it intersects the resource bbox

This logic is subjective and it might only work for some kind of resources. In general, there's no reason to select only specific spatial relationships for the assignment. 

### Proposed By

@giohappy 

### Assigned to Release

This proposal is for GeoNode 4.2

### State

* [x] Under Discussion
* [x] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Details about the motivations. Why people should accept this proposal. What are the benefits compared to the current situation.

## Proposal

Make the assignment logic customizable through a handler that can be configured. The handler will be picked up by the [metadata_post_save](https://github.com/GeoNode/geonode/blob/master/geonode/resource/utils.py#L421) module to execute the custom logic in place of the hardcoded one. 

**By default no assignment will be done by GeoNode.**

### Backwards Compatibility

No backwards compatibility.

## Future evolution

This could be a first step toward a total customization of the post-save step.The metadata update logic could be split into multiple handlers that will be loaded and executed by the core method.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli: +1
* Giovanni Allegri: +1
* Toni Schoenbuchner: +1
* Florian Hoedt: +1

## Links

Remove unused links below.

* [Pull Request]()
* [Linked Issue]()

### PR DESCRIPTION
**Pull request by mattiagiupponi**
ref #11335 
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by giohappy — COMMENTED** [review]
@mattiagiupponi 

1. I would call the classes "*RegionAssignor" since it's a very specific handler
2. I would pass `args` and `kwargs` from the callee
3. By default we will use the "base" version, which means no assignment
4. Let's rename to SpatialPredicateRegionAssignor

**Review by afabiani — CHANGES_REQUESTED** [review]
Can you please add headers to the new files?

**Review by afabiani — DISMISSED** [review]

**Comment by giohappy** [comment]
@mattiagiupponi @afabiani I've converted this PR to Draft since I want to review it a bit more. I see overlaps [metadata_storers](https://github.com/GeoNode/geonode/blob/master/geonode/resource/manager.py#L404), and I would extend existing mechanisms rather then introducing new ones.

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi @afabiani I've converted this PR to Draft since I want to review it a bit more. I see overlaps [metadata_storers](https://github.com/GeoNode/geonode/blob/master/geonode/resource/manager.py#L404), and I would extend existing mechanisms rather then introducing new ones.

@giohappy @afabiani 
I re-arrange the code.
I kept the logic of the handler for the region but i add a function that is called by the metadata-storer to take care of assign the region. More or less it should be what u had in your mind @giohappy

**Comment by giohappy** [comment]
@mattiagiupponi let's do a test run with [geonode-rndt](https://github.com/geosolutions-it/geonode-rndt) (which is exepcted to work with the geonode master branch)

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi let's do a test run with [geonode-rndt](https://github.com/geosolutions-it/geonode-rndt) (which is exepcted to work with the geonode master branch)

@giohappy i made a local test with the RNDT app works as expected, mainly because it goes in appen on the pre-existing storer defined.

**Review by giohappy — APPROVED** [review]

**Pull request merged**
