### PR TITLE
[Fixes #4649] Internal proxy handling of relative URL segments breaks MS2 

### LINKED ISSUE #4649: Internal proxy handling of relative URL segments breaks MS2
## Expected Behavior
When the internal geonode proxy handles a URL with relative parts such as `https://path.to.static.files/folder/dist/../image.png` it should return the correct file at `https://path.to.static.files/folder/image.png`

## Actual Behavior
The geonode proxy returns HTTP 404

## Steps to Reproduce the Problem
  1. Create a geonode instance
  2. Call the proxy with a known good URL such as `geonode.local/proxy/?url=http%3A%2F%2Fgeonode.local%2Fstatic%2F<INSERT_STATIC_FILENAME>`
  3. Call the proxy with the same URL but change the static file name to `test%2F..%2F<INSERT_STATIC_FILENAME>`

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual docker
  - Platform: Ubuntu18.04
  - Additional details: We run into this when MS2 tries to fetch the locale info through XHR, resulting in MS2 layer preview and maps not showing at all.

## Cause

This is caused by `requests` itself, which is used by the geonode proxy. In particular by this issue: https://github.com/kennethreitz/requests/issues/2982

## Suggested fix

Python's `urllib` doesn't provide a way of resolving relative URL parts, but the `hyperlink` package (linked in the requests issue above) does and is quite small.

I suggest adding this to our dependencies and calling `hyperlink.URL.from_text(_url).normalize().to_text()` just after this snippet: https://github.com/GeoNode/geonode/blob/ad552fb4235ba6e42eb0be980e8f75f2a58e9089/geonode/proxy/views.py#L212-L215

Another option would be to write our own normalization logic though we'd have to maintain that?

Yet another option is to try and fix the relative URL path (`/../MapStore2/web/client/translations`) in https://github.com/geosolutions-it/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/api.js, but there's no guarantee that we never have to proxy relative URL segments again.

Happy to make a PR either way, I've only tested the hyperlink package so far.

### PR DESCRIPTION
**Pull request by GeoTob**
Adds the 'hyperlink' package to properly resolve URLs with relative
parts when using the internal proxy.

Fixes https://github.com/GeoNode/geonode/issues/4649

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@GeoTob this PR cannot be accepted like this.
Please fill the checklist otherwise we need to close this.

**Comment by GeoTob** [comment]
- Issue has no milestone attached
- Cannot find any tests for security module, existing tests running
- doc updates not applicable

@afabiani ^

**Comment by afabiani** [comment]
@GeoTob 
* you have to create an issue first and add it to the PR description
* if you can add labels to the issue, you'll need to add some related to it and assign it to a milestone, otherwise, a maintainer will do that
* The PR title must start with "[Fixes #<issue_num>] ..."
* The PR must contain at least one test-case reproducing the functionality you are willing to implement. There are several kind of test-cases in GeoNode you can add: Mocked, Integration, BDD, Selenium
* About the CLA agreement, you need to go to https://www.clahub.com/agreements/GeoNode/geonode
in case of issues, try to follow those instructions here below:

> I returned safely back and tried signing the CLA again, now with
> success. Just to let you know what was needed:
> 
> Missing was:
> * content in the signing field, I put in:
> > I AGREE TO THE CLA
> > MW (Initials)
> * then another form opens, where you have to fill:
> * the repository (Marwe/geonode)
> * Name, contact details, "I AGREE", Initials, ...
> 
> Then signing does work...

**Comment by GeoTob** [comment]
@afabiani 

Sorry it was getting a bit late yesterday..

* I thought I had updated the PR title, but must have updated the commit title instead.
* Issue had been given a label, but I can't assign to milestone.
* Was looking in `geonode/tests` not `geonode/proxy` for the tests... :/
* I still cannot sign the CLA - I get to the page where I enter email/name/corporate info, then hit by the error. Not getting an email notification or anything.

**Comment by afabiani** [comment]
@GeoTob thanks

**Pull request merged**
