### PR TITLE
Revert " Includes additional layer fields in the search index"

### PR DESCRIPTION
**Pull request by francbartoli**
Reverts GeoNode/geonode#4209

### CODE REVIEW

**Comment by afabiani** [comment]
@ahmednoureldeen we had to revert the PR due to this issue

https://github.com/GeoNode/geonode/issues/4218

Please check.

Thanks,
-A.

**Comment by giohappy** [comment]
I think some tests should be added for the haystack backend before including these fields again.

**Comment by ahmednoureldeen** [comment]
error occurred while indexing Profile model, when these fields are defined.
and defining these fields with "prepare_field_name" functions instead of model_attr fixes the issue

**Comment by francbartoli** [comment]
@ahmednoureldeen can you prepare a PR after this has been merged with those changes and some tests for the haystack backend as suggested by @giohappy?

**Comment by ahmednoureldeen** [comment]
@francbartoli ya sure.

**Pull request merged**
