### PR TITLE
[Fixes #5365] Setup code moved to geonode-selenium container

### LINKED ISSUE #5365: Unneeded build steps for SPCGeonode tests
geonode-selenium run tests inside a container, so there is no need to install any dependency on the main system.

### PR DESCRIPTION
**Pull request by frafra**
This merge request avoid running setup steps that have been included in the geonode-selenium new container.

## Checklist

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [X] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

### CODE REVIEW

**Comment by afabiani** [comment]
@frafra when this is ready, can we link the PR to an issue, with correct labels, and rename the PR title please?

**Comment by frafra** [comment]
@afabiani sure!

**Comment by afabiani** [comment]
@frafra selenium still fails on Travis

**Comment by frafra** [comment]
Sorry, I have not been on the internet recently. That error is not critical. There was an `if` clause based on wrong assumptions. Waiting for Travis now.

**Pull request merged**
