### PR TITLE
Fixes #4827 (Line layer uploaded to GeoNode is rendered as point layer)

### LINKED ISSUE #4827: Line layer uploaded to GeoNode is rendered as point layer
## Expected Behavior

A line shapefile is uploaded to GeoNode. The layer is correctly registered in GeoNode, a line style is created in GeoServer and the style is associated to the layer as the default style.

## Actual Behavior

The line layer is uploaded in GeoNode. In GeoServer two styles are created for the layer, one named "layername" (with a point symbolizer) and the other "layername_layer" (with a line symbolizer). The incorrect one is associated to the layer.

## Steps to Reproduce the Problem

I can't reproduce this on GeoNode master, but I noticed this happening randomly on two different GeoNode instances.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

### PR DESCRIPTION
**Pull request by capooti**
Fixes GeoServer being unable to get a default style problem refs #4827

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by capooti** [comment]
> There are some errors in the code:
> 
> ```
> File "/home/travis/build/GeoNode/geonode/geonode/geoserver/helpers.py", line 277, in get_sld_for
>     if name in _style_templates:
> UnboundLocalError: local variable 'name' referenced before assignment
> ```
> 
> The general idea makes sense.

thanks @afabiani. There was also another issue (and instead than or in the condition).
Do you prefer a new PR or you can squash the two commits if CI builds?

**Comment by afabiani** [comment]
@capooti I will squash the commits, no worries.

**Comment by capooti** [comment]
@afabiani test_layer_interaction fails because there are conditions when default_style is not returned. What should I do here? The idea in my commit is to raise the error, but this will make the test fail obviously, because it looks it is actually happening even in the test case (maybe for a raster?)

**Comment by afabiani** [comment]
@capooti so if the test matches a condition where the default_style shouldn't be set yet, we should check that it raises the correct error, no?

**Comment by afabiani** [comment]
@capooti tentative fix here https://github.com/GeoNode/geonode/pull/5092

**Pull request closed without merging**
