### PR TITLE
[Fixes #11703] Documents can now be uploaded without specifying title via the REST API.

### LINKED ISSUE #11703: Upload document via REST API v2 does not work
## Expected Behavior

If I follow the instruction here: https://docs.geonode.org/en/master/devel/api/usage/index.html#resource-upload

I should be able to upload a file via the REST API V2 POST endpoint

## Actual Behavior

```python
import requests
url = "https://stable.demo.geonode.org/api/v2/"

payload={
    'title': 'an example text'
}

files=[
    ('doc_file',('test.txt',open('test.txt','rb'),'text/plain'))
]

headers = {
    'Authorization': 'Basic ####' # (echo -n user:pass | base64)
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)
```

Result:
```
>>> response
<Response [405]>
>>> response.json()
{'success': False, 'errors': ['Methode "POST" nicht erlaubt.'], 'code': 'method_not_allowed'}
```

## Steps to Reproduce the Problem

  1. listed above

## Specifications

  - GeoNode version: stable.demo.geonode.org / 4.x
  - Additional details:
    tested on stable.demo and a local test instance. Both resulted in the same behaviour

### PR DESCRIPTION
**Pull request by ahmdthr**
[Fixes#11703](https://github.com/GeoNode/geonode/issues/11703) Upload document via REST API v2 does not work

The document upload does not work without specifying the title. With this PR the document will be uploaded while setting the title as the name of the uploaded file.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: black geonode && flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [x] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by giohappy — APPROVED** [review]

**Comment by giohappy** [comment]
@ahmdthr please take a look at the failing tests.

**Review by giohappy — CHANGES_REQUESTED** [review]
Apparently your test is failing

**Comment by ahmdthr** [comment]
> Apparently your test is failing

Sorry for the late response, but I was sick last week. I am going to fix the issues today. Thank you for waiting.

**Comment by giohappy** [comment]
test are failing again @ahmdthr

**Comment by ahmdthr** [comment]
The tests are fine now. The tests were failing after the introduction of "Assets". It can also be back-ported to 4.3, if needed.

**Comment by ridoo** [comment]
@ahmdthr what do you think of setting the file name instead of None in case the title is missing?

**Review by giohappy — APPROVED** [review]

**Pull request merged**
