### PR TITLE
Add QGIS Server Backend

### PR DESCRIPTION
**Pull request by lucernae**
Hey everyone, mainly for core maintainer of Geonode

I would like to propose to add qgis_server backend into core geonode repo as 
an alternative of geoserver. The reason on why we did this is, we already 
tried to make qgis_server backend a separate package in the past, but 
because many core geonode functionality has deep integration with geoserver, 
it is hard to create a separate package without changing how ogc backend 
communicate with core geonode. With this in mind we propose the following:

* Include qgis_server package into geonode, so that qgis_server backend 
developer is aware of some interesting changes in geonode. It also make it 
easy for us to maintain interoperability with geonode by making it easy to 
use via INSTALLED_APPS and inline with geonode release schedule.

* Create a parallel continuous integration test with geoserver and 
qgis_server backend to make sure that our changes didn't break current test 
for geoserver, or vice versa. It also makes it easy for us to contribute to 
geonode repo.

# Summary

We know that the first PR is quite big. We were hoping that this gets 
accepted first so we can add more incremental changes. To make it easier for 
core developer of geonode to review, I will summarize the following key 
changes:

* Using matrix testing in Travis, the test job will be divided in two 
separate parallel (running at the same time) test job, one for geoserver 
backend like the usual test, and the other for when qgis_server is being used.

* Using codecov instead of coveralls, mainly because codecov has good 
support for matrix test coverage to combine coverage from both parallel test.

* Include geonode.qgis_server python module

* Add sample docker-compose file for the QGIS Server itself to be used in CI

* Small changes in pavement to accomodate running geonode with paver when 
geoserver was not used as backend

* Helper functions to check which backend is currently being used. We will 
try to add more incremental changes to identify which part of the code is 
specific to which backend (such as some test) and refactor it.

* Modify sample django settings file for qgis_server backend

* Modify some Geonode REST API to include additional info such as Layer.
links and MapLayer.ows_url. This potentially make it easy to query 
information to Geonode from inside QGIS Desktop. We also planning to 
integrate Geonode as datasource seamlessly into QGIS Desktop.

### CODE REVIEW

**Comment by simod** [comment]
I would be +1 after the review. Thanks!

**Comment by afabiani** [comment]
+1

Thanks for your hard work. I'll try to spend some time to review the PR
also.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
github <https://github.com/afabiani?tab=overview>
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by gubuntu** [comment]
Discussion in this thread https://lists.osgeo.org/pipermail/geonode-devel/2017-August/001756.html

**Comment by lucernae** [comment]
Hi everyone I will close this PR and try to submit more atomic one.
Even though, it seems quite difficult to separate this, I will try to divide it by trying to minimize the effect on unittest for GeoServer.

**Pull request closed without merging**
