### PR TITLE
[Fixes #9210] Owner is still able to edit data and style after a resource has been approved and A/W is active

### LINKED ISSUE #9210: Owner is still able to edit data and style after a resource has been approved and A/W is active
According to the Advanced Workflow semantics, editing of a resource must be forbidden to the resource owner when a resource is approved or published.

Tests report that the user still has `change_layer_data` and `change_layer_style` after the resource is approved. This is probably happening because of the following lines: https://github.com/GeoNode/geonode/blob/b8c81edb435ec774a69c59e0c674fd9b0c336935/geonode/security/utils.py#L935-L938

@afabiani if you have any doubt just review the A/W design document.

I haven't tested master, but I suspect it will suffer the same problem.

### PR DESCRIPTION
**Pull request by mattiagiupponi**
ref #9210 
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by marthamareal — CHANGES_REQUESTED** [review]
@mattiagiupponi could we also make the permissions api consider users with only `change_resourcebase_permissions` [here](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L566)

Having both perms work enables the owner to edit permissions in A/W yet `change_resourcebase_permissions` is not assigned to them.

**Comment by afabiani** [comment]
@mattiagiupponi strangely there's a test failing, about the layer replacement apis... I don't think this is related, but it might be worth to take a look and confirm?

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi strangely there's a test failing, about the layer replacement apis... I don't think this is related, but it might be worth to take a look and confirm?

It looks like that is raising an issue with GeoServer, I'll take a look anyway. But if is related inside the docker container will be difficult to debug. I'll let u know later

```python
test_layer_replace_should_work (geonode.layers.api.tests.LayersApiTests) ... WARNING:kombu.connection:No hostname was supplied. Reverting to default 'localhost'
HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /geoserver/wms?SERVICE=WMS&&service=WMS&version=1.1.1&request=GetMap&layers=geonode:new_name&styles=point&width=240&height=200&srs=EPSG:3857&bbox=-24058759.324817516,-20048966.1040146,24058759.324817516,20048966.104014594&format=image/png&transparent=TRUE&bgcolor=0xFFFFFF&exceptions=application/vnd.ogc.se_xml&access_token=YnKu11Wjk0C9h5mfxSmqN1wlbTEOEG (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f715b665100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi could we also make the permissions api consider users with only `change_resourcebase_permissions` [here](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L566)
> 
> Having both perms work enables the owner to edit permissions in A/W yet `change_resourcebase_permissions` is not assigned to them.

Thanks for pointing it out, but this is needed on master and not on 33x. I'll do it when I'll open the PR for master

**Review by marthamareal — APPROVED** [review]

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi strangely there's a test failing, about the layer replacement apis... I don't think this is related, but it might be worth to take a look and confirm?

@afabiani on local instance works smoothly and the test pass (since is able to connect with geoserver the procedure reach the end) 
Is possible that there is some issue with the geoserver for the test build?

**Comment by afabiani** [comment]
@mattiagiupponi yeah maybe, ok, no worries, let's merge this.

**Review by afabiani — APPROVED** [review]

**Pull request merged**
