### PR TITLE
[WIP - do not merge yet] Update GeoNode to Django 1.9.13

### PR DESCRIPTION
**Pull request by afabiani**
If want to update an existing installation, please do the following

```
pip uninstall django-allauth -y
pip uninstall django-friendly-tag-loader -y
pip uninstall django-bootstrap3-datetimepicker -y
pip uninstall django-relationships -y
pip uninstall django-pagination -y

pip install Django==1.9.13
pip install pep8 --upgrade
pip install django-allauth==0.34.0
pip install django-oauth-toolkit==0.12.0
pip install django-invitations --upgrade
pip install django-model-utils --upgrade
pip install django-bootstrap3-datetimepicker-2 
pip install dj-pagination
pip install django-modeltranslation --upgrade --no-cache
pip install django-polymorphic==1.3 --no-cache
```

### CODE REVIEW

**Comment by auvipy** [comment]
just curious why not django 1.11?

**Comment by afabiani** [comment]
@auvipy there are some non-trivial incompatibilities with Django 1.11

At this time we don't have found yet suitable solutions to fix those ones.

Some experimentation ongoing on this branch

https://github.com/GeoNode/geonode/tree/DJANGO_111

Major issues currently identified are:

1. Fixtures passwords (also on tests) are no more valid on Django 1.11; users cannot login with old password hashes.

2. Templates and form widgets are come incompatibilities and details pages other than metadata editor ones, rise errors on rendering.

**Comment by auvipy** [comment]
After 1.9 support I will kick start on 1.11 branch

**Comment by afabiani** [comment]
@auvipy I'm pushing some minor changes.

With those ones basically just installing Django 1.11+ GeoNode works. The only remaining issues are:

1. Passwords stored on fixtures (even for testing) are no more recognized by Django (maybe some missing hashing algorithm or something)

2. When trying to upload a Layer or something, the SQLite DB got locked forever somehow, thus preventing any further operation on GeoNode

Just pushed a commit to align with PR #3660

**Comment by auvipy** [comment]
For the issue number 1 you are facing, what I can tell at the moment, last time I read about this backward incompatible issue in django-dev mailing list is, they suggested to just change the password as they are using new hashing algorithms. So resetting the password is the option as far I can remember right now.

**Comment by afabiani** [comment]
@auvipy yes, we can squash. Would be good to keep migrations since the previous release though.

**Pull request closed without merging**
