### PR TITLE
[Fixes #4954] only needed attributes added to cookie, when adding layer to cart

### LINKED ISSUE #4954: Adding Layers to cart leads to "Request Header Or Cookie Too Large"
## Expected Behavior
- at layer list view, I'm adding multiple layers to cart
- instead of setting permission or creating a map, I go to a layers detail view
- the detail view of the shows up
- I go back to the layers list and the items are still added to the cart

## Actual Behavior
- at layer list view, I'm adding multiple layers to cart
- instead of setting permission or creating a map, I go to a layers detail view
- nginx gives the error "Request Header Or Cookie Too Large"

## Steps to Reproduce the Problem

  1. See expected behavior

## Specifications

  - GeoNode version: 2.10.1
  - Installation method: Docker
  - Platform: debian
  - Additional details:

### PR DESCRIPTION
**Pull request by sjohn-atenekom**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@t-book @sjohn-atenekom there two ways to accept a non CLA-signed PR:

1. The author signs the CLA and sends a copy to OSGeo (as per instructions), than a committer adds the name to the .github file of GeoNode

2. A commiter that had signed the CLA opens a PR equal to the non-signed one.

**Comment by sjohn-atenekom** [comment]
@afabiani I thought this can be considered as a small change, therefore the cla is not needed (as mentioned in PR Template, next to the second checkbox)
But anyways, I can sign and send the CLA to osgeo. It just may take some days.

**Comment by afabiani** [comment]
Nope, those are strict rules from OSGeo now, since GeoNode has been officially acquired as an OSGeo project.
If you don't want to sign the CLA now, we can just copy and paste your changes and open a new PR.

**Comment by sjohn-atenekom** [comment]
Alright. No worries, i can do it... I want to contribute more in the future anyways.

**Comment by t-book** [comment]
@cla-bot check

**Comment by afabiani** [comment]
@sjohn-atenekom if you plan to contribute more in the future, please follow these simple steps

1. check if your git client is configured with an email to sign commits git config --list | grep email
2. If not, set it up using git config --global user.email email@example.com
3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

**Pull request merged**
