### PR TITLE
[Fixes #6880] Circle CI upload tests fail irregulary

### LINKED ISSUE #6880: The circle CI upload tests fail irregulary
The CircleCi tests fail irregularly. As the test machine has less power I would suggest raising the timeout limit and see if this can solve the problem until we find a better way.

### PR DESCRIPTION
**Pull request by t-book**
@afabiani this is more for testing or getting insights. If you think it's not getting us somewhere we can close

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@t-book it might be something more severe than a simple timeout. Probably the GeoServer or GeoNode being stucked.
I will need to investigate this one deeper. It will require some time!

**Comment by t-book** [comment]
@afabiani I agree. 
I will try if I can find the reason as well. As far as I remember we cannot start CircleCi locally yet (due to workflows) which could help to investigate...

**Comment by t-book** [comment]
@afabiani Good shot unfortunately it still hangs? I will see if I can find something with: https://circleci.com/docs/2.0/ssh-access-jobs/

**Comment by afabiani** [comment]
@t-book trying to merge, it should be good now. Let's see what happens with all the others PRs

**Comment by t-book** [comment]
@afabiani I'm more than curious. If it works we should lower the timeout to 10min again. Otherwise we will burn credits for a failing job.

**Pull request merged**
