### PR TITLE
[Fixes #5419] [Fixes #5446] Hierarchical keyword tree widget issues

### LINKED ISSUE #5419: Hierarchical keyword tree widget issues
## Expected Behaviour
Hierarchical keyword tree widget expands keywords successfully when any part of the folder is clicked on.

**Note:** Autocomplete light is currently being upgraded to a new version which integrates with select2 widgets on frontend https://github.com/GeoNode/geonode/pull/5410.  Hierarchical keyword tree widget will also need to be fixed to work with select2 once #5410 has landed. The autocomplete light branch currently has this widget commented out:

## Actual Behaviour
Clicking a keyword doesn't open the hierarchy as expected - it only opens when clicking the very edge of the right side of the folder.

## Steps to Reproduce the Problem

1. Sign in as an admin user
2. Navigate to the django admin panel and add some hierarchical keywords with children like the following.
image
3. Navigate to Documents (or other resource page)
4. Add a document (resource) and click into it
5. Click on "Edit Document"
6. Click the either Advanced Edit or the Wizard option
7. Find the Free-text Keywords field and expand the tree widget using the folder icon on the right of the input
8. Navigate to the parent keyword which was created earlier ie 'layer 1'
9.  Try click on the keyword such that it displays 'layer 2' - this behaviour only seems to work when clicking on the very edge of the right side of the folder. 
10. If 'layer 2' appears successfully try and click on 'layer 2' such that it displays 'layer 3' 

This should look as the following:
image

## Specifications

  - GeoNode version: 2.10 (master)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 18.04
  - Additional details:

### LINKED ISSUE #5446: Grunt production removes binary files
## Expected Behavior
Building static files should copy all needed files

## Actual Behavior
Binary files get deleted when running grunt production.

## Steps to Reproduce the Problem

  1. follow the docs for frontend develeopment setup
  2. run grunt production

## Specifications

  - GeoNode version: all

### PR DESCRIPTION
**Pull request by t-book**
This Fix will solve #5419 by changing the styling of icons. (base.less introduced a left-margin which made the icons overlap) Further, it will fix #5446 (binary files removed from lib) therefore clean:lib has been removed. the /lib directory should stay as is and only replace new build files.

After applying, Hierarchical keyword will look like shown here

## Layer list view
Bildschirmfoto 2019-12-20 um 16 08 43

## Wizard 
Bildschirmfoto 2019-12-20 um 16 09 08

## Advanced Metadata editing

Bildschirmfoto 2019-12-20 um 16 09 41

Next to less I've build the minified files and fixed a typo in docs.

## Checklist
- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

### CODE REVIEW

**Comment by afabiani** [comment]
@t-book cool thanks!

**Comment by afabiani** [comment]
@t-book any chance to restore the deleted assets? The binary files I mean.

**Comment by t-book** [comment]
> @t-book any chance to restore the deleted assets? The binary files I mean.
@afabiani 

Yeah sure no problem. This must happen on grunt production. I will check why.

**Comment by t-book** [comment]
Binaries are restored. I've opened a ticket for grunt ...

**Comment by t-book** [comment]
@afabiani I'm closing here and will restart. After rethinking it I do not like removing the clean:lib task from grunt as my last commit did. ( In my opinion, a new build should rebuild all needed files and we should not end up with a directory where it's unclear which files are needed and which are obsolete. )

**Pull request closed without merging**
