### PR TITLE
New Viewer: React Based (Boundless SDK)

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?

It adds the new React based Client to Geonode.

### How to use it
To use the new viewer/composer with your geonode instance

change the `LAYER_PREVIEW_LIBRARY` to `react`
add `geocode-client` to `INSTALLED_APPS` (already installed)

## Running Instance
Here is a running instance from master using the new viewer/composer where you can try it out.
http://geonode.terranodo.io/

## Screenshots

bildschirmfoto 2016-12-23 um 17 33 25
bildschirmfoto 2016-12-23 um 17 33 53
bildschirmfoto 2016-12-23 um 17 34 14
bildschirmfoto 2016-12-23 um 17 34 27
bildschirmfoto 2016-12-23 um 17 34 37
bildschirmfoto 2016-12-23 um 17 34 56
bildschirmfoto 2016-12-23 um 17 34 47
bildschirmfoto 2016-12-23 um 17 35 13

### CODE REVIEW

**Comment by capooti** [comment]
hi @milafrerichs, looks really a great work!

Would love to test it but after following your instructions, and having installed the client in my virtualenv with: pip install git+https://github.com/GeoNode/geonode-client.git

I am getting this error: "TemplateDoesNotExist: geonode-client/layer_map.html"

**Comment by simod** [comment]
Yahooo

**Comment by milafrerichs** [comment]
@capooti 
Thanks for the report. You can just install the latest release from pypi:
`pip install django-geonode-client`
It is included in the requirements.txt as well.

**Comment by francbartoli** [comment]
thanks @milafrerichs, can't wait to test it!

**Comment by capooti** [comment]
Oh thanks @milafrerichs I should have checked more carefully your code.
Now it is working but I am experiencing a CORS error:

Access to Image at 'http://localhost:8080/geoserver/wms?access_token=zMsFVnmX5OQOSRPZDUjpUZvTvH….342789244%2C-20037508.342789244%2C20037508.342789244%2C20037508.342789244' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

**Comment by jj0hns0n** [comment]
@capooti I also see the CORS error. I think @BerryDaniel had trouble with the django CORS module and removed it. We need to get this working in dev mode and figure out what needs to be added to the packaging to enable CORS @kalxas will help with that.

**Pull request merged**
