### PR TITLE
[Fixes #7060] Refactoring of thumbnail creation

### LINKED ISSUE #7060: Refactor thumbnail creation service
The current creation of thumbnails for layers and maps is quite a mess, and the following points are especially problematic:

- there are multiple implementations of thumbnail rendering of layers. At least the following two are implemented:
   - [create_gs_thumbnail_geonode](https://github.com/GeoNode/geonode/blob/d712fe93bc1bacda3cb22e521f531bb5d0bbabec/geonode/layers/utils.py#L1094) which apparently is only used by geoserver async signals signals 
   - [layer_thumbnail](https://github.com/GeoNode/geonode/blob/1a94bbe43e553a4b3155260c925a1f4f9919731c/geonode/layers/views.py#L1472)
- both [layer_thumbnail](https://github.com/GeoNode/geonode/blob/1a94bbe43e553a4b3155260c925a1f4f9919731c/geonode/layers/views.py#L1472) and [map_thumbnail](https://github.com/GeoNode/geonode/blob/8448190b6a105f4b9fe94276e442f8a877606de3/geonode/maps/views.py#L1310) [use the pritng Geoserver module](https://github.com/GeoNode/geonode/blob/d909a1d1e50a765f1b849b9657377e07db83cf1d/geonode/geoserver/helpers.py#L2068) for the actaul rendering. This module is stale and quite a black box. Probably [this code](https://github.com/planetfederal/geoserver-exts/tree/master/printng) reflects the module that we're [bundling inside the Geoserver build](https://github.com/GeoNode/geoserver-geonode-ext/blob/2.17.x/geoserver/pom.xml#L427) for GeoNode
- the creation of the thumbnail for a map apparently takes different paths in case the thumbnail is generated from the Django template pages or from the "Save" action inside the GeoNode MapStore client. Different thumbnails (different zoom level and positioning) are generated for the two cases

This module will be in charge of:

- provide a unified interface for the GeoNode components that trigger the creation of a thumbnail:   
   - post layer creation tasks
   - map saving
   - metadata wizard thumbnail widget
   - set thumbnail action from layer and map detail page
- receiving a configuration for the map to be rendered (bbox, dimensions, etc.)
- delegating to specialized classes the retrieval of the layers images (WMS, XYZ, etc.)
- composing the final rendered image

### PR DESCRIPTION
**Pull request by giohappy**
Refactoring of thumbnail creation

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [x] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by gannebamm** [comment]
@afabiani These are many commits for the PR. Most not related to the issue? This should be cleaned?

**Comment by afabiani** [comment]
@bieganowski can you fix also this new LGTM alert?

1 for Result of integer division may be truncated

**Comment by afabiani** [comment]
@gannebamm there are many commits because the fork is against the geosolutions repo, but the context is ok. I will review carefully anyway.

However, if the PR is OK, all the commits will be squashed on merge.

**Comment by bieganowski** [comment]
@afabiani I think the LGTM alert is python 2 exclusive, and python 3 does not truncate the divided integers:
image

P.S. Of course, if that's something that cannot be changed easily in LGTM, or we don't want to mess with it, I can cast one of these values to float, just to remove this alert.

**Review by afabiani — APPROVED** [review]

**Pull request merged**
