### PR TITLE
Improve geonode performances

### PR DESCRIPTION
**Pull request by simod**
This PR solves the major issues described in #2130 and #2122.
The guardian permissions are checked faster avoiding complex joins
The categories, regions and keyword counts are done in the post-process in bulk and not per object anymore
The layer_upload uses gsconfig so to not query geoserver for all the layers available
The layer_acls check is improved by ~75%

A proper test to load lot of data has to be done in a realistic way. Loading many times the same layer will hit the db to find an available name so there is still a slight slow down in layer upload like it becomes 1s slower every 300 layer loaded.

### CODE REVIEW

**Comment by ingenieroariel** [comment]
:+1:

**Comment by capooti** [comment]
it looks perfect to me, great work! ;)

**Comment by ischneider** [comment]
Nice work, @simod.

As per my line comment, it looks like there are several other places where the use of `values_list` can be replaced.

**Comment by simod** [comment]
thanks! fixing them

**Pull request merged**
