### PR TITLE
[DRAFT][Closes #4389] New rebuilt Leaflet hookset/template

### LINKED ISSUE #4389: New rebuilt Leaflet hookset/template
Quoting @dejansamardzic

> Dear community,
> 
> We have rebuilt Leaflet hookset/template, so now Leaflet client is fully functional and prepared for adding new plugins. We have inclueded plugins for: Full screen, measurement tool, printing tools, layer contoler with multiple base layers, transparency slider, scale bar, drawing tools - useful for pointing some objects or areas before printing, locate me option, leaflet hash...
> 
> Known limitations:
> 
> Bounding box for map thumbnail creation doesn't focus as it should be
> 
> Problem with GeoWeb Cache: Uploading new layers results with wrong bounding boxes in Geoserver. In order to make GeoWeb Cache to work, layer needs to be removed from Cache and added again. This clears problem with wrong bounding box defined during upload and turn it into "dynamic".
> 
> Embeded maps are focused on Montenegro.
> 
> To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container
> 
> Plugin "Locate me" works only through https.
> 
> Best regards,
> Dejan Samardzic

Refers #4130
Refers #4131

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by t-book** [comment]
@afabiani what is the state of this PR? Do you need my testing review here?

**Comment by t-book** [comment]
@afabiani Issues:

- **Pan-Tool outputted twice.**
Bildschirmfoto 2019-06-12 um 16 37 10

- **Map creation, no layers populated in drop down**
Bildschirmfoto 2019-06-12 um 16 37 24

- **Creation of thumbnails not working**
````
geonode:tiger_roads:379 Uncaught TypeError: map.getBounds is not a function
    at createMapThumbnail (geonode:tiger_roads:379)
    at HTMLAnchorElement.<anonymous> (geonode:tiger_roads:2107)
    at HTMLAnchorElement.dispatch (assets.min.js?v=2.10rc5:4)
    at HTMLAnchorElement.q.handle (assets.min.js?v=2.10rc5:4)
````


- **Tests?**

**Comment by gannebamm** [comment]
maybe we should close this one?

**Comment by t-book** [comment]
> maybe we should close this one?

+1 I would even say maybe we should kick out leaflet completely. Unfortunately, it's not easy as the qgis stack is using it ...

**Pull request closed without merging**
