### PR TITLE
Fixes #4949 UnicodeEncodeError in upload.models.update_from_session

### LINKED ISSUE #4949: UnicodeEncodeError in upload.models.update_from_session method when using Importer
## Expected Behavior

A layer can be correctly uploaded by a user with a profile first_name and last_name not containing ascii characters.

## Actual Behavior

For a user in profile has no ascii characters in first_name, last_name the upload using the GS Importer fails with the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 675, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 234, in save_step_view
    Upload.objects.update_from_session(upload_session)
  File "/home/ubuntu/geonode/geonode/upload/models.py", line 42, in update_from_session
    upload_session)
  File "/home/ubuntu/geonode/geonode/upload/models.py", line 100, in update_from_session
    upload_session.user.first_name = u'{}'.format(upload_session.user.first_name).decode("utf-8", "replace")
  File "/home/ubuntu/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-11: ordinal not in range(128)
```

REST uploaded works as expected.

## Steps to Reproduce the Problem

  1. Login with a user having not-ascii characters in first_name/last_name (profile)
  2. upload a layer using GS importer

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by capooti**
Fixes #4949

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by capooti** [comment]
@afabiani the error is caused by the check being done. Removing that two lines won't remove the information from the upload_session and Python handles it without problems even with not ascii characters in my test.
I agree to have a test for this: it would be enough to have a profile fixture having not ascii characters in first_name/last_name for this purpose

**Comment by t-book** [comment]
... or in case it is good for a thing we currently do not see how about keep it but fail silently?

```
try:
    upload_session.user.first_name = u'{}'.format(upload_session.user.first_name).decode("utf-8", "replace")
    upload_session.user.last_name = u'{}'.format(upload_session.user.last_name).decode("utf-8", "replace")
except UnicodeEncodeError:
    pass
```

**Comment by afabiani** [comment]
Well, interpreting the code it seems that the original intention was to pickle the user info into the database. The existing check, tries to remove "unpickable" utf-8 characters. Removing them or doing a silent check, means avoid saving completely that info into the DB.

Now, it is possible that it is not used anywhere else later on, but it is worth to double check IMHO.

**Comment by afabiani** [comment]
@capooti --> https://github.com/GeoNode/geonode/pull/4958

**Comment by capooti** [comment]
thanks @afabiani I just merged it
In my case there wasn't the need to sanitize the strings as you did, that is way I was considering just to remove those two lines.
If you have time, could you run CI after removing the two lines as a test?

**Comment by t-book** [comment]
Ref: https://github.com/GeoNode/geonode/issues/4935
(Test if this can help here as well)

**Pull request closed without merging**
