### PR TITLE
[Fixes #5893] delete_resources management command

### LINKED ISSUE #5893: delete_resources management command
**Is your feature request related to a problem? Please describe.**
I'd like to have a management command removing certain resources (layers, maps, documents), based on django's Q() expressions.

**Describe the solution you'd like**
The command will have to implement the following features:

1. delete resources from GeoNode (and Geoserver in case of layers) and all related data
2. provide a CLI interface for simple usage or a config file for more aritculated options 

Filtering
The filtering should accept Q object expressions, to express any lookup combination with ANDs and ORs. Ideally the filter should be deserielized to be employed inside a Queryset.get() or Queryset.filter() expression.

A dumb example is the following:

```
"filters": {
	"layer": 'Q(pk__in: [PK1, PK2, PK3]) | Q(title__icontains:"italy"), Q(owner__name=admin)',
	"map": '*',
	"documents": '*'
}
```

CLI
The CLI should provide 3 params for each kind of resource. For each param a filter expression can be defined or a param to pass a json file like in the example aboive.

`python manage.py delete_resources -l 'Q("pk__in": [PK1, PK2, PK3]) | Q("title__icontains":"italy"), Q(owner__name=admin)' - m '\*' -d '\*'`

`python manage.py delete_resources -f ./filters.json`

### PR DESCRIPTION
**Pull request by bieganowski**
Management command removing certain resources (layers, maps, documents), based on django's Q() expressions.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by bieganowski** [comment]
documentation PR: https://github.com/GeoNode/documentation/pull/14

**Comment by t-book** [comment]
@bieganowski can you please have a look at this https://lgtm.com/projects/g/GeoNode/geonode/rev/pr-c5727557a354c61e0127b773803c9806b820f29f thanks!

**Comment by bieganowski** [comment]
@t-book that import statement needs to be there, even though it is wasn't directly used in this module - this management command evaluates serialized django `Q()` lookups, so without that import, it will surely fail on the first run :)
image

**Comment by t-book** [comment]
@bieganowski thanks for having a look!

**Pull request merged**
