### PR TITLE
port existing MapStory Favorites feature to GeoNode as optional module.

### PR DESCRIPTION
**Pull request by jwood106**
Uncomment 'geonode.contrib.favorite' entry in settings.py to enable.
Once enabled, UI allows authenticated user to favorite Document, Layer and Map.

### CODE REVIEW

**Comment by garnertb** [comment]
Please squash this into a single commit so that we can review it.

**Comment by simod** [comment]
What is the Favorite functionality?
I know that we have some if statements spread around like the one of NOTIFICATION, but we are trying to get rid of them (and we will in the near future). It would be preferable to have non invasive contrib apps so that they can be plugged in without the need add code in core. On the long (and even short) term it will become very difficult to maintain that code.

**Comment by jwood106** [comment]
Per garnertb's request, squashed into single commit.
Per simod's question, while squashing, added better favorite functionality description in the commit description.
Re: simod's comment about minimizing changes necessary in core for an optional contrib app, I agree.  Definitely valuable to make the minimum changes to the core, keep as much isolated in the contrib module for clarity and maintainability.  I made the minimum 'hook' changes to core that I know to do.  You mentioned you are looking at how to get rid of existing hooks, makes sense to apply the same here, if applicable.

**Comment by ingenieroariel** [comment]
I understand @simod's suggestion and also believe the notification one is a particularly intrusive third party app and requires conditionals all over the place.

That said, I see why favorites is someting that should be added to document detail, layer detail and map detail pages. In that case, I believe it is better to instruct the user to add the relevant HTML snippet manually instead of writing the conditional code. This is more in line to how Django apps work (they ask you to add things to templates, settings.py and urls.py) and end up in more flexibility for the end user.

@simod, what do you think about the compromise of having code that is commented out and can be uncommented to enable the functionality instead of the context variables that were introduced?

**Comment by simod** [comment]
I think is better, especially if the template is just a snippet that lives in the contrib app, with the instructions, that can be {% included %} in the desired pages.

**Comment by jwood106** [comment]
Per GeoNode developer feedback above (btw, thank you for the feedback), I removed all previously submitted changes to GeoNode core, now this pull request contains only code in the new contrib module.
I added a readme.txt with instructions for changes developer will need to make to GeoNode core if want to enable the Favorite module in the app.
Squashed the changes into a single commit.
Thank you to Tyler Garner for superior Git support.  He helped me overcome several issues I had and improve my workflow for this pull request.  Much appreciated!

**Comment by ingenieroariel** [comment]
I am :+1: on merging

**Comment by simod** [comment]
+1 too

**Pull request merged**
