### PR TITLE
[Fixes #12170] unable to set advanced contact roles in metadata editor

### LINKED ISSUE #12170: unable to set advanced contact roles in metadata editor
## Expected Behavior

When setting an advanced (related to this PR (https://github.com/GeoNode/geonode/pull/10367)) contact role through the metadata editor it is not stored in the database.

I guess this is related to changes to django framework.

## Specifications

  - GeoNode version: 4.2
  - Installation type (vanilla, geonode-project): all
  - Installation method (manual, docker): all
  - Platform: all
  - Additional details:

### PR DESCRIPTION
**Pull request by mwallschlaeger**
<Include a few sentences describing the overall goals for this Pull Request>

ref #12170 ,  #10367 ,  #10290

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by giohappy** [comment]
@mwallschlaeger there's an error reported by tests

**Review by giohappy — CHANGES_REQUESTED** [review]
tests are failing do to this error @mwallschlaeger:

```
ERROR: test_resource_form_is_valid_extra_metadata (geonode.geoapps.tests.GeoAppTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/base/widgets.py", line 36, in value_from_datadict
    ret_list = data.getlist(name)
AttributeError: 'dict' object has no attribute 'getlist'

During handling of the above exception, another exception occurred:
```

**Comment by mwallschlaeger** [comment]
@giohappy I will check this and fix the issue

**Comment by mwallschlaeger** [comment]
@giohappy its ready review now

**Comment by giohappy** [comment]
@mwallschlaeger any chance to get the editor fixed for documents?

**Comment by mwallschlaeger** [comment]
@giohappy i will take care of this tomorrow

**Review by giohappy — APPROVED** [review]

**Comment by giohappy** [comment]
@mwallschlaeger this fix should be backported to 4.2.x too. Can you please take care of this?

**Comment by mwallschlaeger** [comment]
@giohappy yes i can cherry-pick the commits to 4.2.x beginning of next week

**Comment by giohappy** [comment]
@mwallschlaeger if it's a matter of cherry-picking I can do it, but I suspect it's more then that, since 4.2.x uses Django 3

**Comment by mwallschlaeger** [comment]
@giohappy i will take a look at it. no worries

**Pull request merged**
