### PR TITLE
Adding a geogig_link URL to /api/layers

### PR DESCRIPTION
**Pull request by theduckylittle**
This adds a geogig_link URL to the search results and avoids using the full TastyPie hydration cycle that https://github.com/GeoNode/geonode/pull/2789 caused.

The following changes were made:

1. The model for `Layer` now has `geogig_enabled` and `geogig_link` properties. 
2. Object formatting was moved out of `create_response` and into a new class method, `format_objects`.
3. The `VALUES` object was moved out of `create_response` and is now a class member.
4. The `LayerResource` class has a new `format_objects` method which converts the models to dictionaries, then adds in the `geogig_link` property to the dictionary.

These changes work with https://github.com/boundlessgeo/MapLoom/pull/45

Thanks again.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@theduckylittle can you take a look at the test failure? It may just need to have the build bumped?

**Comment by theduckylittle** [comment]
I just did a fetch/merge/push cycle and the checks are restarting now.  I didn't see any test failures before but will check back in when this completes.

**Comment by jj0hns0n** [comment]
It may be flake8 complaining, its running again now ... slowly.

**Comment by theduckylittle** [comment]
Found the flake8 error, line 513 was over length by 4 characters.

**Comment by jj0hns0n** [comment]
Glad you caught that, flake8 errors not so easy to see in travis, would be
nice to know something other than that it complained. Ill merge when the
tests run.

**Comment by theduckylittle** [comment]
Woohoo! Passing tests!

**Pull request merged**
