### PR TITLE
[3.3.x][Fixes #8362] Permissions to brand new group managers 

### LINKED ISSUE #8362: Permissions to brand new group managers
## Expected Behavior

While in *advanced workflow* mode, when creating a brand new group manager, all default manager permissions should be granted to existing resources.

## Actual Behavior

No permissions are granted to the new manager.

~~Only a couple of basic permissions are granted.~~ (see first comment below)

## Steps to Reproduce the Problem

  1. Setup: enable advanced workflow
  2. Create a resource and assign a group
  3. Create a new manager for the group
  4. Check the permissions for the new manager 

## Specifications

  - GeoNode version: 
    - 3.3.x, 
    - master

## Additional details:

Promoting and demoting users in a group do not assign all the needed permissions handled in the advanced workflow  https://github.com/GeoNode/geonode/blob/5b4edf0f35dc5441f45ff2087756fdae7492af4e/geonode/groups/models.py#L266-L286

### PR DESCRIPTION
**Pull request by mattiagiupponi**
References: #8362

Centralize permissions assign when user is promoted to manager or demoted to user

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — CHANGES_REQUESTED** [review]
The code does something different from the previews one and doesn't look matching the issue requirements.

As an instance when promoting a user to manager, there's no logic to assign `write` permissions to it anymore.

**Comment by mattiagiupponi** [comment]
> The code does something different from the previews one and doesn't look matching the issue requirements.
> 
> As an instance when promoting a user to manager, there's no logic to assign `write` permissions to it anymore.

@afabiani you are right. I was focusing on advanced workflow behaviour. I'm gonna fix this asap

**Comment by mattiagiupponi** [comment]
> The code does something different from the previews one and doesn't look matching the issue requirements.
> 
> As an instance when promoting a user to manager, there's no logic to assign `write` permissions to it anymore.

@afabiani The write permissions are handled internally by the `set_permissions` function. The main development has been done here: https://github.com/GeoNode/geonode/pull/8145.
I add also a little doc inside the code to explicit this thing:
```
Internally the set_permissions function will automatically handle the permissions
that needs to be assigned to re resource.
Background at: https://github.com/GeoNode/geonode/pull/8145
If the user is demoted, we assign by default at least the view and the download permission
to the resource
```

**Comment by afabiani** [comment]
@mattiagiupponi I've been refactoring the `permissions` methods on the `security` module by trying to centralize more the `workflow` ones. @etj @mattiagiupponi would you be able to give it a try?

**Comment by mattiagiupponi** [comment]
@afabiani I checked it, it looks like that the behaviour is modified (as an instance the `SetPermissionsTestCase` are failing).

There are also a few things that are a bit confusing to me:
- `set_workflow_perms` I would change the name, technically isn't set any kind of permission. Is just a function that returns the permissions dict for the resource. Maye `get_workflow_perms`?
- The `set_permissions` now assume that the permission dict is a param. I would evaluate to change how the `demote/promote` works and `set/remove` only the permission to the user instead of recalculating every time the dictionary for all the users with perms on that resource. 

@etj any thoughts?

**Comment by afabiani** [comment]
@mattiagiupponi the previous behavior wasn't fully correct, I'm currently reviewing the tests too. It was not coherent with the advanced workflow logic. As an instance the queryset to filter the affected resources was wrong. Other than this, it was invoking the `set_permissions` wrongly. You need to always pass the whole `perm_spec` to that method, otherwise you will remove other permissions.

This lead to the second point, the `set_permissions` purges the GeoFence rules, that's why currently there's no suitable way to selectively remove some rules, unless we do additional work in order to improve such behavior.

I agree about point 1.

**Pull request merged**
