### PR TITLE
[Fixes #5437] API endpoints reveal too much information

### LINKED ISSUE #5437: API endpoints reveal too much information
## Expected Behavior
- API-Endoinsts do not reveal user or group information on unauthenticated requests

## Actual Behavior
- Endpoints /api/profiles, /api/owners /api/groups reveal information, which should be accessible for unauthenticated requests
Following information can be accessed: complete Userdetails, Email-Addresses, Name of groups

## Steps to Reproduce the Problem

  1. https://master.demo.geonode.org/api/profiles
  2. https://master.demo.geonode.org/api/owners
  3. https://master.demo.geonode.org/api/groups

## Specifications

  - GeoNode version: 2.6 / 2.10.0 / 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Debian
  - Additional details:

### PR DESCRIPTION
**Pull request by sjohn-atenekom**
This PR fixes ISSUE-5437. Open API endpoints have been protected and closed for anonymous users. Therefore a new settings has been introduced, to deactivate the lockdown, since the lockdown affects the filtering of search results, when a user is not authenticated.

Documentation and tests have been added.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@sjohn-atenekom thanks. The patch is very good.

Can you please fix the code formatting issues to make the tests pass?

```
flake8 geonode
geonode/api/tests.py:516:72: W292 no newline at end of file
geonode/api/authorization.py:169:1: W391 blank line at end of file
geonode/api/api.py:303:5: E303 too many blank lines (2)
geonode/api/api.py:344:5: E303 too many blank lines (2)

```

**Comment by sjohn-atenekom** [comment]
Hi @afabiani,
i just fixed the formatting issues.

**Comment by sjohn-atenekom** [comment]
@afabiani I fixed the formatting issues again. There still some unittests failing, but i'm not sure if these are related to this fix. What do you think?

**Comment by afabiani** [comment]
@sjohn-atenekom as far as I can see there are still several errors on tests

```
======================================================================
ERROR: test_group_logo_is_not_present_on_list_view (geonode.groups.tests.GroupProfileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/groups/tests.py", line 792, in test_group_logo_is_not_present_on_list_view
    ][0]
IndexError: list index out of range
======================================================================
ERROR: test_group_logo_is_present_on_list_view (geonode.groups.tests.GroupProfileTest)
Verify that a group's logo is rendered on list view.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/django/test/utils.py", line 384, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/GeoNode/geonode/geonode/groups/tests.py", line 766, in test_group_logo_is_present_on_list_view
    ][0]
IndexError: list index out of range
======================================================================
FAIL: test_api (geonode.groups.tests.GroupCategoriesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/groups/tests.py", line 699, in test_api
    GroupCategory.objects.all().count())
AssertionError: 0 != 1
----------------------------------------------------------------------
Ran 105 tests in 1290.076s
FAILED (failures=1, errors=2)
```

**Comment by afabiani** [comment]
@sjohn-atenekom I guess now it is better for you to redo this PR against 2.10.x branch.

We will forward it to the master branch later on.

Still, there are tests failures (see my previous comments)

**Comment by sjohn-atenekom** [comment]
@afabiani sorry for delay. I'm already working on it and I will try to open a new PR in the beginning of next week.

**Comment by sjohn-atenekom** [comment]
I opened PR #5598 and will close this PR instead as discussed in comments.

**Pull request closed without merging**
