### PR TITLE
[Fixes #8300] Hide "download" permissions for maps and apps

### LINKED ISSUE #8300: Hide "download" permissions for maps and apps
**Is your feature request related to a problem? Please describe.**
Currently GeoNode has no features to "download" something different from a `dataset` or `document`, therefore this should be also reflected on permissions.

`download_resourcebase` permission does not make any sense to `ResourceBase` which are not `dataset` or `document`.

**Additional context**
#### Backend

1. Improve the `ResourceManager set_permissions` [method](https://github.com/GeoNode/geonode/blob/master/geonode/resource/manager.py#L557) in order to perform sanity checks on the provided `perm_specs` and remove the permissions accordingly to the `resource_type`
2. Improve the `permissions` compact/expand [methods](https://github.com/GeoNode/geonode/blob/master/geonode/security/permissions.py#L93) in order to both prevent sending `Download` permissions for resources that do not support them (we might envisage to extend the `Meta` to be able to keep track of this) and remove the latter too accordingly, when converting from `compact` to `extended` and vice versa

#### Frontend
Avoid shown "Download" permissions on resources different from `dataset` and `document`.

The goal would be allow the frontend to dynamically set the list of available permissions for a certain resource type
image

We would like to avoid putting a lot of static conditions on the frontend side in order to render the list above.

The proposal is to:

1. Add a new node to the resource API v2 `json` output named `allowed_perms` providing the list of the available `perm_spec` and `compact` permissions on a resource
    e.g. for a `dataset` resource type

    ```json
    {
      "name": "dataset",
      "count": 1,
      "allowed_perms": {
        "perms": {
          "anonymous": [
            "view_resourcebase"
          ],
          "default": [
            "change_resourcebase_metadata",
            "delete_resourcebase",
            "change_resourcebase_permissions",
            "publish_resourcebase",
            "change_resourcebase",
            "view_resourcebase",
            "download_resourcebase",
            "change_dataset_data",
            "change_dataset_style"
          ],
          "registered-members": [
            "change_resourcebase_metadata",
            "delete_resourcebase",
            "change_resourcebase_permissions",
            "publish_resourcebase",
            "change_resourcebase",
            "view_resourcebase",
            "download_resourcebase",
            "change_dataset_data",
            "change_dataset_style"
          ]
        },
        "compact": {
          "anonymous": [
            "none",
            "view"
          ],
          "default": [
            "view",
            "download",
            "edit",
            "manage",
            "owner"
          ],
          "registered-members": [
            "none",
            "view",
            "download",
            "edit",
            "manage"
          ]
        }
      }
    }
    ```
2. Allow the frontend to be able to filter the perms `dropdowns` accordingly to the previous list

### PR DESCRIPTION
**Pull request by afabiani**
References: #8300

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@giohappy @allyoucanmap this PR allows the backend behave accordingly to #8300
however the frontend should also be improved in order to avoid showing "download" permissions on `maps` and `apps`.

Do we envisage improving the `api` somehow? Or we can adapt the `SPA` sections directly? Thoughts?

**Comment by giohappy** [comment]
>however the frontend should also be improved in order to avoid showing "download" permissions on maps and apps.

@afabiani @allyoucanmap isn't the client only showing the compact permissions received from the backend? In theory it shouldn't be adapted, it should happen automatically...

**Comment by allyoucanmap** [comment]
> @afabiani @allyoucanmap isn't the client only showing the compact permissions received from the backend? In theory it shouldn't be adapted, it should happen automatically...

@giohappy @afabiani 
Yes, it's showing the compact permission of the resource but the list of the available permissions types is provided by the client as configurable properties https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/plugins/Share.jsx#L149-L200 .

I don't think there is and endpoint that list all the available permissions based on resource_type right now.

**Comment by afabiani** [comment]
What about a property "downloadable" or something attached to the resource itslef?

**Comment by giohappy** [comment]
>What about a property "downloadable" or something attached to the resource itslef?

If we want the backend to provide the information I would make it generic, and not specific for the "download" permission. An API with the available permissions by resource type, as suggested by @allyoucanmap, would be fine. How long would it take @afabiani?

**Comment by afabiani** [comment]
@giohappy yes, I also meant something more generic. We already have something on the backend which is able to discriminate between resources that are downloadable, editable and so on...

I don't think it will be a big deal from the backend exposing an API endpoint with the available permissions by resource type. 0.5 days probably

**Comment by giohappy** [comment]
>I don't think it will be a big deal from the backend exposing an API endpoint with the available permissions by resource type. 0.5 days probably

In that case I would implement this and adapt the client accordingly, rather then changing the client static list of permissions. @afabiani can you please open an epic with which both the client and backend issues will be created?

**Pull request merged**
