### PR TITLE
[Fixes #6332] In home page show only ISO categories currently assigned to some dataset

### LINKED ISSUE #6332: In home page show only ISO categories currently assigned to some dataset
In home page shows only ISO categories currently assigned to some dataset

## Overview

In the GeoNode home page, ISO Categories displayed for quick filtering of datasets are shown irrespective of if they are being used or not by any dataset. This at times leads to an empty search of click. This can be changed to only show ISO categories currently assigned to a dataset together with a count of the number of datasets (only those a user has access to view) using the ISO format.
iso

### Proposed By

[abulo john joshua](https://github.com/abulojoshua1)

### Assigned to Release

This proposal is for GeoNode 3.1.0.dev1596544521.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Displaying ISO formats that are not being used by any dataset will only lead to the filtering of empty datasets in the search when the quick ISo format link is clicked. In addition, it would also be good if the ISO formats contain a stats badge showing the number of datasets using the ISO format

## Proposal

To filter for all ResourceBase model objects with a category that a user has permissions to view, then get a count and other category data needed to display stats (number of datasets using the ISO format) and other data about the category (ISO format)

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

### PR DESCRIPTION
**Pull request by abulojoshua1**
In home page show only ISO categories currently assigned to some dataset

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@abulojoshua1 

# . There are some conflicts with the previous PR base.less and base.css
#. flake8 complains about some syntax issues

```
flake8 geonode
geonode/base/tests.py:59:20: E222 multiple spaces after operator
geonode/base/templatetags/base_tags.py:357:68: E231 missing whitespace after ','
```

**Comment by afabiani** [comment]
@abulojoshua1 some tests are also failing

```
======================================================================
ERROR: test_add_missing_metadata_author_or_poc (geonode.base.tests.TestCreationOfMissingMetadataAuthorsOrPOC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 124, in test_add_missing_metadata_author_or_poc
    self.rb.owner = user
AttributeError: 'TestCreationOfMissingMetadataAuthorsOrPOC' object has no attribute 'rb'
======================================================================
ERROR: test_initial_behavior (geonode.base.tests.TestCreationOfMissingMetadataAuthorsOrPOC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 87, in test_initial_behavior
    self.assertFalse(self.rb.has_thumbnail())
AttributeError: 'TestCreationOfMissingMetadataAuthorsOrPOC' object has no attribute 'rb'
======================================================================
ERROR: test_initial_behavior (geonode.base.tests.ThumbnailTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 87, in test_initial_behavior
    self.assertFalse(self.rb.has_thumbnail())
AttributeError: 'ThumbnailTests' object has no attribute 'rb'
----------------------------------------------------------------------
Ran 187 tests in 475.577s
```

**Comment by abulojoshua1** [comment]
> @abulojoshua1 some tests are also failing
> 
> ```
> ======================================================================
> ERROR: test_add_missing_metadata_author_or_poc (geonode.base.tests.TestCreationOfMissingMetadataAuthorsOrPOC)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 124, in test_add_missing_metadata_author_or_poc
>     self.rb.owner = user
> AttributeError: 'TestCreationOfMissingMetadataAuthorsOrPOC' object has no attribute 'rb'
> ======================================================================
> ERROR: test_initial_behavior (geonode.base.tests.TestCreationOfMissingMetadataAuthorsOrPOC)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 87, in test_initial_behavior
>     self.assertFalse(self.rb.has_thumbnail())
> AttributeError: 'TestCreationOfMissingMetadataAuthorsOrPOC' object has no attribute 'rb'
> ======================================================================
> ERROR: test_initial_behavior (geonode.base.tests.ThumbnailTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 87, in test_initial_behavior
>     self.assertFalse(self.rb.has_thumbnail())
> AttributeError: 'ThumbnailTests' object has no attribute 'rb'
> ----------------------------------------------------------------------
> Ran 187 tests in 475.577s
> ```



> @abulojoshua1 some tests are also failing
> 
> ```
> ======================================================================
> ERROR: test_add_missing_metadata_author_or_poc (geonode.base.tests.TestCreationOfMissingMetadataAuthorsOrPOC)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 124, in test_add_missing_metadata_author_or_poc
>     self.rb.owner = user
> AttributeError: 'TestCreationOfMissingMetadataAuthorsOrPOC' object has no attribute 'rb'
> ======================================================================
> ERROR: test_initial_behavior (geonode.base.tests.TestCreationOfMissingMetadataAuthorsOrPOC)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 87, in test_initial_behavior
>     self.assertFalse(self.rb.has_thumbnail())
> AttributeError: 'TestCreationOfMissingMetadataAuthorsOrPOC' object has no attribute 'rb'
> ======================================================================
> ERROR: test_initial_behavior (geonode.base.tests.ThumbnailTests)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/GeoNode/geonode/geonode/base/tests.py", line 87, in test_initial_behavior
>     self.assertFalse(self.rb.has_thumbnail())
> AttributeError: 'ThumbnailTests' object has no attribute 'rb'
> ----------------------------------------------------------------------
> Ran 187 tests in 475.577s
> ```
:) 
Checking...

**Comment by t-book** [comment]
@abulojoshua1 On a migrated instance the fa-class is fa-times for every cat. 

Bildschirmfoto 2020-09-09 um 11 32 25

Making all Categories look like:

Bildschirmfoto 2020-09-09 um 11 32 36


Can you kindly say if this is intended behaviour, or if I did miss some fixture?

**Comment by abulojoshua1** [comment]
> @abulojoshua1 On a migrated instance the fa-class is fa-times for every cat.
> 
> Bildschirmfoto 2020-09-09 um 11 32 25
> 
> Making all Categories look like:
> 
> Bildschirmfoto 2020-09-09 um 11 32 36
> 
> Can you kindly say if this is intended behaviour, or if I did miss some fixture?

@t-book, I'll look into this issue but, in my humble opinion, it is unlikely that it was caused by changes in this PR because no migration files were changed, no fixture files were changed and this PR does not include changes to the ResourceBase model class.

**Comment by t-book** [comment]
nice thanks a lot @abulojoshua1 I think in case this is a general behavior and not only at my migrated instance a notice at the docs or a small fixture will do it.

**Pull request merged**
