### PR TITLE
[Fixes: #10841] Serializing and deserializing ResourceBase and Dataset objects breaks validation check

### PR DESCRIPTION
**Pull request by mwallschlaeger**
<Include a few sentences describing the overall goals for this Pull Request>

This PR fixes an issue regarding the serialization of dynamic rest framework object serialization in base.api.serializers. Current implementation misses the conversion from DynamicModelSerializer Objects into django internal data structures. This issue is described in #10841 

This PR further fixes makes patch actions of the following resource fields work: 
- "keywords",
- "tkeywords"
- "restriction_code_type"
- "license"
- "spatial_representation_type"
- "category"

like e.g. using `geonodectl` like:
```
geonodectl ds patch 1  --set 'category={"identifier": "structure"}'
```

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@mwallschlaeger thanks for the contribute... any chance to add a small test in order to make CircleCI capturing possible regressions for this issue in the future?

**Comment by giohappy** [comment]
@mwallschlaeger a couple of comments:

- this custom implementation of deserialization doesn't support the default behavior, which [expects to get a PK](https://github.com/AltSchool/dynamic-rest/blob/6489a393ac6319a5ca5717a64a25ee95313bceb6/dynamic_rest/fields/fields.py#L327) for the related field. I would check if the passed data is a single value and, in that case, assume it's the PK and call the default implementation.
- what about `group` and `owner`? I would treat them the same. 

Have you considered the option to override DynamiRelatedField? It think it would cleaner, easier to maintain and to extend to new fields, without haveing to keep track of them inside the
Something like this:

**Comment by mwallschlaeger** [comment]
@giohappy hey, yeah thanks for mentioning it. I was actually not quite happy with the solution provided in this PR as well. I'm thinking about how to imrpove this solution back and forth quite some time. But i like your idea a lot, and will consider and test it.

**Comment by giohappy** [comment]
@mwallschlaeger I hope I'll be able to test your PR today

**Review by afabiani — APPROVED** [review]

**Pull request merged**
