### PR TITLE
Update 500.html - Gender neutral terminology

### PR DESCRIPTION
**Pull request by CamGreen**
Updated the text for the error page to not refer to 'he' but rather 'they'. Small change but just wanted to get started and saw this text error. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
Dear @CamGreen thank you very much for your contribution. We hope to see more PRs coming from you in the future :)

About the CLA, yes, it is required. The process to get it signed is very simple and described here

https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md#contributing

Please let me know if you need further help.

**Comment by afabiani** [comment]
Dear @CamGreen now that you have been added to the contributors, we will need to refine a bit this PR.

We need to follow the checklist and match as much as possible the requirements.

You will need to do the following:

1. Open a github issue describing the problem or improvement you would like to be fixed
2. Be sure all the labels have been assigned to the issue (in case ask a core developer to help)
3. Modify the text of this PR accordingly (see the checklist in order to understand how to do)

**Comment by t-book** [comment]
@afabiani even if it sounds a bit harsh, same here as with the https://github.com/GeoNode/geonode/pull/5391 if there is no answer and issue is missing close? – otherwise I could offer to open a ticket and commit both changes as both make sense ...

**Comment by afabiani** [comment]
Closing as it is not matching the minimum required checks.

@t-book let's recreate those PRs along with tickets. Do you have any resources/time to volunteer? If not I can take care of this.

**Comment by t-book** [comment]
@afabiani 

> let's recreate those PRs along with tickets. Do you have any resources/time to volunteer? If not I can take care of this.

sure will do.

**Pull request closed without merging**
