### PR TITLE
geosites settings.py invalid syntax fix

### PR DESCRIPTION
**Pull request by BerryDaniel**

### CODE REVIEW

**Comment by simod** [comment]
Hi. The syntax is like that because it's compiled by the add site command. Did you test that the site is is set correctly?

**Comment by BerryDaniel** [comment]
@simod When doing the rpmbuild it is failing due to a syntax error.

```bash
Compiling /home/dberry/geonode/rpmbuild/BUILDROOT/python27-geonode-2.4c2-1.el6.x86_64/usr/local/lib/python2.7/site-packages/geonode/contrib/geosites/site_template/settings.py ...
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/site-packages/geonode/contrib/geosites/site_template/settings.py', 21, 11, 'SITE_ID = $SITE_ID  # flake8: noqa\n'))
```

@ingenieroariel suggested to just comment it out.

Open to any suggestions.

**Comment by simod** [comment]
Yeah but I'm afraid geosites won't work anymore. Will think tomorrow :) ok?

Il mercoledì 18 novembre 2015, Daniel Berry <notifications@github.com> ha
scritto:

> @simod <https://github.com/simod> When doing the rpmbuild it is failing
> due to a syntax error.
>
> Compiling /home/dberry/geonode/rpmbuild/BUILDROOT/python27-geonode-2.4c2-1.el6.x86_64/usr/local/lib/python2.7/site-packages/geonode/contrib/geosites/site_template/settings.py ...
> SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/site-packages/geonode/contrib/geosites/site_template/settings.py', 21, 11, 'SITE_ID = $SITE_ID  # flake8: noqa\n'))
>
> @ingenieroariel <https://github.com/ingenieroariel> suggested to just
> comment it out.
>
> Open to any suggestions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/pull/2350#issuecomment-157832543>.
>


-- 
Simone

**Comment by BerryDaniel** [comment]
I think the best way forward is for me to apply a patch file during the build process, so this is not affecting others. We should just close this out.

**Pull request closed without merging**
