### PR TITLE
[Fixes #3884] Update GeoServer to 2.14.x on master

### LINKED ISSUE #3884: Update GeoServer to 2.14.x on master

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by francbartoli** [comment]
sorry @afabiani just noticed you have already done. Thanks

**Comment by afabiani** [comment]
@francbartoli is it possible to create a 2.14.x build on docker hub? I don't have rights to do that

**Comment by francbartoli** [comment]
sure @afabiani! I will grant you too with the privileges, hopefully I should be able

**Comment by francbartoli** [comment]
done, can you double check?

**Comment by afabiani** [comment]
Currently blocked due to this issue on GeoServer

https://osgeo-org.atlassian.net/browse/GEOS-8920

I will trigger the build again as soon as the fix has been deployed

**Comment by afabiani** [comment]
finally passed!

**Pull request merged**
