### PR TITLE
[Fixes #4634] Geoserver doesn't restart with https SPC

### LINKED ISSUE #4634: Geoserver doesn't restart with https SPC
## Expected Behavior
Geoserver starts

## Actual Behavior
Geoserver waiting for postgres but in fact ssl error : 

Message from logs : 
geoserver_1       | keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect

## Steps to Reproduce the Problem

  1. Install Geonode with SPC
  2. Start Geonode with up --build : All Ok
  3. Stop docker containers and restart : Geoserver stuck on waiting for postgis

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPC
  - Platform: Archlinux
  - Additional details:

### PR DESCRIPTION
**Pull request by kikislater**
Geoserver fail on https

Message from logs : 
geoserver_1       | keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect

### CODE REVIEW

**Comment by kikislater** [comment]
Link to issue : https://github.com/GeoNode/geonode/issues/4634

**Comment by gannebamm** [comment]
That's exactly what we at Thünen-Institut do. But my attempt was less sophisticated and was using a env variable as switch. Nice work @kikislater

**Comment by kikislater** [comment]
> using a env variable as switch

Glad it could help ! Which environment variable did you set ? PASSWORD ?
Happy to discuss with you about others issue you find in SPC.

**Comment by francbartoli** [comment]
That's interesting @gannebamm, @kikislater would you like to improve the conditional clause to check for a variable?

Something like:

`if [ "$(ls -A /keystore.jks)" ] || [ -z ${SKIP_INITIALIZATION} ]`

**Comment by kikislater** [comment]
> That's interesting @gannebamm, @kikislater would you like to improve the conditional clause to check for a variable?
> 
> Something like:
> 
> `if [ "$(ls -A /keystore.jks)" ] || [ -z ${SKIP_INITIALIZATION} ]`

Looking forward any improvement !

**Comment by gannebamm** [comment]
Just for additional information. This is how I implemented the 'switch'. I found this behaviour while doing disaster recovery from an backup, therefore it is called 'RECOVERY'
```
# If we recover from a backup geoserver data dir the keystore is allready initialized
# GeoServer will not accept the old keystore due to mismatches
# therefore we could skip this if we use the flag RECOVERY:
if [ ! -z "$RECOVERY" ]; then
    # https://docs.geoserver.org/stable/en/user/community/oauth2/index.html#ssl-trusted-certificates    
    if [ ! -z "$HTTPS_HOST" ]; then
        PASSWORD=$(openssl rand -base64 18)

        openssl s_client -connect ${HTTPS_HOST#https://}:${HTTPS_PORT} </dev/null |
            openssl x509 -out server.crt

        # create a keystore and import certificate
        keytool -import -noprompt -trustcacerts \
                -alias ${HTTPS_HOST} -file server.crt \
                -keystore /keystore.jks -storepass ${PASSWORD}

        rm server.crt

        JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.keyStore=/keystore.jks -Djavax.net.ssl.keyStorePassword=$PASSWORD"
    fi
fi
```

**Comment by kikislater** [comment]
Interesting, thank you for sharing !

**Comment by Itsman-AT** [comment]
> 
> fi
> ```

Hi Florian,
sorry for my ignorance: But into which file did you insert the above code? I have the exact same problem with my certifcate after testing the Let's Encrypt certificate mode "production" and then switching back to "disabled" (which is no suprise, though).
PS: I guess I also should consider updating the whole GeoNode installation on our server to fix the issue (which I am a bit scared of, at the moment).

**Comment by gannebamm** [comment]
@Itsman-AT We *had* this in /scripts/spcgeonode/geoserver/docker-entrypoint.sh but changed our codebase to be aligned with geonode 2.10.1
Look how it checks if a keystore is present: https://github.com/GeoNode/geonode/blob/2.10.1/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L141

**Comment by Itsman-AT** [comment]
Thanks, will check this (and also the possibility to update the system).

**Comment by Itsman-AT** [comment]
I am no facing these errors. Any hint for me:
`
geoserver_1    | 04 Dec 16:03:10 INFO [ows.OWSHandlerMapping] - Mapped URL path [/animate] onto handler 'dispatcher'
geoserver_1    | 2019-12-04 16:03:13.683:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@5594a1b5{/geoserver,file:/geoserver/webapps/geoserver/,STARTING}{/geoserver}
geoserver_1    | org.springframework.beans.factory.BeanCreationException: Error occured reading security configuration; nested exception is java.io.IOException: org.xml.sax.SAXParseException; cvc-identity-constraint.4.2.2: Duplicate key value [super] declared for identity constraint "UserKey" of element "userRegistry".
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.reload(GeoServerSecurityManager.java:434)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.onApplicationEvent(GeoServerSecurityManager.java:368)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
geoserver_1    |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
geoserver_1    |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
geoserver_1    |        at org.geoserver.platform.GeoServerContextLoaderListener.contextInitialized(GeoServerContextLoaderListener.java:25)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
geoserver_1    |        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
geoserver_1    |        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
geoserver_1    |        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:440)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
geoserver_1    |        at org.eclipse.jetty.server.Server.start(Server.java:387)
geoserver_1    |        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
geoserver_1    |        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
geoserver_1    |        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
geoserver_1    |        at java.security.AccessController.doPrivileged(Native Method)
geoserver_1    |        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
geoserver_1    |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
geoserver_1    |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
geoserver_1    |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
geoserver_1    |        at java.lang.reflect.Method.invoke(Method.java:498)
geoserver_1    |        at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
geoserver_1    |        at org.eclipse.jetty.start.Main.start(Main.java:817)
geoserver_1    |        at org.eclipse.jetty.start.Main.main(Main.java:112)
geoserver_1    | Caused by:
geoserver_1    | java.io.IOException: org.xml.sax.SAXParseException; cvc-identity-constraint.4.2.2: Duplicate key value [super] declared for identity constraint "UserKey" of element "userRegistry".
geoserver_1    |        at org.geoserver.security.xml.XMLValidator.validateUserGroupRegistry(XMLValidator.java:57)
geoserver_1    |        at org.geoserver.security.xml.XMLUserGroupService.deserialize(XMLUserGroupService.java:151)
geoserver_1    |        at org.geoserver.security.xml.XMLUserGroupService.initializeFromConfig(XMLUserGroupService.java:112)
geoserver_1    |        at org.geoserver.security.concurrent.LockingUserGroupService.initializeFromConfig(LockingUserGroupService.java:242)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager$UserGroupServiceHelper.load(GeoServerSecurityManager.java:2959)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.loadUserGroupService(GeoServerSecurityManager.java:1233)
geoserver_1    |        at org.geoserver.security.auth.UsernamePasswordAuthenticationProvider.initializeFromConfig(UsernamePasswordAuthenticationProvider.java:43)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager$AuthProviderHelper.load(GeoServerSecurityManager.java:3312)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.init(GeoServerSecurityManager.java:633)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.init(GeoServerSecurityManager.java:575)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.reload(GeoServerSecurityManager.java:428)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.onApplicationEvent(GeoServerSecurityManager.java:368)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
geoserver_1    |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
geoserver_1    |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
geoserver_1    |        at org.geoserver.platform.GeoServerContextLoaderListener.contextInitialized(GeoServerContextLoaderListener.java:25)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
geoserver_1    |        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
geoserver_1    |        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
geoserver_1    |        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:440)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
geoserver_1    |        at org.eclipse.jetty.server.Server.start(Server.java:387)
geoserver_1    |        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
geoserver_1    |        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
geoserver_1    |        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
geoserver_1    |        at java.security.AccessController.doPrivileged(Native Method)
geoserver_1    |        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
geoserver_1    |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
geoserver_1    |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
geoserver_1    |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
geoserver_1    |        at java.lang.reflect.Method.invoke(Method.java:498)
geoserver_1    |        at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
geoserver_1    |        at org.eclipse.jetty.start.Main.start(Main.java:817)
geoserver_1    |        at org.eclipse.jetty.start.Main.main(Main.java:112)
geoserver_1    | Caused by:
geoserver_1    | org.xml.sax.SAXParseException; cvc-identity-constraint.4.2.2: Duplicate key value [super] declared for identity constraint "UserKey" of element "userRegistry".
geoserver_1    |        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
geoserver_1    |        at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.XMLSchemaValidator$KeyValueStore.checkDuplicateValues(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.XMLSchemaValidator$ValueStoreBase.addValue(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.identity.Field$Matcher.matched(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.identity.XPathMatcher.startElement(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.identity.Selector$Matcher.startElement(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
geoserver_1    |        at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
geoserver_1    |        at org.apache.xerces.jaxp.validation.DOMValidatorHelper.beginNode(Unknown Source)
geoserver_1    |        at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
geoserver_1    |        at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
geoserver_1    |        at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
geoserver_1    |        at javax.xml.validation.Validator.validate(Validator.java:124)
geoserver_1    |        at org.geoserver.security.xml.XMLValidator.validateUserGroupRegistry(XMLValidator.java:55)
geoserver_1    |        at org.geoserver.security.xml.XMLUserGroupService.deserialize(XMLUserGroupService.java:151)
geoserver_1    |        at org.geoserver.security.xml.XMLUserGroupService.initializeFromConfig(XMLUserGroupService.java:112)
geoserver_1    |        at org.geoserver.security.concurrent.LockingUserGroupService.initializeFromConfig(LockingUserGroupService.java:242)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager$UserGroupServiceHelper.load(GeoServerSecurityManager.java:2959)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.loadUserGroupService(GeoServerSecurityManager.java:1233)
geoserver_1    |        at org.geoserver.security.auth.UsernamePasswordAuthenticationProvider.initializeFromConfig(UsernamePasswordAuthenticationProvider.java:43)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager$AuthProviderHelper.load(GeoServerSecurityManager.java:3312)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.init(GeoServerSecurityManager.java:633)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.init(GeoServerSecurityManager.java:575)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.reload(GeoServerSecurityManager.java:428)
geoserver_1    |        at org.geoserver.security.GeoServerSecurityManager.onApplicationEvent(GeoServerSecurityManager.java:368)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
geoserver_1    |        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
geoserver_1    |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
geoserver_1    |        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
geoserver_1    |        at org.geoserver.platform.GeoServerContextLoaderListener.contextInitialized(GeoServerContextLoaderListener.java:25)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
geoserver_1    |        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
geoserver_1    |        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
geoserver_1    |        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
geoserver_1    |        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
geoserver_1    |        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:440)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
geoserver_1    |        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
geoserver_1    |        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
geoserver_1    |        at org.eclipse.jetty.server.Server.start(Server.java:387)
geoserver_1    |        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
geoserver_1    |        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
geoserver_1    |        at org.eclipse.jetty.server.Server.doStart(Server.java:354)
geoserver_1    |        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
geoserver_1    |        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
geoserver_1    |        at java.security.AccessController.doPrivileged(Native Method)
geoserver_1    |        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
geoserver_1    |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
geoserver_1    |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
geoserver_1    |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
geoserver_1    |        at java.lang.reflect.Method.invoke(Method.java:498)
geoserver_1    |        at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
geoserver_1    |        at org.eclipse.jetty.start.Main.start(Main.java:817)
geoserver_1    |        at org.eclipse.jetty.start.Main.main(Main.java:112)
geoserver_1    | 2019-12-04 16:03:13.723:INFO:oejs.ServerConnector:main: Started ServerConnector@f769ade{HTTP/1.1}{0.0.0.0:8080}
geoserver_1    | 2019-12-04 16:03:13.725:INFO:oejs.Server:main: Started @26859ms
django_1       | -----------------------------------------------------
django_1       | 9. Securing GeoServer
django_1       | Traceback (most recent call last):
django_1       |   File "scripts/spcgeonode/django/initialize.py", line 156, in <module>
django_1       |     r1.raise_for_status()
django_1       |   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
django_1       |     raise HTTPError(http_error_msg, response=self)
django_1       | requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://geoserver:8080/geoserver/rest/security/masterpw.json
django_1       | /usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
django_1       |   """)
django_1       | JSONField implementation is: <class 'jsonfield.fields.JSONField'>
django_1       | -----------------------------------------------------
`

**Pull request merged**
