### PR TITLE
[Fixes #7717] Temporary files created under static root are never rem…

### LINKED ISSUE #7717: Temporary files created under static root are never removed
There are many situations where temp files are created under static root (prepare zip for download, unzip folders, etc.).
None of these methods appear to correctly remove these temp files, which makes the static root grow indefintely.

Ex.
 - resource download: https://github.com/GeoNode/geonode/blob/347a2053d179721b3dec53410d67757a563114d1/geonode/proxy/views.py#L283
 - unzip files: https://github.com/GeoNode/geonode/blob/347a2053d179721b3dec53410d67757a563114d1/geonode/utils.py#L119

We must check all the places where this is done and correctly handle the revoal of temp files, including exceptions.

### PR DESCRIPTION
**Pull request by afabiani**
…oved

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by mattiagiupponi — CHANGES_REQUESTED** [review]
I'll consider adding a check to verify that the temp folder exists. Because (for any reason) if the folder has been deleted during the operations, on the `shutil.rmtree(_tmpdir)` this will raise an error. Maybe something like this could be enough to prevent it:
```python
if os.path.exists(tempdir) and tempdiris not None
    shutil.rmtree(tempdir)
```

**Comment by afabiani** [comment]
> I'll consider adding a check to verify that the temp folder exists. Because (for any reason) if the folder has been deleted during the operations, on the `shutil.rmtree(_tmpdir)` this will raise an error. Maybe something like this could be enough to prevent it:
> 
> ```python
> if os.path.exists(tempdir) and tempdiris not None
>     shutil.rmtree(tempdir)
> ```

I would prefer to avoid existence checks. Instead I would use the following options of the `shutil.rmtree` method eventually

`def rmtree(path, ignore_errors=False, onerror=None)`

**Comment by mattiagiupponi** [comment]
> I would prefer to avoid existence checks. Instead, I would use the following options of the `shutil.rmtree` method eventually
>
> `def rmtree(path, ignore_errors=False, onerror=None)`

Maybe using `ignore_errors=True` could not be the best approach since it just silently ignore errors.
from the doc:

>  If ignore_errors is true, errors resulting from failed removals will be ignored; if false or omitted, such errors are handled by calling a handler specified by onerror or, if that is omitted, they raise an exception.

For example, if the error raised is a `NotFound` is fine that we can ignore it, but if it raises an error regarding the User / App permissions on the filesystem/storage system, is correct that an `Exception` is raised, but with `ignore_errors=True`, you are just ignoring a potential issue.
I think that just checking the existence of the directory could the safest approach

**Comment by afabiani** [comment]
> > I would prefer to avoid existence checks. Instead, I would use the following options of the `shutil.rmtree` method eventually
> > `def rmtree(path, ignore_errors=False, onerror=None)`
> 
> Maybe using `ignore_errors=True` could not be the best approach since it just silently ignore errors.
> from the doc:
> 
> > If ignore_errors is true, errors resulting from failed removals will be ignored; if false or omitted, such errors are handled by calling a handler specified by onerror or, if that is omitted, they raise an exception.
> 
> For example, if the error raised is a `NotFound` is fine that we can ignore it, but if it raises an error regarding the User / App permissions on the filesystem/storage system, is correct that an `Exception` is raised, but with `ignore_errors=True`, you are just ignoring a potential issue.
> I think that just checking the existence of the directory could the safest approach

The `onerror` callback is supposed to catch this... however in this specific case we don't care about catching the exception... we are just trying to delete a temp folder.
If we need a hard stop we will need to manage the specific case.
The existence check is FS specific and we are migrating to the storage manager.

**Pull request merged**
