### PR TITLE
Set to 2.5 final version for release

### PR DESCRIPTION
**Pull request by BerryDaniel**

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@BerryDaniel ... @simod and I were trying to get the hierarchical keywords branch merged before the 2.5 as it has some schema changes. Can you give us a chance to fix the one failing test before you cut 2.5?

**Comment by BerryDaniel** [comment]
2.5 tag and release have been completed. We might be able to delete it and
run it again or do a 2.5.1 release?

**Comment by jj0hns0n** [comment]
I guess 2.5.1 is ok, we will probably tag a few more this way right? Did
you guys push packages yet?

**Comment by simod** [comment]
don't think so. note: we never pushed the "final" version in master so to have the dev version appearing on it. Should we roll it back then? Paver publish will take care of all the tagging for us.

**Comment by jj0hns0n** [comment]
yeah, lets do.

**Pull request merged**
