### PR TITLE
[Fixes #7735] Editing layer metadata in admin interface throws an error

### LINKED ISSUE #7735: Editing layer metadata in admin interface throws an error
## Expected Behavior
Saving edited layer in django admin interface should succeed. 

## Actual Behavior
image

## Steps to Reproduce the Problem
  1. Prepare docker installation of GeoNode
  2. Upload layer
  3. Go to admin interface -> layers and edit uploaded layer
  4. Click save

## Specifications
  - GeoNode version: 3.2.0
  - Installation method: GeoNode Docker
  - Platform: Ubuntu Linux with docker
  - Additional details:
     Here is the content of the debug page: 
[TypeError.at._pl_admin_layers_layer_1_change_.zip](https://github.com/GeoNode/geonode/files/6763359/TypeError.at._pl_admin_layers_layer_1_change_.zip)

### PR DESCRIPTION
**Pull request by virdiignis**
Updated add() method in _HierarchicalTagManager to fit django-taggit and Django 2.2.
I tried to expand add() method with all the functionality added to the original in django-taggit. Fixes #7735. I didn't manage to run tests locally, so will take a look at CircleCI results.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@virdiignis thanks for your contribution, I have tested the fix and this is working as expected.

Two things before merging the PR:

1. Are you able to sign the CLA? If not I can close this PR and recreate it for you since the fix is small
2. It would be good to put a specific test case in order to avoid we face this regression again in the future

**Comment by virdiignis** [comment]
@afabiani
1. I am. Where should I send it?
2. I'll try.

**Comment by giohappy** [comment]
@virdiignis you can read how to fill and send the CLA here https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md

**Comment by afabiani** [comment]
Superseded by https://github.com/GeoNode/geonode/pull/7808

**Pull request closed without merging**
