### PR TITLE
[Fixes:#7488] Prevent /o endpoints

### PR DESCRIPTION
**Pull request by t-book**
@afabiani Let's keep it a draft until it's sure it passes tests (and I have done further testing). Find a more advanced URLs setup here https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_02.html (scroll down a bit). This advanced version would respect debug. But let's try to keep it simple.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
My plan was to add some tests but what I see looks solid: https://github.com/GeoNode/geonode/blob/master/geonode/api/tests.py#L213-L248

**Comment by afabiani** [comment]
@t-book how this will work with the current tokens endpoints used by GeoServer, like the following one as an instance?

image

**Comment by t-book** [comment]
@afabiani the idea is to only import base_urlpatterns
https://github.com/GeoNode/geonode/pull/7489/files#diff-183649a047cf2b64cc7880f7e6c0904c21a166c17cc99733f1d56cbae75f102dR46

and get read of the development views, where users can add apps.

_base_urlpatterns_ should cover the token endpoint you're asking for     
https://github.com/GeoNode/geonode-oauth-toolkit/blob/df5deaf865f78fcf0cf346b0ff23dfe052422d5d/oauth2_provider/urls.py#L11

**Comment by giohappy** [comment]
@t-book probably I missed somthing but what's the purpose of this change?

**Comment by t-book** [comment]
@giohappy see the conversation at the psc list

**Comment by t-book** [comment]
> @t-book I'm a bit worried about the prefix change.
> 
> Please take a look at my proposal here https://github.com/GeoNode/geonode/pull/7509/files#diff-183649a047cf2b64cc7880f7e6c0904c21a166c17cc99733f1d56cbae75f102d

@afabiani looks good! if ci does not fail please go ahead. I will close here in favour of your PR

**Pull request closed without merging**
