### PR TITLE
#3460 add oauth2 client support

### PR DESCRIPTION
**Pull request by afabiani**
@author https://github.com/ricardogsilva

This PR adds Oauth2 client support for geonode, allowing a user to register and login with external account providers, like linkedin or facebook. It relates to geonode issue #3460.

In order to harmonize the various authentication flows between local accounts and remote social accounts, the whole user registration and authentication codebase has been refactored.

Major changes:

- [geonode-user-accounts](https://github.com/GeoNode/geonode-user-accounts) has been retired and is not used anymore. This app was only capable of managing local accounts;
- [django-allauth](https://github.com/pennersr/django-allauth) has been integrated as a dependency of geonode. It provides a solution for managing both local and remote user accounts. It is now used for dealing with most user registration and auth flows;
- [django-invitations](https://github.com/bee-keeper/django-invitations) has also been integrated as a dependency of geonode and is used for managing invitations to new users. This functionality was previously provided by geonode-user-accounts;
- django-allauth has been extended in order to provide the following additional features:

  - Automatically registering an e-mail with a user when the e-mail is used to connect to a social account;
  - Automatically extract information from the user's social account and use that to enhance the user's profile fields on geonode. This was implemented in a pluggable way, allowing custom installs to configure it for other providers;
  - Allow approval of new registrations by staff members before allowing new users to login. This functionality was previously  provided by geonode-user-accounts.

- There are now extra sections on the user's profile to manage connected social accounts and e-mail accounts
  manage_social_accounts_email

- When properly configured, the login and register pages now display the possibility to login with social accounts
  login_social_accounts

This PR changes many files. However, most changes are really just templates being updated. The body of the changes, in terms of actual code, is in the `geonode.people` app.

**To Setup**
```pip install -r requirements.txt --no-deps --no-cache
pip uninstall geonode-user-accounts -y
pip uninstall django-user-accounts -y
pip install -r requirements.txt
DJANGO_SETTINGS_MODULE=geonode.local_settings paver sync
```

### CODE REVIEW

**Comment by francbartoli** [comment]
@afabiani I've got this error while starting your branch in dev mode:

```
paver sync
---> pavement.sync
python manage.py makemigrations --noinput
CommandError: Conflicting migrations detected (0004_auto_20171108_1101, 0002_auto_20171101_1139 in user_messages).
To fix them run 'python manage.py makemigrations --merge'
```

Trying to fix with the merge leads to:

`django.core.exceptions.FieldDoesNotExist: Thread has no field named u'users'`

Back to master for adding the base configuration for bdd.

**Comment by francbartoli** [comment]
Previous comment it was totally my fault. Sorry @afabiani, I don't know why but uninstalling geonode-user-messages didn't delete and clean this package at all from my virtual environment. An old migration was left and broke geonode.

**Comment by afabiani** [comment]
@francbartoli do I have to take some action here?

**Comment by francbartoli** [comment]
@afabiani not yet. PR bdd setup soon then we can try to do something over here together

**Pull request merged**
