### PR TITLE
Set max_length=255 for doc_file and doc_url in document model

### PR DESCRIPTION
**Pull request by capooti**
Set max_length=255 for doc_file and doc_url in document model as per #2285

### CODE REVIEW

**Comment by simod** [comment]
@capooti wouldn't this break existing databases?

**Comment by capooti** [comment]
I don't think so, as it is just setting the field length to an higher value for new synced database.
Though best practice here it would be to have a migration script, so we may postpone this to 2.5.

**Comment by simod** [comment]
I'm afraid that the db would complain if we allow more that 100 but the it has a constraint of 100. Unless we will provide a migrations script.

**Comment by capooti** [comment]
apparently this is already happening according to #2285. We need to make
sure that the form does not accept file names longer than 100 chars then.

On Tue, Sep 29, 2015 at 9:39 AM, Simone Dalmasso <notifications@github.com>
wrote:

> I'm afraid that the db would complain if we allow more that 100 but the it
> has a constraint of 100. Unless we will provide a migrations script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/pull/2288#issuecomment-143974342>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by jj0hns0n** [comment]
@capooti should we go ahead and merge this one now?

**Comment by capooti** [comment]
Yes, given that now we can do schema changes.
Should we start using Django migrations for schema changes, by the way? (this way will be easier to update production systems)

**Comment by simod** [comment]
@capooti +1 for the migrations, not sure that django 1.6 has migrations yet but we should also upgrade it to the latest.

**Comment by capooti** [comment]
Yes, now I think south is integrated in django.
let's do this: when we will updated django to the latest (time to do it, imho, let me know if I may help), I will add the migration to this PR, and then we merge it

**Comment by jj0hns0n** [comment]
@capooti Can we go ahead and merge this now?

**Comment by capooti** [comment]
Sure! Go ahead

**Pull request merged**
