### PR TITLE
added mapbox api basemaps functionality

### PR DESCRIPTION
**Pull request by BerryDaniel**
Added mapbox api basemaps functionality if MAPBOX_ACCESS_TOKEN is set.

fix for #2478 

- created an api_basemaps app under geonode.contrib
- moved bing basemap to api_basemaps
- set default value for both to None and check for os.environ for both

### CODE REVIEW

**Comment by ingenieroariel** [comment]
:+1:

**Comment by JJediny** [comment]
Just note that XYZ tile basemaps at least in pre-2.4ish - dependent on Geoexplorer version = loaded/requested tiles whether they were activated or not. Someone should test that XYZ basemaps arent loading in the background on zoom from web browsers development console

**Comment by BerryDaniel** [comment]
@JJediny That does not appear to be the case

**Comment by BerryDaniel** [comment]
@mtirwin

**Comment by mtirwin** [comment]
@BerryDaniel flagging that [our tiles-from-styles API serves 512 x 512 px tiles by default](https://www.mapbox.com/api-documentation/#retrieve-raster-tiles-from-styles). If OL is expecting 256 x 256 px tiles, you'll want to flag that in the query param like this:

`https://api.mapbox.com/styles/v1/mapbox/%s/tiles/256/${z}/${x}/${y}?access_token=%s`

cc/ @tmcw @lyzidiamond @maning

**Comment by BerryDaniel** [comment]
added the 256 addition, thanks @mtirwin

**Pull request merged**
