### PR TITLE
Complete Translate pt_BR

### PR DESCRIPTION
**Pull request by edsonflavio**
Tradução completa da localização para Português Brasileiro. Complete translate for pt_BR localization.

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — APPROVED** [review]

**Review by edsonflavio — COMMENTED** [review]
Hi Alessio,
I sign and send CLA today for info@osgeo.org.
Can you review and aprove my changes?
thanks.

**Comment by afabiani** [comment]
@edsonflavio can you please create the PR for the 4.0.x branch too? Name it "[Backport to 4.0.x] Complete Translate pt_BR" please. thanks

**Comment by edsonflavio** [comment]
I created a new PR.

Can you check, please?

Edson Flavio de Souza


Inove, confie, ouse, compartilhe. Façamos diferente, mas juntos.
________________________________
De: Alessio Fabiani ***@***.***>
Enviado: quarta-feira, 28 de setembro de 2022 05:31
Para: GeoNode/geonode ***@***.***>
Cc: Edson Flavio de Souza ***@***.***>; Mention ***@***.***>
Assunto: Re: [GeoNode/geonode] Complete Translate pt_BR (PR #10056)


@edsonflavio<https://github.com/edsonflavio> can you please create the PR for the 4.0.x branch too? Name it "[Backport to 4.0.x] Complete Translate pt_BR" please. thanks

**Comment by edsonflavio** [comment]
Hello,

I sign and send CLA, today.

You can review please.

Edson Flavio de Souza


Inove, confie, ouse, compartilhe. Façamos diferente, mas juntos.
________________________________
De: cla-bot[bot] ***@***.***>
Enviado: terça-feira, 27 de setembro de 2022 09:29
Para: GeoNode/geonode ***@***.***>
Cc: Edson Flavio de Souza ***@***.***>; Mention ***@***.***>
Assunto: Re: [GeoNode/geonode] Complete Translate pt_BR (PR #10056)


Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have the users @edsonflavio<https://github.com/edsonflavio> on file. In order for us to review and merge your code, please contact the project maintainers to get yourself added.

**Comment by afabiani** [comment]
@edsonflavio thanks, we need you to update/recreate the files in the backport PR [here](https://github.com/GeoNode/geonode/pull/10093) since there are some conflicts preventing us on merging this one. Thanks.

**Pull request merged**
