### PR TITLE
.txt and .html metadata exports

### PR DESCRIPTION
**Pull request by artists974**
Hi,

These additions allow users to download metadata in .txt and .html formats.
It works perfectly well with my instance of Geonode, but I noticed some changes between mine and core GeoNode (in urls.py for example). However, this code should normally work, but let me know if there is a problem.

Thanks !

### CODE REVIEW

**Comment by simod** [comment]
Hi, the tests are failing. I suggest you to run $paver test and paver test_integration locally and see what happens.
We also usually recommend to squash the commits into a single one before accepting pull requests, could you please do that as well? Thanks

**Comment by artists974** [comment]
Ok, I will check that as soon as I can.
(Sorry about the multiple commits, git is quite new for me...)

Antoine Rolland

**Comment by pjdufour** [comment]
@artists974, please squash your commits (compress your mulitple commits into 1 commit).  You can use something like:

```
git rebase -i HEAD~10
```

It's a slightly dangerous operation, so I'm sure someone can help you through it or do the final merge for you.  Here to help.  Thanks for the PR!

**Comment by artists974** [comment]
Hi, I tried paver test and paver test_integration locally on my branch, and I met problems. As I thought these problems were just about my branch, I downloaded GeoNode core code from GeoNode GitHub page once again, and did a paver test and paver test_integration locally, on the master branch, and I meet the same problem than for my branch... : 

$ paver test
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
---> pavement.test
python manage.py test geonode.people.tests geonode.base.tests geonode.layers.tests geonode.maps.tests geonode.proxy.tests geonode.security.tests geonode.social.tests geonode.catalogue.tests geonode.documents.tests geonode.api.tests geonode.groups.tests geonode.services.tests geonode.geoserver.tests geonode.upload.tests geonode.tasks.tests --noinput
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named storages


Captured Task Output:
---------------------

---> pavement.test
python manage.py test geonode.people.tests geonode.base.tests geonode.layers.tests geonode.maps.tests geonode.proxy.tests geonode.security.tests geonode.social.tests geonode.catalogue.tests geonode.documents.tests geonode.api.tests geonode.groups.tests geonode.services.tests geonode.geoserver.tests geonode.upload.tests geonode.tasks.tests --noinput

Build failed running pavement.test: Subprocess return code: 1


$ paver test_integration
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
---> pavement.test_integration
rm -rf geonode/development.db
rm -rf geonode/uploaded/*


Captured Task Output:
---------------------

---> pavement.test_integration
rm -rf geonode/development.db
rm -rf geonode/uploaded/*
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 446, in test_integration
    _reset()
  File "pavement.py", line 498, in _reset
    _install_data_dir()
  File "pavement.py", line 119, in _install_data_dir
    with open(config) as f:
IOError: [Errno 2] No such file or directory: path('geoserver/data/security/auth/geonodeAuthProvider/config.xml')

I really have no idea what to do...

**Comment by simod** [comment]
seems that your installation is incomplete like geoserver is missing from the expected place and not all dependencies are installed. Running locally for me it works. Did you run paver setup before?

**Comment by artists974** [comment]
I just did ran paver setup, and did a paver test and paver test_integration. I have the same errors in paver test, but paver test_integration error changed : 

$ paver test_integration
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
---> pavement.test_integration
rm -rf geonode/development.db
rm -rf geonode/uploaded/*
rmtree geoserver/data
---> pavement.start_geoserver
cd geonode/geoserver/data
java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
java -Xmx512m -XX:MaxPermSize=256m -DGEOSERVER_DATA_DIR=geonode/geoserver/data -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar 
geonode/downloaded/jetty-runner-8.1.8.v20121106.jar --port 8080 --log 
geonode/geoserver/jetty.log geonode/scripts/misc/jetty-runner.xml > /dev/null &
cd geonode
Starting GeoServer on http://localhost:8080/geoserver/
The logs are available at geonode/geoserver/jetty.log
GeoNode is now available, running the tests now.
python manage.py test geonode.tests.integration --noinput --liveserver=localhost:8000
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named storages
Tests failed! Subprocess return code: 1
---> pavement.stop
---> pavement.stop_geoserver
2016-06-29 15:47:05.026:INFO:omjr.Runner:Runner
2016-06-29 15:47:05.027:WARN:omjr.Runner:No tx manager found
Stopping java (process number 4200)
Stopping GeoNode ...
---> pavement.stop_django
rm -rf geonode/development.db
rm -rf geonode/uploaded/*
rmtree geoserver/data

**Pull request closed without merging**
