### PR TITLE
[Fixes #7826] Implement tests for harvesters

### LINKED ISSUE #7826: Implement tests for harvesters
Based on https://github.com/geosolutions-it/nexus-geonode/issues/314

## Overview
This should have been done along the development. In any case this is urgent. At least 60% coverage must be granted

### PR DESCRIPTION
**Pull request by meomancer**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by meomancer** [comment]
This fix https://github.com/GeoNode/geonode/issues/7826
cc @ricardogsilva

**Review by ricardogsilva — CHANGES_REQUESTED** [review]
The current implementation seems overly complex. Tests should ideally be simple, otherwise we start needing to write tests to check for the correctness of tests.

With this in mind, please do not use abstract base classes in tests. IMO, multiple inheritance in a test case is also something to avoid. The bottom line is we would like tests to be easy to read, even serving as an example of features.

Please try to keep it simple and dumb :smile:. Perhaps taking a look at other pre-existing test cases for GeoNode might be a good start?

Write tests for: 

- `harvesting.config.py`
- `harvesting.tasks.py`
- `harvesting.harvesters.base.py`
- `harvesting.harvesters.geonode.py`
- `harvesting.models.py`
- `harvesting.api.serializers.py`

**Comment by meomancer** [comment]
hi @ricardogsilva 
updated

**Comment by ricardogsilva** [comment]
@meomancer 

I've pushed a commit adding some more tests and renaming some names in order to better conform to django naming conventions.

I think we should add some more tests for the `API` and the `admin` sections.

I added the `test_api_views.py` module but it is still a bit crude. Please add some more tests there. Something I think we should cover is testing that API views are protected from unauthorized users.

Also, please add some tests for `admin.py` since there is some business logic in there.

**Comment by giohappy** [comment]
@meomancer conflicts to fix

**Comment by meomancer** [comment]
Conflicts fixed and PR updated @ricardogsilva @giohappy

**Review by ricardogsilva — APPROVED** [review]
Looks good, LGTM!

**Comment by ricardogsilva** [comment]
@afabiani I'm not sure what is happening with the CI checks here. Could this be unrelated to this PR?

I can run tests locally with docker-compose and stuff seems to be working OK? Can you take a look?

**Comment by giohappy** [comment]
@ricardogsilva django containers fail to start

image

**Comment by ricardogsilva** [comment]
@afabiani we need some input here, as the tests seem to work locally on my docker-compose stack.

I don't see any relevant info on the CI logs, so don't really know what is causing it to fail.

**Comment by meomancer** [comment]
hi @ricardogsilva @giohappy 
This is because of this line
https://github.com/GeoNode/geonode/pull/7827/commits/118e694bdd92a902a3e3e6f74634a66f6b523f0b#diff-7ac86826e82ce3199d439a18a94ee054c7f4112698d2df0281463ee2d5a4b222R53
Geonode does not have HARVESTER_CLASS in settings, making `getattr(settings, setting_key)` is error

Could you retry @giohappy ?

**Comment by giohappy** [comment]
@meomancer branch updated. Tests are running again. let's see...

**Comment by giohappy** [comment]
@meomancer tests are failing, can you check please?

**Comment by meomancer** [comment]
hi @giohappy 
there was error on migrations
i already fix it, please check this PR

**Comment by giohappy** [comment]
@ricardogsilva @meomancer please finalize this PR (fix PEP8 issues).

**Review by ricardogsilva — APPROVED** [review]
Looks OK, LGTM

**Pull request merged**
