### PR TITLE
[Fixes #7854] Trasnform detail_url to a property and return URL depending on the client

### LINKED ISSUE #348: Error when uploading avatar in 1.2beta1
This may be a compatibility problem with Django 1.4 and django-avatar. @ischneider told me something about it a while ago.

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/avatar/add/

Django Version: 1.4
Python Version: 2.7.0
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django_extensions',
 'registration',
 'profiles',
 'avatar',
 'dialogos',
 'agon_ratings',
 'taggit',
 'south',
 'geonode.core',
 'geonode.maps',
 'geonode.proxy')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware')


Traceback:
File "/Users/ingenieroariel/work/geonode/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                         response = callback(request, *callback_args, **callback_kwargs)
File "/Users/ingenieroariel/work/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  20.                 return view_func(request, *args, **kwargs)
File "/Users/ingenieroariel/work/geonode/src/avatar/avatar/views.py" in add
  71.             request.user.message_set.create(
File "/Users/ingenieroariel/work/geonode/lib/python2.7/site-packages/django/utils/functional.py" in inner
  185.         return func(self._wrapped, *args)

Exception Type: AttributeError at /avatar/add/
Exception Value: 'User' object has no attribute 'message_set'
```

### LINKED ISSUE #7854: Transform detail_url to a property and return URL depending on the client
## Expected Behavior
- Make `self get_absolute_url` return [layer_detail_url and layers_list_url](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py#L150-L154) hookset returned values
- Trasnform ResourceBase detail_url into a property, which will return self.get_absolute_url() response

## Actual Behavior
ResourcesBase.detail_url is a field holding the URL of the detail page. In view of removing any dependency between core and client we want to make an initial step by turning the field into a property, which will return the detail url dynamically.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by marthamareal**
References #7854

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by mattiagiupponi — DISMISSED** [review]
@marthamareal the reference issue in the title is wrong, should be changed with #7854
The rest LGTM.

**Comment by giohappy** [comment]
@marthamareal tests are still failing

**Comment by marthamareal** [comment]
> @marthamareal tests are still failing

going to check them.

**Comment by marthamareal** [comment]
@giohappy I updated this.

**Review by afabiani — CHANGES_REQUESTED** [review]
Please fix LGTM issues [here](https://lgtm.com/projects/g/GeoNode/geonode/rev/pr-438e5ed8ad5ce75cd0fdc54526ba1e841b398d35)

**Comment by marthamareal** [comment]
@afabiani I solved the LGTMs by removing the unused imports [here](https://github.com/GeoNode/geonode/pull/7855/files#diff-a1e2c399564784bf6260dd16ef41a914dce1e27683e534aef013065e42f5b811)

**Pull request merged**
