### PR TITLE
Fixes #5311 user_messages div does not completely disappear

### LINKED ISSUE #5311: user_messages div does not completely disappear
## Expected Behavior
When you log in or log out to/from GeoNode you see a message for some seconds that you successfully logged in /out. When the message automatically disappeared, you can click buttons where to message was displayed.

## Actual Behavior
The message-div is not visible anymore, but the div is still present in the DOM and overlays underlying buttons or fields which cannot be pressed. The problem is, that the div's opacity is changed to 0, but in addition the visibility must be set to hidden.

I will provide a PR later.

Bildschirmfoto von 2019-11-25 15-21-43

## Steps to Reproduce the Problem

  1. Login 
  2. Try pressing buttons, where the div was.
  3.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu
  - Additional details:

### PR DESCRIPTION
**Pull request by sjohn-atenekom**
added `visibility: hidden;` to keyframe for msgDisappear. Now the div #user_message is hidden and does not overlay the site anymore.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
@afabiani good! thanks for double-checking!

**Comment by sjohn-atenekom** [comment]
Alright. Thanks @afabiani for the hint. I will fix that.

**Comment by sjohn-atenekom** [comment]
@afabiani Done.

**Comment by afabiani** [comment]
@sjohn-atenekom thanks!

**Pull request merged**
