### PR TITLE
[GNIP #3485] - GNIP: Add support for vector temporal series to GeoNode (CSV/SHP). #3485

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by francbartoli** [comment]
I have tried within a clean repo clone and virtualenv:

`git clone https://github.com/GeoNode/geonode.git`
`git fetch origin pull/3558/head:timeseries`
`git checkout timeseries`
`pip install -r requirements.txt`
`pip install pygdal==1.11.3.3`
`pip install -e .`
`paver setup`

`paver setup` is failing:

---> pavement.setup
---> pavement.setup_geoserver
makedirs path('downloaded')
makedirs path('geoserver')
Traceback (most recent call last):
  File "/home/osboxes/.pyenv/versions/2.7.14/envs/geonode/lib/python2.7/site-packages/paver/tasks.py", line 196, in _run_task
    return do_task()
  File "/home/osboxes/.pyenv/versions/2.7.14/envs/geonode/lib/python2.7/site-packages/paver/tasks.py", line 192, in do_task
    task()
  File "/home/osboxes/.pyenv/versions/2.7.14/envs/geonode/lib/python2.7/site-packages/paver/tasks.py", line 321, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "/home/osboxes/.pyenv/versions/2.7.14/envs/geonode/lib/python2.7/site-packages/paver/tasks.py", line 214, in _run_task
    return do_task()
  File "/home/osboxes/.pyenv/versions/2.7.14/envs/geonode/lib/python2.7/site-packages/paver/tasks.py", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 127, in setup_geoserver
    _install_data_dir()
  File "pavement.py", line 199, in _install_data_dir
    justcopy(original_data_dir, target_data_dir)
  File "pavement.py", line 1058, in justcopy
    _copytree(origin, target)
  File "pavement.py", line 1052, in _copytree
    shutil.copy2(s, d)
  File "/home/osboxes/.pyenv/versions/2.7.14/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/home/osboxes/.pyenv/versions/2.7.14/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: path('geoserver/data/README.rst')

I would suggest to relax _copytree

**Comment by afabiani** [comment]
PR contains fixes for the Issues below:

- [x] closes #3564 [User Story] Improve security workflow for Group-protected resources
- [x] closes #3565 Topic Category is no more visible on the Layer summary list
- [x] closes #3566 If a Resource belongs to a Group, it should be also visible on the summary list
- [x] closes #3569 Add support for KML and KMZ with GroundOverlay
- [x] closes #3573 Invitation for unregistered users
- [x] closes #3574 Monitoring ServiceHandlers hangs when "service.last_check" is null

**Comment by francbartoli** [comment]
@afabiani tested again right now with time data from gisdata package. I don't know if this below is expected but when I create a map from a layer the zoom level selected in the editor is not the same defined in the created map which is the highest possible.
I'd rather presume this is a small bug and not the desired behavior.

See image
screenshot_1441

**Comment by afabiani** [comment]
@francbartoli currently I didn't noticed that, need to try to reproduce it. Most probably a GeoExplorer issue.

Can we open a separate issue for that?

**Comment by afabiani** [comment]
@francbartoli just did a test, it looks happening the first time I save the map only or when no overlay is added. That confirms that it is a GeoExplorer bug.

**Pull request merged**
