### PR TITLE
[Fixes #5821] Backup/restore procedure update

### LINKED ISSUE #5821: Backup/restore procedure update
## Expected Behavior
- backup / restore procedure to work correctly

## Actual Behavior
- Layer fixtures are loaded before UploadSession fixtures, causing an error
- Django signals are not disabled on b/r commands execution, causing e.g. doubled entries in Attributes table for a single layer

## Steps to Reproduce the Problem

  1. Configure Geonode-Geoserver to user PostGIS datastore
  2. Upload a layer
  3. Run `python manage.py backup` command
  4. Run `python manage.py restore` command

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Linux mint
  - Additional details: -

### PR DESCRIPTION
**Pull request by bieganowski**
Geonode and Geoserver backup/restore procedure update:
- change an order of models declaration in geonode/layers/models.py to ensure proper fixture loading order
- fix for disabling Django signals on Geonode's backup and restore

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
Nice thanks @bieganowski can you please sign the CLA? For further guidance on signing see: https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md

**Comment by giohappy** [comment]
@t-book I will add Michal to the CLA since he's working for us (GeoSolutions)

**Comment by afabiani** [comment]
@bieganowski thanks, we need:

1. To create an issue on GeoNode describing what you are trying to achieve
2. Rename this PR as [Fixes #<issue>] title of the issue
3. Possibly, adding a test case
4. Mandatory, update the documentation if something changed on procedures

**Comment by t-book** [comment]
@giohappy Perfect! Thanks!

**Pull request merged**
