### PR TITLE
[Fixes #4916] – show featured items on startpage

### LINKED ISSUE #4916: Featured items don't show up in home page
## Expected Behavior

The featured items should show up in the home page featured datasets section.

## Actual Behavior

They currently don't show up. But I see that the request to the API is successful.
Looks to be an angular thing.

## Steps to Reproduce the Problem

Check "featured" on any layer/map/document, go to the home page: there isn't the featured item in the list.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

### PR DESCRIPTION
**Pull request by t-book**
Fixes https://github.com/GeoNode/geonode/issues/4916
Angular problem not showing featured items

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by capooti** [comment]
@t-book great! +1 to merge once CI builds correctly

**Comment by t-book** [comment]
thanks @capooti would you kindly accept with a review? Otherwise, I cannot merge.

**Comment by capooti** [comment]
@t-book for some reasons yesterday when I looked at this there wasn't a way to add a review for me.
Maybe because the build was still running? Not sure why that happened

**Comment by t-book** [comment]
No worries. Github GUI is sometimes a mystery ;)

**Comment by capooti** [comment]
and already did that many times :)

**Pull request merged**
