### PR TITLE
[Fixes #7236] Issues with layer style legends displayed when more tha…

### LINKED ISSUE #7236: Issues with layer style legends displayed when more than one style is selected
## Expected Behavior
When adding more than one style to a layer, I can see the legend of the current selected style.

## Actual Behavior
I see multiple legends. Moreover the title of the CSS ones report a long UUID as stated  form this issue [here](https://github.com/GeoNode/geonode/issues/7102#issuecomment-803847539)

## Steps to Reproduce the Problem

  1. Edit a Layer
  2. Add more than one style either from the map editor or "style manage" utility
  3. Go back to the layer detail page

grafik

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by afabiani**
…n one style is selected

Refers: ISSUE #7236

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by marthamareal** [comment]
@afabiani  This fixes the UI after you perform an update and the `sld_title` is added. I suggest that to fix existing displays before an update is done, we also update [this block](https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_detail.html#L592) in the template.

**Comment by giohappy** [comment]
@afabiani I agree with @marthamareal, we should also apply a fix to the template conditional check.

**Comment by afabiani** [comment]
The legend should change dynamically when selecting a new style from the list of the available ones, this is the scope of the loop (if I remember correctly). 
image

It is worth to take a look anyway. Also I agree about the wrong `None` check; that should be avoided.

**Comment by giohappy** [comment]
yes, the loop is required of course, but the problem is with the equality check in case sld_title is None. It happens for styles saved before the fixes.

**Pull request merged**
