### PR TITLE
Initial work on describing GeoGig OSM functionality

### PR DESCRIPTION
**Pull request by jj0hns0n**
@state-hiu @garnertb can you guys take a quick review of this before merging.

Related to #1931

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@groldan @volaya see the notes about the fid/pk problems we encountered when doing pg export with osm data ... and the workarounds. This is related to https://github.com/boundlessgeo/GeoGig/issues/356 Lets see if we can discuss and potentially get a fix for these?

https://github.com/GeoNode/geonode/pull/2066/files#diff-6a45552812f16e9cdbe602ca48df6167R222

**Comment by jj0hns0n** [comment]
@garnertb maybe you can also help with the final section on using the geoserver extension. I have no idea how to configure this without just using a complete war.

**Comment by jj0hns0n** [comment]
How the hell does a PR that only adds to an existing doc fail?

**Comment by simod** [comment]
@jj0hns0n  master was failing today due to an update in flake8, maybe you just have to re trigger the build.

**Comment by jj0hns0n** [comment]
We can just merge this I bet, I just sent a PR vs pushing directly to make
sure that @garnertb and @state-hiu actually looked at it :)

**Comment by capooti** [comment]
thanks for the very informative doc, @jj0hns0n

**Pull request merged**
