### PR TITLE
[Closes #4249] Contribute back upstream menu management from IGAD

### LINKED ISSUE #4249: Contribute back upstream menu management from IGAD
Generalize and simplify the menu management system implemented for IGAD.
The generic implementation to be ported upstream should provide a model to define menus and a generic "placeholder" concept to be integrated inside custom tempaltes through template tags.

### Models
- **menu_placeholder**: represents a logical container for menus. A template tag will provide the list of menus linked to this placeholder to be rendered in a specific area of the template HTML.
   - id
   - name

- **menu**: the links container. With bootstrap it could be rendered as a dropdown title
  - id
  - title
  - placeholder_id: FK to menu_placeholder
  - order: menus within the same placeholder will be rendered according to this (optional) value. It represents a relative weight

image

- **menu_item**:
  - id
  - title
  - menu_id: FK to menu 
  - order
  - blank_target: boolean flag to specify if the link should open a new page
  - url: free input. Internal pages will be define with relative urls, external pages with absolute url. 

image

### Template tags
A set of template tags should be implemented to provide the template developer the option to obtain:

 - list of menu objects for a certain placeholder
 - list of menu_item objects for a certain menu

image

We would also provide a "rendered" option to obtain a complete placehoder and / or single menu rendered according to a default template, i.e. Bootstrap themed as the other menus in vanilla GeoNode.

image

### PR DESCRIPTION
**Pull request by afabiani**
In this PR the menu management system implemented for IGAD has been generalized and simplified.

Issue: #4249

Three new models have been added in the geonode 'base' app model python module:
* MenuPlaceholder - a logical container for menus
* Menu - the link container
* Menu item - internal or external links shown in each menu

Two custom template tags have been implemented for the menus rendering in the templates.

The **get_menu** assignment tag takes the placeholder name as argument and return, as output, a dictionary like this:
`{ <Menu: menu_0>: <QuerySet [<MenuItem: menu_item_0>, <MenuItem: menu_item_1>, ... ]>, ... }`
It can be used everywhere (for example to perfom a dropdown menu or an accordion panel) following these steps:
1 - load the custom tag `{% load base_tags %}`
2 - call the tag `{% get_menu '<placeholder_name>' %}`

The **render_nav_menu** inclusion tag does the same job but with a predefined html rendering (geonode/base/templates/menu.html). It is prepared for being a navbar dropdown menu without any further front-end implementation needed.
It should be called inside the **extra_tab** block of the 'base.html' template:
`{% block extra_tab %}`
    `{% render_nav_menu '<placeholder_name>' %}`
`{% endblock extra_tab %}`

No rendering options have been implemented yet.
No bdd test implemented.

Unittest in geonode/base/tests.py.

### CODE REVIEW

**Comment by afabiani** [comment]
Smoke tests are temporarily broken, they will be fixed once we merge this one
https://github.com/GeoNode/geonode/pull/4240

**Comment by capooti** [comment]
it is interesting, though I'd prefer to see this as a contribute module

**Comment by francbartoli** [comment]
I guess this would affect the template for additional nav menus on geonode-project also. I'm inclined to  agree with Paolo for a contrib app

**Comment by afabiani** [comment]
@capooti @francbartoli by default it does not affect the templates, in fact in order to add a new menu item you would need to both:

1. Create a placeholder key on admin
2. Add the placeholder on the template

This PR proposes, along with documentation explaining how to add more, at leas one placeholder already created on base.html called 'TOPBAR_MENU', just to avoid that standard users not haveing carefully read the documentation, will try to add menus from admin without seeing the outcomes.

Nevertheless, we can remove the default placeholder from base.html and fixtures.

That said, if you still prefer moving this to a contrib module, no problems.

Can you please cast your votes?

**Comment by francbartoli** [comment]
@afabiani In such case +0 for me. It can also stay in the code base

**Pull request merged**
