### PR TITLE
 [Fixes #5288] Django SPC build error

### LINKED ISSUE #5288: Django SPC build error
## Expected Behavior
```
docker-compose build
``` 
run fine 

## Actual Behavior
```
Collecting more-itertools
  Downloading https://files.pythonhosted.org/packages/c2/31/45f61c8927c9550109f1c4b99ba3ca66d328d889a9c9853a808bff1c9fa0/more-itertools-7.2.0.tar.gz (73kB)
ERROR: Package 'more-itertools' requires a different Python: 2.7.16 not in '>=3.4'
ERROR: Service 'celerycam' failed to build: The command '/bin/sh -c pip install celery==4.1.0 # see https://github.com/GeoNode/geonode/pull/3714' returned a non-zero code: 1
```
more-itertools 7.2.0 requires python 3

## Steps to Reproduce the Problem

  1. git clone 2.10.x repository
  2. cd geonode/scripts/spcgeonode
  3. docker-compose build

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode
  - Platform: Ubuntu 18.04 and Archlinux
  - Additional details:

### PR DESCRIPTION
**Pull request by kikislater**
<Include a few sentences describing the overall goals for this Pull Request>
 [Fixes GeoNode#5288] Django SPC build error

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
Dear @kikislater  there are some issues with this PR

- In case you plan further contribution please sign the CLA. Find more about it here: https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md When finished just drop me a line and I will add you where needed.
- Please have a look at the checklist. Issues should have labels and milestones, I've just added those to your issue
- Also checklist: not all of them have to be checked. For example, have a look where it says "Unit tests" having a look at your commit there are no newly added unit tests
- Please correct the title of you PR and remove geonode. It should just read `[Fixes #5288] Django SPC build error`

Thanks!

**Comment by kikislater** [comment]
Ok sorry, I have signed CLA and sent to info at osgeo.org 
Ok labels and milestone have to be in issue ?

**Comment by t-book** [comment]
no worries @kikislater ;)
yes the issue must have label and milestone

**Comment by kikislater** [comment]
I'll close this PR. I just rebuild and everything ok
Sorry for that !

**Comment by t-book** [comment]
ok thanks for reporting. You're now added to contributors and cla-bot should accept your PR's.

**Pull request closed without merging**
