### PR TITLE
[Fixes #7051] GeoServer will create three styles instead of one

### LINKED ISSUE #7051: GeoServer will create three styles instead of one
## Expected Behavior
If I upload a layer a default style will be created by GeoServer for it.

## Actual Behavior
GeoServer will create three styles as shown here:
grafik

## Steps to Reproduce the Problem

  1. deploy GeoNode with async mode on
  2. upload a layer
  3. take a look at the available layers in GeoServer, or by managing existing layers styles.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by afabiani**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by gannebamm** [comment]
This was blazingly fast @afabiani . I can test it this evening.

**Comment by t-book** [comment]
This is how I've just tested it.

up a fresh GeoNode Project 3.2.x
Log into django container
```
cd /usr/src/geonode
git fetch origin
git checkout -b ISSUE_7051 origin/ISSUE_7051
find . -name '*.pyc' -delete
git log #double check commit
```
restarted the container.
Uploaded tiger roads and checked styles:

Bildschirmfoto von 2021-03-10 15-51-33

Again three. However. Today is not my best day. There is a fair chance for example my container restart is not enough. 
Unfortunately, I do not have a paver setup by the hand. So @gannebamm it would be great if you can double-check as well

**Comment by afabiani** [comment]
@t-book this won't be sufficient, you will need to update and restart the celery container too.

I'm building this branch on https://master.demo.geonode.org/ it will be ready for testing in a few.

**Comment by afabiani** [comment]
@t-book @gannebamm master ready for testing. Just did a quick test:

image

image

**Comment by t-book** [comment]
Yes celery of course. Not my day. Thanks @afabiani

**Review by gannebamm — APPROVED** [review]
Did not check the commit line by line, but tested it successful locally.

**Review by t-book — APPROVED** [review]

**Pull request merged**
