### PR TITLE
[Issue #6843] Remove redundant enumerate calls

### LINKED ISSUE #6807: Remove redundant enumerate calls
_Reserved for Catalyst Academy 2021_

### Description

There are some instances where enumerate is used redundantly, that is the digit count is not being used. We can remove instances such as
```
fruits = ["apple", "orange", "pear"]
copy_of_fruits = [fruit for num, fruit in enumerate(fruits)]
```

### Tasks

- [ ] Identify instances of enumerate that are redundant
- [ ] Remove the enumerate call and the digit unpacking from the redundant instance

### PR DESCRIPTION
**Pull request by rukarangi**
Removed redundant enumerate calls.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — DISMISSED** [review]

**Comment by afabiani** [comment]
@mtnorthcott can we collect all those useful improvements PRs in an epic?

**Comment by mtnorthcott** [comment]
> @mtnorthcott can we collect all those useful improvements PRs in an epic?

I have created https://github.com/GeoNode/geonode/issues/6843 if you could add the label  for me.

**Comment by afabiani** [comment]
@mtnorthcott I invited you to the GeoNode Team group. You will be promoted as mantainer, so you will be able to manage the issues by yourself. I also converted #6843 into an Epic. That way you should be able to add other issues as dependencies of this one. Let me know if I can provide some further help.

**Review by mtnorthcott — APPROVED** [review]

**Comment by t-book** [comment]
@mtnorthcott already approved. I do agree as well. Looks good. As it's the base and layers model let's wait (once again) how tests run.

**Review by t-book — APPROVED** [review]

**Pull request merged**
