### PR TITLE
[DRAFT] Remove AngularJS from Geonode Search.

### PR DESCRIPTION
**Pull request by trepagnier**
This PR is connected to https://github.com/GeoNode/geonode/issues/4129. It is an early draft that will complete the items listed below. The list will grow in number and detail as work on this PR progresses:

- [x] Integrate Webpack into the Geonode static directory.
- [x] Configure Webpack to transpile ES6 to ES5 for browser support.
- [ ] Remove all references to AngularJS inside the Geonode search codebase and replace with  a mixture of React, jQuery, and vanilla ES6.
- [ ] Introduce a central search controller that consists of minimal declarative code. All imperative code will be abstracted away to helper functions inside of a `functions` directory.
- [ ] Split search code into smaller, more maintainable modules.
- [ ] Componentize key search features.
- [x] Fix the extent bug in the Leaflet sidebar map that causes bounds to grow infinitely as one scrolls.
- [x] Introduce a `Search` factory function. An instance of `Search` will be used to store all data related to searching the Geonode catalogue. This instance should be regarded as the single source of truth for all search related data. Any stateful components or modules should receive their state from the Search instance. 
- [x] Implement a pubsub paradigm for the search codebase. Communication between components should be handled via publications and subscriptions in order to ensure loose coupling between components. 
- [x] Provide an Angular shim that syncs data between Angular's `$scope` and a given `Search` instance, which will be used until Angular is entirely removed from the project.

### CODE REVIEW

**Comment by francbartoli** [comment]
@darinacosta @Coop56 I believe a connected issue with this is required as per our latest rules from PSC. Also minimal e2e tests for the UI features touched by this would be actually useful

**Comment by Coop56** [comment]
@francbartoli The issue connected with this PR is https://github.com/GeoNode/geonode/issues/4129 - do we just need to add that to the description of the PR?

**Comment by francbartoli** [comment]
Yes please, reference it somewhere

**Comment by francbartoli** [comment]
Another comment is about jquery. Do we need to still maintain it? Can we replace with something like [Axios](https://github.com/axios/axios) for ajax calls?

**Comment by darinacosta** [comment]
@francbartoli Regarding the use of jQuery: there are a couple of components rely on it, such as [TextSearchForm](https://github.com/MapStory/geonode/blob/react-migration/geonode/static/geonode/js/search/components/TextSearchForm.js) and [SelectionTree](https://github.com/MapStory/geonode/blob/react-migration/geonode/static/geonode/js/search/components/SelectionTree.js). Perhaps we can address  its removal in a future phase of refactoring?

**Comment by francbartoli** [comment]
> @francbartoli Regarding the use of jQuery: there are a couple of components rely on it, such as [TextSearchForm](https://github.com/MapStory/geonode/blob/react-migration/geonode/static/geonode/js/search/components/TextSearchForm.js) and [SelectionTree](https://github.com/MapStory/geonode/blob/react-migration/geonode/static/geonode/js/search/components/SelectionTree.js). Perhaps we can address its removal in a future phase of refactoring?

Main concern was about still using if for ajax call even though getting rid of jquery would be better. Thanks for addressing bdd tests

**Comment by afabiani** [comment]
@trepagnier closing this since it is stale for a long time and has conflicts.
Please re-send if you want by following the correct path:
 * Create an issue describing what you want to achieve
 * Make sure the PR respects all the requirements

Thanks,
@afabiani

**Pull request closed without merging**
