### PR TITLE
[Fixes #6916] gsimporter.api.NotFound caused by missing trailing slash at the end of GEOSERVER_LOCATION

### LINKED ISSUE #6916: gsimporter.api.NotFound caused by missing trailing slash at the end of GEOSERVER_LOCATION
## Expected Behavior
If GEOSERVER_LOCATION does not end with trailing slash it should handled by code so the functionality of Geonode won't break.

## Actual Behavior
Uploading a layer will raise error `gsimporter.api.NotFound` due to GEOSERVER_LOCATION not ending with trailing slash

## Steps to Reproduce the Problem

  1. change GEOSERVER_LOCATION to make it not end with trailing slash `http://nginx:80/geoserver`
  2. go to upload layer
  3. upload any shapefiles 

## Specifications

  - GeoNode version: 3.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Linux

### PR DESCRIPTION
**Pull request by malnajdi**
GEOSERVER_LOCATION requires to end with trailing slash other wise it will raise an error which can't be explained.
```
gsimporter.api.NotFound
ERROR 2021-02-01 15:54:28,314 upload 1 139829203416832 Error creating import session
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/geonode/upload/upload.py", line 305, in save_step
    next_id = _get_next_id()
  File "/usr/local/lib/python3.8/site-packages/geonode/upload/upload.py", line 228, in _get_next_id
    importer_sessions = gs_uploader.get_sessions()
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 47, in get_sessions
    return self._call(self.client.get_imports)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 34, in _call
    robj = fun(*args)
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 221, in get_imports
    return parse_response(self._request(self.url("imports")))
  File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 194, in _request
    raise NotFound()

```
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@malnajdi thanks for your contribution. Few things missing here though:

1. Did you sent the CLA to Osgeo?
2. You need to create an ISSUE first and title the PR accordingly
3. Probably we need to update the documentation too here
4. A small test case would be nice

**Comment by malnajdi** [comment]
> @malnajdi thanks for your contribution. Few things missing here though:
> 
>     1. Did you sent the CLA to Osgeo?
        - yes
>     2. You need to create an ISSUE first and title the PR accordingly
       - done
>     3. Probably we need to update the documentation too here
       - i don't think so. reason that it's not mentioned in the current docs that it's required for GEOSERVER_LOCATION to end with trailing slash. there for i would leave it be. https://docs.geonode.org/en/master/basic/settings/index.html?highlight=geoserver_location#geoserver-location
>     4. A small test case would be nice
       - What kind of test ? and where you would like me to add it ?

**Comment by t-book** [comment]
@cla-bot check

**Comment by t-book** [comment]
> What kind of test ? and where you would like me to add it ?

Unsure, maybe a smoke test or geoserver.test. Where would you see it @afabiani

**Comment by afabiani** [comment]
A very simple smoke test getting the value of `settings.GEOSERVER_LOCATION` and ensuring it ends with `/` would be sufficient.

Just to be sure no one will introduce a regression in the future.

**Comment by malnajdi** [comment]
> A very simple smoke test getting the value of `settings.GEOSERVER_LOCATION` and ensuring it ends with `/` would be sufficient.
> 
> Just to be sure no one will introduce a regression in the future.

Okay, thanks. Shall this be under tests/smoke.py (GeoNodeSmokeTests) ?

**Comment by t-book** [comment]
Yep

**Comment by malnajdi** [comment]
done

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
Thanks @malnajdi

**Pull request merged**
