### PR TITLE
[Fixes #9101] Keywords filter only returns the root nodes of the tree

### LINKED ISSUE #9101: Keywords filter only returns the root nodes of the tree
Apparently, the only root keywords, from the hierarchical tree, are returned inside the keywords filter, with the following result:

 - if resources have children keywords assigned only their root keywords are returned inside the filter, even if these root keywords are not explicitly assigned to any resource
 - the number returned inside the keyword filter only counts the resources directly assigned to the keyword, and not its children keywords

Let's make an example

Keywords tree:
 - "a"
   - "aa"  <- dataset_1
     - "aaa"   <- dataset_1
 - "b" <- dataset_2

Filter (current behaviour):
- "a" (0) 
- "b" (1)

You see that "a" is returned, since it's a parent of keywords with associated resources, and its number is 0 because it deosn't have resources directly associated

The expected results is:
Filter:
- "aa" (1)
- "aaa" (1)
- "b" (1)

i.e. the flattened keywords, with only the keywords with a direct association with one or more resources.

### PR DESCRIPTION
**Pull request by afabiani**
References: #9101

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by marthamareal — COMMENTED** [review]
@afabiani, This looks good, maybe we could add some unit tests for this on API  `api/v2/keywords`

**Review by giohappy — APPROVED** [review]

**Review by marthamareal — APPROVED** [review]

**Review by mattiagiupponi — COMMENTED** [review]
I think would be valuable to have a test to cover this kind of scenario, a parent with a child that have a child.
image

**Comment by giohappy** [comment]
>I think would be valuable to have a test to cover this kind of scenario, a parent with a child that have a child.

@mattiagiupponi recursive cases should be accounted by the tests, without having to so specific tests. Otherwise we also need a test for further levels.

If we're not covering the recursive case tests must be improved.

**Comment by afabiani** [comment]
> > I think would be valuable to have a test to cover this kind of scenario, a parent with a child that have a child.
> 
> @mattiagiupponi recursive cases should be accounted by the tests, without having to so specific tests. Otherwise we also need a test for further levels.
> 
> If we're not covering the recursive case tests must be improved.

Not sure I understood... when you invoke the rest endpoint the outcome is generated by triggering the recursive function... I can add other levels, but I really don't think this would change something

**Review by giohappy — APPROVED** [review]

**Pull request merged**
