### PR TITLE
Adding non obvious steps to get a windows dev environment up and running (Eg novelt readme patch 1)

### PR DESCRIPTION
**Pull request by eg-novelt**
Hello,

I just ran through the steps to get a dev environment up and running on windows.  These minor changes just make it clear what needs to be done to get the current master branch to a state where you can run paver start.

Some of this info is elsewhere in the docs, but it is always nice to have the getting started steps clear directly in the main readme file.

Feedback always welcome.  I'm not sure if this could all theoretically work in 64 bit python...

Thanks,
Eric

### CODE REVIEW

**Comment by pjdufour** [comment]
Could you squash your commits please?  Otherwise, I'm happy to just close when ready and just manually add commit.

**Comment by tomkralidis** [comment]
Note as an option we can squash right here in GitHub as part of the Merge pull request button.

**Comment by eg-novelt** [comment]
Hello, 

I googled a bit and saw this page: https://help.github.com/articles/about-pull-request-merge-squashing/

It looks like it is is done by the person merging the pull request, as tomkralidis mentioned.  

If that's wrong or not possible, could you let me know how to go about the "squashing" (ie do I use git merge or some form of git rebase?)

Thanks !

Eric

**Comment by jj0hns0n** [comment]
@eg-novelt we can squash during merge, so dont worry about it. Can you update your branch with master though.

**Comment by jj0hns0n** [comment]
@eg-novelt can you sign the CLA online so we can merge

**Comment by eg-novelt** [comment]
CLA signed

**Pull request merged**
