### PR TITLE
[Fixes #4322] SESSION_EXPIRED_CONTROL_ENABLE=True breaks GeoNode

### LINKED ISSUE #4322: SESSION_EXPIRED_CONTROL_ENABLE=True breaks SPC GeoNode
Here's what happens when setting `SESSION_EXPIRED_CONTROL_ENABLE=True` (default value in GeoNode, but set to `False` in SPCGeonode):

```
$,
,
,
,
-----------------------------------------------------,
STARTING DJANGO ENTRYPOINT Thu Mar 28 14:18:47 UTC 2019,
-----------------------------------------------------,
Running initialize.py...,
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.,
  """),
JSONField implementation is: <class 'jsonfield.fields.JSONField'>,
-----------------------------------------------------,
1. Waiting for PostgreSQL,
-----------------------------------------------------,
2. Running the migrations,
Operations to perform:,
  Apply all migrations: account, actstream, admin, agon_ratings, announcements, auth, avatar, base, contenttypes, dialogos, documents, geonode_client, geonode_themes, groups, guardian, invitations, layers, maps, oauth2_provider, people, pinax_notifications, services, sessions, sites, socialaccount, taggit, tastypie, upload, user_messages,
Running migrations:,
  No migrations to apply.,
  Your models have changes that are not yet reflected in a migration, and so won't be applied.,
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.,
-----------------------------------------------------,
3. Creating/updating superuser,
superuser successfully updated,
-----------------------------------------------------,
4. Create/update an OAuth2 provider to use authorisations keys,
oauth2 provider successfully updated,
-----------------------------------------------------,
5. Loading fixtures,
Installed 301 object(s) from 1 fixture(s),
-----------------------------------------------------,
6. Running updatemaplayerip,
-----------------------------------------------------,
 Collecting static files,
-----------------------------------------------------,
8. Waiting for GeoServer,
-----------------------------------------------------,
9. Securing GeoServer,
Master password was already changed. No changes made.,
-----------------------------------------------------,
FINISHED DJANGO ENTRYPOINT --------------------------,
-----------------------------------------------------,
*** Starting uWSGI 2.0.18 (64bit) on [Thu Mar 28 14:19:09 2019] ***,
compiled with version: 6.3.0 20170516 on 26 March 2019 12:04:41,
os: Linux-4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019,
nodename: 5175656e9bb7,
machine: x86_64,
clock source: unix,
pcre jit disabled,
detected number of CPU cores: 2,
current working directory: /spcgeonode,
detected binary path: /usr/local/bin/uwsgi,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
chdir() to /spcgeonode,
*** WARNING: you are running uWSGI without its master process manager ***,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
lock engine: pthread robust mutexes,
thunder lock: disabled (you can enable it with --thunder-lock),
uWSGI http bound on 127.0.0.1:8001 fd 3,
spawned uWSGI http 1 (pid: 16),
uwsgi socket 0 bound to TCP address :8000 fd 6,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
Python version: 2.7.14 (default, May  1 2018, 23:38:34)  [GCC 6.3.0 20170516],
*** Python threads support is disabled. You can enable it with --enable-threads ***,
Python main interpreter initialized at 0x556d753d82e0,
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
your server socket listen backlog is limited to 100 connections,
your mercy for graceful operations on workers is 60 seconds,
mapped 364520 bytes (355 KB) for 5 cores,
*** Operational MODE: preforking ***,
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.,
  """),
JSONField implementation is: <class 'jsonfield.fields.JSONField'>,
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x556d753d82e0 pid: 1 (default app),
uWSGI running as root, you can use --uid/--gid/--chroot options,
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** ,
*** uWSGI is running in multiple interpreter mode ***,
spawned uWSGI worker 1 (pid: 1, cores: 1),
spawned uWSGI worker 2 (pid: 26, cores: 1),
spawned uWSGI worker 3 (pid: 27, cores: 1),
spawned uWSGI worker 4 (pid: 28, cores: 1),
spawned uWSGI worker 5 (pid: 29, cores: 1),
[pid: 1|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 294 bytes} [Thu Mar 28 15:19:47 2019] GET / => generated 31220 bytes in 472 msecs (HTTP/1.1 200) 8 headers in 401 bytes (1 switches on core 0),
[pid: 28|app: 0|req: 1/2] 10.255.0.2 () {50 vars in 883 bytes} [Thu Mar 28 15:19:49 2019] GET / => generated 31220 bytes in 574 msecs (HTTP/1.0 200) 10 headers in 544 bytes (1 switches on core 0),
[pid: 29|app: 0|req: 1/3] 10.255.0.2 () {50 vars in 787 bytes} [Thu Mar 28 15:19:50 2019] GET /jsi18n/ => generated 11591 bytes in 26 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 1/4] 10.255.0.2 () {50 vars in 787 bytes} [Thu Mar 28 15:19:49 2019] GET /lang.js => generated 13361 bytes in 281 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 2/5] 10.255.0.2 () {48 vars in 826 bytes} [Thu Mar 28 15:19:50 2019] GET /favicon.ico => generated 20346 bytes in 97 msecs (HTTP/1.0 404) 9 headers in 468 bytes (1 switches on core 0),
[pid: 26|app: 0|req: 1/6] 10.255.0.2 () {50 vars in 829 bytes} [Thu Mar 28 15:19:50 2019] GET /api/featured/ => generated 132 bytes in 247 msecs (HTTP/1.0 200) 9 headers in 330 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 3/7] 10.255.0.2 () {56 vars in 1037 bytes} [Thu Mar 28 15:20:05 2019] POST /account/login/?next=/ => generated 22525 bytes in 91 msecs (HTTP/1.0 200) 9 headers in 461 bytes (1 switches on core 0),
[pid: 26|app: 0|req: 2/8] 10.255.0.2 () {50 vars in 808 bytes} [Thu Mar 28 15:20:06 2019] GET /jsi18n/ => generated 11591 bytes in 7 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
[pid: 29|app: 0|req: 2/9] 10.255.0.2 () {50 vars in 808 bytes} [Thu Mar 28 15:20:06 2019] GET /lang.js => generated 13361 bytes in 240 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
[pid: 28|app: 0|req: 2/10] 10.255.0.2 () {56 vars in 1045 bytes} [Thu Mar 28 15:20:14 2019] POST /account/login/ => generated 0 bytes in 44 msecs (HTTP/1.0 302) 11 headers in 548 bytes (1 switches on core 0),
[pid: 1|app: 0|req: 2/11] 10.255.0.2 () {52 vars in 944 bytes} [Thu Mar 28 15:20:14 2019] GET / => generated 32571 bytes in 306 msecs (HTTP/1.0 200) 10 headers in 536 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 4/12] 10.255.0.2 () {50 vars in 831 bytes} [Thu Mar 28 15:20:15 2019] GET /jsi18n/ => generated 11591 bytes in 8 msecs (HTTP/1.0 200) 9 headers in 373 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 5/13] 10.255.0.2 () {48 vars in 826 bytes} [Thu Mar 28 15:20:16 2019] GET /favicon.ico => generated 20346 bytes in 46 msecs (HTTP/1.0 404) 9 headers in 468 bytes (1 switches on core 0),
[pid: 29|app: 0|req: 3/14] 10.255.0.2 () {50 vars in 831 bytes} [Thu Mar 28 15:20:15 2019] GET /lang.js => generated 13361 bytes in 11009 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
[pid: 1|app: 0|req: 3/15] 10.255.0.2 () {52 vars in 910 bytes} [Thu Mar 28 15:20:26 2019] GET /layers/?limit=20 => generated 60264 bytes in 147 msecs (HTTP/1.0 200) 9 headers in 461 bytes (1 switches on core 0),
[pid: 29|app: 0|req: 4/16] 10.255.0.2 () {50 vars in 803 bytes} [Thu Mar 28 15:20:26 2019] GET /jsi18n/ => generated 11591 bytes in 5 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 6/17] 10.255.0.2 () {50 vars in 829 bytes} [Thu Mar 28 15:20:26 2019] GET /api/featured/ => generated 132 bytes in 270 msecs (HTTP/1.0 200) 9 headers in 330 bytes (1 switches on core 0),
[pid: 26|app: 0|req: 3/18] 10.255.0.2 () {50 vars in 868 bytes} [Thu Mar 28 15:20:26 2019] GET /h_keywords_api?type=layer => generated 2 bytes in 3 msecs (HTTP/1.0 200) 8 headers in 303 bytes (1 switches on core 0),
[pid: 29|app: 0|req: 5/19] 10.255.0.2 () {50 vars in 803 bytes} [Thu Mar 28 15:20:26 2019] GET /lang.js => generated 13361 bytes in 321 msecs (HTTP/1.0 200) 8 headers in 298 bytes (1 switches on core 0),
Internal Server Error: /api/categories/,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 221, in wrapper,
    response = callback(request, *args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 461, in dispatch_list,
    return self.dispatch('list', request, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 493, in dispatch,
    response = method(request, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1357, in get_list,
    for obj in to_be_serialized[self._meta.collection_name],
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__,
    self._fetch_all(),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all,
    self._result_cache = list(self._iterable_class(self)),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__,
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql,
    raise original_exception,
OperationalError: lost synchronization with server: got message type "e", length 1933189234,
,
Internal Server Error: /api/categories/,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner,
    response = get_response(request),
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response,
    response = self._get_response(request),
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response,
    response = self.process_exception_by_middleware(e, request),
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response,
    response = wrapped_callback(request, *callback_args, **callback_kwargs),
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view,
    return view_func(*args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 270, in wrapper,
    return self._handle_500(request, e),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 320, in _handle_500,
    return self.error_response(request, data, response_class=response_class),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1292, in error_response,
    serialized = self.serialize(request, errors, desired_format),
  File "./geonode/api/api.py", line 271, in serialize,
    return super(TopicCategoryResource, self).serialize(request, data, format, options),
  File "./geonode/api/api.py", line 146, in serialize,
    return super(TypeFilteredResource, self).serialize(request, data, format, options),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 399, in serialize,
    return self._meta.serializer.serialize(data, format, options),
  File "/usr/local/lib/python2.7/site-packages/tastypie/serializers.py", line 265, in serialize,
    return method(bundle, options),
  File "./geonode/api/api.py", line 105, in to_json,
    counts = self.get_resources_counts(options),
  File "./geonode/api/api.py", line 81, in get_resources_counts,
    'base.view_resourcebase',
  File "/usr/local/lib/python2.7/site-packages/guardian/shortcuts.py", line 471, in get_objects_for_user,
    permission__codename=codename),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method,
    return getattr(self.get_queryset(), name)(*args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get,
    num = len(clone),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__,
    self._fetch_all(),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all,
    self._result_cache = list(self._iterable_class(self)),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__,
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 887, in execute_sql,
    cursor = self.connection.cursor(),
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor,
    return self._cursor(),
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor,
    return self._prepare_cursor(self.create_cursor(name)),
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__,
    six.reraise(dj_exc_type, dj_exc_value, traceback),
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 231, in _cursor,
    return self._prepare_cursor(self.create_cursor(name)),
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 220, in create_cursor,
    cursor = self.connection.cursor(),
InterfaceError: connection already closed,
Internal Server Error: /api/regions/,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 221, in wrapper,
    response = callback(request, *args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 461, in dispatch_list,
    return self.dispatch('list', request, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 493, in dispatch,
    response = method(request, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1352, in get_list,
    to_be_serialized = paginator.page(),
  File "/usr/local/lib/python2.7/site-packages/tastypie/paginator.py", line 194, in page,
    count = self.get_count(),
  File "/usr/local/lib/python2.7/site-packages/tastypie/paginator.py", line 126, in get_count,
    return self.objects.count(),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 364, in count,
    return self.query.get_count(using=self.db),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 499, in get_count,
    number = obj.get_aggregation(using, ['__count'])['__count'],
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 480, in get_aggregation,
    result = compiler.execute_sql(SINGLE),
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql,
    raise original_exception,
OperationalError: insufficient data in "D" message,
lost synchronization with server: got message type "", length -65536,
,
[pid: 29|app: 0|req: 6/20] 10.255.0.2 () {50 vars in 864 bytes} [Thu Mar 28 15:20:26 2019] GET /api/regions/?type=layer => generated 88 bytes in 29 msecs (HTTP/1.0 500) 8 headers in 315 bytes (1 switches on core 0),
Internal Server Error: /api/thesaurus/keywords/,
Traceback (most recent call last):,
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 221, in wrapper,
    response = callback(request, *args, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 461, in dispatch_list,
    return self.dispatch('list', request, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 493, in dispatch,
    response = method(request, **kwargs),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1362, in get_list,
    return self.create_response(request, to_be_serialized),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1263, in create_response,
    serialized = self.serialize(request, data, desired_format),
  File "./geonode/api/api.py", line 195, in serialize,
    return super(ThesaurusKeywordResource, self).serialize(request, data, format, options),
  File "./geonode/api/api.py", line 146, in serialize,
    return super(TypeFilteredResource, self).serialize(request, data, format, options),
  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 399, in serialize,
    return self._meta.serializer.serialize(data, format, options),
  File "/usr/local/lib/python2.7/site-packages/tastypie/serializers.py", line 265, in serialize,
    return method(bundle, options),
  File "./geonode/api/api.py", line 105, in to_json,
    counts = self.get_resources_counts(options),
  File "./geonode/api/api.py", line 81, in get_resources_counts,
    'base.view_resourcebase',
  File "/usr/local/lib/python2.7/site-packages/guardian/shortcuts.py", line 483, in get_objects_for_user,
    queryset = _get_queryset(ctype.model_class()),
  File "/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 163, in model_class,
    return apps.get_model(self.app_label, self.model),
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 198, in get_model,
    app_label, model_name = app_label.split('.'),
ValueError: need more than 1 value to unpack,
[pid: 1|app: 0|req: 4/21] 10.255.0.2 () {50 vars in 876 bytes} [Thu Mar 28 15:20:26 2019] GET /api/layers/?limit=20&offset=0 => generated 131 bytes in 34 msecs (HTTP/1.0 200) 9 headers in 330 bytes (1 switches on core 0),
[pid: 27|app: 0|req: 7/22] 10.255.0.2 () {50 vars in 870 bytes} [Thu Mar 28 15:20:26 2019] GET /api/categories/?type=layer => generated 11917 bytes in 93 msecs (HTTP/1.0 500) 8 headers in 326 bytes (1 switches on core 0),
[pid: 1|app: 0|req: 5/23] 10.255.0.2 () {50 vars in 885 bytes} [Thu Mar 28 15:20:27 2019] GET /api/layers/?limit=20&offset=0 => generated 131 bytes in 22 msecs (HTTP/1.0 200) 9 headers in 330 bytes (1 switches on core 0),
[pid: 28|app: 0|req: 3/24] 10.255.0.2 () {50 vars in 862 bytes} [Thu Mar 28 15:20:26 2019] GET /api/owners/?type=layer => generated 558 bytes in 488 msecs (HTTP/1.0 200) 9 headers in 330 bytes (1 switches on core 0),
```

@afabiani said about that (in Gitter):
> if you are logged out means that there's something wrong with your access tokens
> a hint about session control... if you are logged out it may depend on wrong/misconfigured/missing OAuth2 "GeoServer" application on Django (see fixtures)

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by afabiani** [comment]
@frafra seems like spc_geonode does not like the session middleware at all :|

**Comment by frafra** [comment]
@afabiani tests seem to work only if you wait for a while before running them, maybe because of the 60 seconds timeout you added.

A similar issue happens with the standard Docker setup, and should be avoided in my opinion, or at least we should have a simple and robust mechanism to determine if the system is ready to be used or not. I would prefer to avoid API-only solutions, as even a user should be aware if the platform is ready or not, and if you have your system running with a nice homepage the user will think that everything is fine, while it is not.

**Comment by afabiani** [comment]
@frafra agree, any suggestion? I'll start thinking about a solution too as soon as I can devote some time here again.

**Comment by afabiani** [comment]
@frafra ... which timeout? The DB one?

**Comment by afabiani** [comment]
@frafra what about a geonode endpoint `http://localhost:8000/gs/online` returning a json `{"online": false}` or `{"online": false}` whenever the LOCAL_GEOSERVER is up or not?

**Comment by t-book** [comment]
> least we should have a simple and robust mechanism to determine if the system is ready to be used or not.

> @frafra what about a geonode endpoint `http://localhost:8000/gs/online` returning a json `{"online": false}` or `{"online": false}` whenever the LOCAL_GEOSERVER is up or not?

I haven´t followed all of the discussion but why wouldn´t checking the status of the geoserver endpoint just do it?

> as even a user should be aware if the platform is ready or not,

+1 for informing users whenever gs is down.

```
fetch('/geoserver/web/').then(function(response) {
  if (response.status !== "200") {
    alert("warning geoserver is offline")
});
```

**Comment by frafra** [comment]
> @frafra ... which timeout? The DB one?

Yes, but I am not sure if that's what causes the issue.

> @frafra what about a geonode endpoint http://localhost:8000/gs/online returning a json {"online": false} or {"online": false} whenever the LOCAL_GEOSERVER is up or not?

In that scenario, how to determine if LOCAL_GEOSERVER is up? Should we check if GeoServer returns a 2xx HTTP code? We are already doing that in geonode-selenium, thanks to Docker healthchecks, but it is still failing on this pull request.

> I haven´t followed all of the discussion but why would it not be enough checking the status code of GeoServer endpoint?

That's what is already happening. It seems to me that there are certain cases where GeoNode and GeoServer can be both up and running, but not ready to accept uploads. It would be nice to understand why, because we could fix the standard Docker setup too (which is not possible to test automatically with geonode-selenium because we do not know when it is really ready to be tested).

**Comment by afabiani** [comment]
@frafra uhm, I'm not fully sure it is a timeout problem here. It looks to me more a setup issue instead. Something related to the fixtures, not loaded correctly or something. However, I'll investigate a bit more on this as soon as I have some time slots available.

**Comment by afabiani** [comment]
@frafra @t-book, for the time being, I will set the property to "False" by default and I will add (in the next commit) appropriate documentation.

I then will open a specific issue about this "spc-geonode" behavior described above.

**Comment by afabiani** [comment]
@frafra @t-book with the latest commits:

1. The Django message framework now uses the cookie store, thus avoiding to lock the DB
2. The `SESSION_EXPIRED_CONTROL_ENABLED` is set to `False` by default and can be enabled to Env
3. Updated `tutorials/advanced/geonode_settings/settings.html` variables by describing the new variable setting

image

This PR also refers to #4325 "List of documentation improvements" by refactoring the `tutorials/advanced/geonode_settings/settings.txt` accordingly.

**Comment by t-book** [comment]
Great @afabiani. Thanks a lot for this. The blocking does not occur in dev setup anymore and hence the issue is fixed for me.
@frafra This should solve the docker issue as well?

**Comment by afabiani** [comment]
I'm going to merge this and address the SPC GeoNode issue here

https://github.com/GeoNode/geonode/issues/4322

**Pull request merged**
