### PR TITLE
[Fixes: #7289] Missleading message on upload

### PR DESCRIPTION
**Pull request by t-book**
Remove text that could be misunderstood on upload

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@t-book we should probably update the translations too... but this can be done later on too.

Do you prefer include them into this PR or let me open a separate ticket?

**Comment by t-book** [comment]
yes correct..... as there is still some other work ongoing I would push the lang files here as well. but this will take until today late evening or tomorrow. in case you prefer to continue with a second issue please go-ahead

**Comment by afabiani** [comment]
@t-book nope that's ok. Feel free to merge the PR when you think is ready, or let me know if you need me to review it.

I would prefer to include everything in this PR if possible.

**Comment by t-book** [comment]
@afabiani I would do English, Spanish, German and Italian. in Italian do you prefer "Upload status" or "Stato caricamento" (google translate)

**Comment by t-book** [comment]
unsure with italian: https://github.com/GeoNode/geonode/pull/7290/files#diff-b0b68729645be0830ded32fc640b67257edfe0d12234bd4043141f1eaa6079b8R2498

**Pull request merged**
