### PR TITLE
Fix ISO 19139 metadata validity

### PR DESCRIPTION
**Pull request by matthesrieke**
This is a small fix for the ISO 19139 metadata template. Two validation problems are solved. Metadata served via pycsw should be valid after integrating the adjustments.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users): https://github.com/GeoNode/geonode/issues/7181
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by matthesrieke** [comment]
fyi: I am working on the CLA, probably a company-wide for 52North.

**Comment by matthesrieke** [comment]
CLA is signed now.

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
@matthesrieke nevermind, the backport bot was able to create it automatically

**Comment by matthesrieke** [comment]
thanks @afabiani !

**Comment by matthesrieke** [comment]
@afabiani might it also be suitable to backport this to `4.0.x` ? Its a smaller fix and an upcoming bugfix release could benefit from it.

**Comment by afabiani** [comment]
@matthesrieke 4.0.x is now a maintenance branch and therefore no new features are expected to be backported there, and we do not envisage any new 4.0.x release soon. The new stable is 4.1.x.

**Pull request merged**
