### PR TITLE
[Fixes #7761] Harvested resource permissions assignment must follow the same logic as uploaded resources

### LINKED ISSUE #7761: Harvested resource permissions assignment must follow the same logic as uploaded resources
Based on : https://github.com/geosolutions-it/nexus-geonode/issues/301

## Overview
From my tests it looks like visibility and download grants of resources created from harvestable resources are not assigned to anonymous users. 
I expect the permissions for this resoruces to follow the same logic as uploaded resources. I suspect that the harvester is doing more then what it's asked to do. Default permission assignments should be performed by the resource manager.

@ricardogsilva can you please check this behaviour?

### PR DESCRIPTION
**Pull request by meomancer**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by meomancer** [comment]
this fix https://github.com/geosolutions-it/nexus-geonode/issues/301

removeing harvester to handle default permission
CC @ricardogsilva

**Comment by afabiani** [comment]
@meomancer please fix PEP8 issues
`
^@^@geonode/harvesting/harvesters/base.py:157:9: F841 local variable 'harvester' is assigned to but never used
`

**Comment by meomancer** [comment]
updated @afabiani

**Comment by ricardogsilva** [comment]
@meomancer the PR looks good to me. Please update it with the latest changes from `master` and then I'll give a final review and approval.

**Review by giohappy — CHANGES_REQUESTED** [review]
fix conflicts

**Review by ricardogsilva — APPROVED** [review]
I'm +1 for merging this

**Review by giohappy — APPROVED** [review]

**Pull request merged**
