### PR TITLE
[Fixes #8561] Refactor the API for the update of the thumbnails

### LINKED ISSUE #8561: Refactor the API for the update of the thumbnails
## Expected Behavior

Thumbnails for all resources should be saved correctly.

## Actual Behavior

In this moment the update of thumbnails from the client work "by accident". Except for maps, the base64 string sent from the client is saved as it is, along the rest of the resource data, when a PATCH request is submitted. When the client loads the resource it's capable to manage the base64 string returned inside the `thumbnail_url` property and show it. 
By the way this is not the way things should work. The thumbnail should always be saved as an image and the `thumbnail_url` should always contain a staic url for the image.

The fix requires the following changes:

- [ ] The ResorceManager.set_thumbnail method must be extended to 
  - [ ] accept a file-like object representing the thumbnail 
  - [ ] call any specific intermediate method according to the resoruce type. In the case of documents the final `document.save_thumbnail` should be removed
  - [ ] call the `resource.save_thumbnail` method in the end
- [ ] A new set_thumbnail API must be exposed under the resources/{pk} endpoint. This endpoint will validate the POST data, perform any base64 decoding ( we can reuse some logic from [handle_map_thumbnail](https://github.com/GeoNode/geonode/blob/28357a5cdf0d93657033cdd78537567c98b39854/geonode/maps/utils/thumbnail.py#L42)) and, finally, call `ResourceManager.set_thumbnail` with a file-like parameter.
- [ ] Remove [these two lines](https://github.com/GeoNode/geonode/blob/28357a5cdf0d93657033cdd78537567c98b39854/geonode/maps/api/views.py#L166-L168) from the Maps API view

When this will be ready we will:
 - make any resource type API validate the content passed inside `thumbnail_url` (POST, PUT, PATCH) and **only accept URLs**. 
 - The MapStore client call the set_thumbnail API explicitly and stop patching the thumbnail_url field

## Steps to Reproduce the Problem

  1. Go to [master](https://master.demo.geonode.org/)
  2. Try uploading thumbnail for document, dataset or geoapp
  
hnh

  3. Check the url of the thumbnail saved.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by marthamareal**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by giohappy** [comment]
@marthamareal from our call:

 - the `set_thumbnail` endpoint should also accept (PUT) file uploads. DRF [FileUploadParser](https://www.django-rest-framework.org/api-guide/parsers/#fileuploadparser) can be used for this. In the future I expect this endpont will replace the `thumbnail_upload` method that is still used by the metadata wizard thumbnail widget (for documents and geoapps)
 - make the validation more robust, instead of relying on exceptions. 
 - in case no thumbnail is passed in the request the method will return an error

**Review by giohappy — CHANGES_REQUESTED** [review]
As reviewed in our live call the current PR has the following problems:

- you're using raw binary data for file upload, which is not what a web client usually does. A form data upload is the usual way, so the FileUpload parser must be replaced wtih the MultiPartParser
- relying on the try / catch exception is not robust. In several cases the based64 decode might try to decode a URL string, so a pattern matching must be done before passing the string to the base64 decoder
- even if a thumbnail is set an existing CuratedThumbnail takes precedence inside any API response. Since we're not using curated thumbnails anymore, we will remove any check inside the API, and we will directly return the `resource.thumbnail_url` . The next step will be (not in this PR) drop CuratedThumbnail and fix the metadata wizard widget accordingly

All these fixes has been committed to a [temporary branch](https://github.com/GeoNode/geonode/tree/marthamareal-issue-8561). Pull and merge them into your own private branch, then we will remove this temp branch.

What is left to you is fixing the tests (use form data upload instead of raw binary) and execute pep validation.

**Comment by afabiani** [comment]
@giohappy @marthamareal are we still using the REST endpoint `set_thumbnail_from_bbox` ? Could we maybe get rid of it?

**Comment by giohappy** [comment]
> @giohappy @marthamareal are we still using the REST endpoint set_thumbnail_from_bbox ? Could we maybe get rid of it?

@afabiani for the moment this new endpoint only covers the image thumbnails, and it will replace the legacy `thumbnail_upload` view that is currently used by the metadata wizard widget.

However I would be in favour of merging the two API v2 endpoints in a new PR.

**Review by giohappy — CHANGES_REQUESTED** [review]
@marthamareal

 - there's one [test that is failing](https://app.circleci.com/pipelines/github/GeoNode/geonode/6385/workflows/1a9e1d09-7088-4a42-b585-5dafadd36677/jobs/24082/parallel-runs/0/steps/0-106)
 - let's make the ResourceBase.thumbnail_url [API field read-only](https://www.django-rest-framework.org/api-guide/fields/#read_only). I mean from the point of view of the API not the model itself, of course

**Comment by marthamareal** [comment]
@giohappy I have updated this.

**Pull request merged**
