### PR TITLE
[New Docs] GeoNode Core Docker up and running

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by t-book** [comment]
Thanks, @afabiani looks good to me. If you haven't tested it already I can offer to do so this afternoon or tomorrow morning. In any case, I would wait for a review of @francbartoli as he has much more experience with docker.

**Comment by francbartoli** [comment]
I'm on it doing some tests. Minor things I would remove code formatting from headings, do you agree?

**Comment by afabiani** [comment]
@frafra go ahead, no worries

**Comment by francbartoli** [comment]
@afabiani we are too many Francesco on this project :)

**Comment by afabiani** [comment]
@francbartoli doh, sorry, I typed the wrong name :P

**Pull request merged**
