### PR TITLE
[Fixes #7057] ResourceBase for metadata-only resources

### LINKED ISSUE #7057: GNIP 83 - ResourceBase for metadata-only resources
# GNIP 83 - ResourceBase for metadata-only resources

## Overview

Flag `ResourceBase` instances in order not to be displayed in the GUI, but only available through CSW.

### Proposed By

- [etj](https://github.com/etj): Emanuele Tajariol

### Assigned to Release

This proposal is for GeoNode <version>.

### State

* [x] Under Discussion
* [x] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

With this kind of "hidden" ResourceBase, our underlying pyCSW can be decoupled from the data handled in GeoNode/GeoServer, and regain a bit of the functionalities lost when using the internal pyCSW (the only one currenlty maintained) wrt external catalogs.

A good use case is the publishing of service metadata documents that details the WMS, WFS and WCS services offered by our GeoNode/GeoServer instance.

## Proposal

The proposal is about adding a new boolean field `ResourceBase.metadata_only`, defaulting to false. 
 
The queries used to present resources on screen should exclude the ResourceBase records having `metadata_only=True`.

The CSW endpoint should be able to handle such records, so no changes are needed on that side.

Please note that it's up to future development or external modules to add metadata only records.

### Backwards Compatibility

The *DB migration* process will set the new fields to the default value, so existing data will all be visibile on GUI.
If no external logic is added which creates metadata only records, no changes will be visibile on the GeoNode instance.

External clients that use a **generic API** that returns all of the ResourceBase fields should be aware of the new attribute.
Anyway the presence of records with the metadata_only attribute set will be well-known in the GeoNode setup (since by default nothing will add such records), so the system architects shall consider how the metadata_only records will be used in the specific context.

External clients that use **CSW** should be aware that they will get all of the records. Anyway the same recommendations in previous paragraph applies here as well.

## Future evolution

We're developing a contrib app that allows the admin to add service metadata to the catalog.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani: +1
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt: +1

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

### PR DESCRIPTION
**Pull request by mattiagiupponi**
With this PR i want to:
- Add new migration file to add `metadata_only` (by default as False) with relative `Model `changes
- set `metadata_only=False` were needed in order to exclude the the resource from search/facet
- filter out resource with `metadata_only=True` from `get_visible_resources` in `geonode/security/utils.py`
- add new test coverage for classes: `LayerResource`, `DocumentResource`, `MapResource`, `TopicCategoryResource` 
- add new test coverage for function: `get_visible_resources`

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [x] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@mattiagiupponi @etj we should add this field to the REST APIs too I guess

**Comment by afabiani** [comment]
Here https://github.com/GeoNode/geonode/blob/master/geonode/base/api/serializers.py#L260

and here https://github.com/GeoNode/geonode/blob/master/geonode/base/api/serializers.py#L292

**Comment by afabiani** [comment]
@mattiagiupponi 

1. There's one test failing on rest apis, can you please double check?
```
======================================================================
FAIL: test_embed_urls (geonode.base.api.tests.BaseApiTests)
Ensure the embed urls reflect the concrete instance ones.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/base/api/tests.py", line 536, in test_embed_urls
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 17 tests in 90.091s

FAILED (failures=1)
```
2. Can you please fix the conflicts with master branch?

**Review by afabiani — CHANGES_REQUESTED** [review]
1. https://github.com/GeoNode/geonode/pull/7076#issuecomment-801781548
2. We need to update REST APIs too with the new field

**Comment by mattiagiupponi** [comment]
> 
> 
>     1. [#7076 (comment)](https://github.com/GeoNode/geonode/pull/7076#issuecomment-801781548)
> 
>     2. We need to update REST APIs too with the new field

@afabiani 
- master merged
- test fixed
- Field added to the rest api 
here: https://github.com/mattiagiupponi/geonode/blob/bd9f8197e0a2f438aa701fec5b58e1e8b1be23f9/geonode/base/api/serializers.py#L261
and here: https://github.com/mattiagiupponi/geonode/blob/bd9f8197e0a2f438aa701fec5b58e1e8b1be23f9/geonode/base/api/serializers.py#L293

**Pull request merged**
