### PR TITLE
Replace default crs with 3857

### LINKED ISSUE #3367: Remove 900913 definition in remote services
Apologies in advance if I'm using any terminology etc. incorrectly, I'm rather new with GeoNode.

Steps to reproduce: 
1) Install GeoNode 2.6 on Ubuntu 16.04 per instructions here http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html
2) Add the following Remote Service: http://www.agr.gc.ca/atlas/services/mapservices/aafc_watershed_2013/MapServer/WMSServer
3) Browse any layer, see pink tiles

When checking GetCapabilities for the WMS server, you can see the following coordinate systems defined:

<CRS>CRS:84</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:3857</CRS>

<CRS>EPSG:102100</CRS>

But when you examine the actual URL being generated by GeoNode for layer images

http://www.agr.gc.ca/atlas/services/mapservices/aafc_watershed_2013/MapServer/WMSServer?LAYERS=14&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&TILED=true&SRS=EPSG%3A900913&BBOX=-15028131.255,5009377.085,-12523442.7125,7514065.6275&WIDTH=256&HEIGHT=256

SRS=EPSG%3A900913

Is there something special that needs to be done with this type of remote service?

### PR DESCRIPTION
**Pull request by francbartoli**
Fixes #3367

### CODE REVIEW

**Comment by afabiani** [comment]
@francbartoli did you check that having 3857 as default in settings still works with default map layers in GeoExplorer? Since this is the default setup we need to be sure that clean installations still work well.

**Comment by francbartoli** [comment]
@afabiani I run all tests but actually I did not make any further tests manually. Going to check that out now.

**Comment by francbartoli** [comment]
@afabiani effectively everything seems to work fine apart from the geoexplorer viewer which is created with a zoom and a bbox with no correspondence to the uploaded layer. I'm probably missing something here where those settings are set, perhaps within geoexplorer?

**Comment by capooti** [comment]
One thing to consider here is also existing GeoNode instances. I can't check this right now, but we should make sure existing maps are not broken. If that is the case, we should provide a migration script I think.

**Comment by francbartoli** [comment]
Totally agreed, thanks @capooti for the hints. I haven't thought about that

**Comment by capooti** [comment]
who knows @francbartoli, maybe it would keep working. I don't remember if srs is serialized somewhere in db. It would require some investigation

**Comment by afabiani** [comment]
Will have a look as soon as I have some available time-slot

**Comment by afabiani** [comment]
@francbartoli starting from your branch I have updated the PR in order to correctly handle the CRS from GeoExplorer also. See this PR

https://github.com/GeoNode/geonode/pull/3417

**Comment by francbartoli** [comment]
Nice @afabiani thanks

**Comment by afabiani** [comment]
@francbartoli I'm going to close this since changes here are part of #3417

**Pull request closed without merging**
