### PR TITLE
Use defusedxml instead of xml

### LINKED ISSUE #4728: Use defusedxml instead of xml
Some functions can be obstacled by using defusedxml.

## Specifications

  - GeoNode version: all
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): all
  - Platform: all

### PR DESCRIPTION
**Pull request by t-book**
Used defused xml
Fixes #4728 Use defusedxml instead of xml

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

### CODE REVIEW

**Comment by afabiani** [comment]
Thanks @t-book 

As far as I can see most of the Travis issues are related to some formatting issues

```
OK
flake8 geonode
geonode/layers/metadata.py:27:1: F401 'defusedxml.lxml as dlxml' imported but unused
geonode/layers/metadata.py:45:16: F821 undefined name 'dxml'
geonode/tests/integration.py:1469:23: F821 undefined name 'etree'
geonode/tests/integration.py:1481:23: F821 undefined name 'etree'
geonode/tests/integration.py:1500:23: F821 undefined name 'etree'
geonode/tests/csw.py:128:67: F821 undefined name 'settings'
geonode/tests/csw.py:130:67: F821 undefined name 'settings'
geonode/tests/csw.py:132:67: F821 undefined name 'settings'
geonode/tests/csw.py:198:40: F821 undefined name 'settings'
geonode/tests/csw.py:203:40: F821 undefined name 'settings'
```

**Comment by afabiani** [comment]
adding to my previous comment... it might be possible that some test is missing some import or something also

```
======================================================================
ERROR: test_capabilities (geonode.tests.integration.GeoNodeGeoServerCapabilities)
Test capabilities
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/decorators.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/home/travis/build/GeoNode/geonode/geonode/tests/integration.py", line 1469, in test_capabilities
    rootdoc = etree.ElementTree(layercap)
NameError: global name 'etree' is not defined
======================================================================
ERROR: test_layer_zip_upload_metadata (geonode.tests.integration.GeoNodeMapTest)
Test uploading a layer with XML metadata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/home/travis/build/GeoNode/geonode/geonode/tests/integration.py", line 534, in test_layer_zip_upload_metadata
    uploaded = file_upload(thelayer_zip, overwrite=True)
  File "/home/travis/build/GeoNode/geonode/geonode/layers/utils.py", line 553, in file_upload
    identifier, vals, regions, keywords = set_metadata(xml_file)
  File "/home/travis/build/GeoNode/geonode/geonode/layers/metadata.py", line 48, in set_metadata
    'Uploaded XML document is not XML: %s' % str(err))
GeoNodeException: Uploaded XML document is not XML: global name 'dxml' is not defined
======================================================================
FAIL: test_layer_upload_metadata (geonode.tests.integration.GeoNodeMapTest)
Test uploading a layer with XML metadata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/home/travis/build/GeoNode/geonode/geonode/tests/integration.py", line 510, in test_layer_upload_metadata
    "GeoServer failed to detect the projection for layer [air_runways]. "
AssertionError: "Uploaded XML document is not XML: global name 'dxml' is not defined" != "GeoServer failed to detect the projection for layer [air_runways]. It doesn't look like EPSG:4326, so backing out the layer."
```

**Comment by t-book** [comment]
thanks @afabiani I will check it.

**Comment by t-book** [comment]
@afabiani missed pushing a commit, now unit tests do finish. It looks like test coverage decreased and codecov complains, right? What to do, to make it happy?

**Comment by afabiani** [comment]
@t-book global coverage increased by 0.01 so that's ok. The first one represents the relative coverage, no worries.
As a general info, in case you would like to help to improve the coverage, you might look here

https://codecov.io/gh/GeoNode/geonode

and in particular here

https://codecov.io/gh/GeoNode/geonode/tree/master/geonode

Let me test the PR locally first since this is a quite important change, then we can merge this.

**Comment by t-book** [comment]
> Let me test the PR locally first since this is a quite important change, then we can merge this.

thanks @afabiani 🙏

**Comment by t-book** [comment]
@afabiani See the bot comment above I could backport manually to 2.10 this Friday or Saturday if it helps?

**Comment by afabiani** [comment]
@t-book I'll take care of this today, no worries. Thanks for the effort.

**Pull request merged**
