### PR TITLE
[Fixes #5667] visual glitch on download formats modal

### LINKED ISSUE #5667: visual glitch on download formats modal
## Expected Behavior
The download formats are displayed nicely like:
grafik

## Actual Behavior
There is a strange bullet point in front of the download formats:
grafik

## Steps to Reproduce the Problem

  1. Have a layer you can download uploaded to geonode
  2. open the download layer button

## Specifications

  - GeoNode version: 2.10.2.dev1581417404
  - Additional details:

seems to be caused by this ` <li class="active">`:
https://github.com/GeoNode/geonode/blob/7423649e56b6a14d05c7f9d4857d03aab6106d56/geonode/layers/templates/layers/layer_detail.html#L298

In the expected behaviour screenshot I got rid of it by Firefoxs WebDevTools.

### PR DESCRIPTION
**Pull request by gannebamm**
Will fix the visual glitch in download modal

## Checklist
For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@gannebamm update your emails from https://github.com/settings/emails

**Comment by gannebamm** [comment]
> 
> 
> @gannebamm update your emails from https://github.com/settings/emails

done @afabiani

**Comment by afabiani** [comment]
@cla-bot recheck

**Comment by gannebamm** [comment]
@afabiani I did commit with my institute mail address. This seems to confuse the cla-bot. Should / cam I just alter the commit autor to my personal mail, or can this be merged as it is?

**Comment by t-book** [comment]
@gannebamm As we know for sure you have signed the CLA but just used another Email I do not see any reason to block your PR. Just pay attention next time to not upset clabot ;) hope this is fine for you @afabiani

**Pull request merged**
