### PR TITLE
Fix autocomplete for profiles and groups

### PR DESCRIPTION
**Pull request by sarasafavi**
This is the first step in resolving https://github.com/GeoNode/geonode/issues/2555; note that search itself is not fixed with this patch, only autocomplete. PR to fix search coming soon.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@sarasafavi can you check the failing test so we can get this merged during the sprint?

**Comment by sarasafavi** [comment]
@jj0hns0n rebased to pull in the updated travis yml; Java error should be resolved with this test run.

**Comment by jj0hns0n** [comment]
@sarasafavi can you update to master so we can merge.

**Comment by sarasafavi** [comment]
@jj0hns0n the GH auto-update-to-master should have done the trick (can't verify because I don't have the perms). Try now?

**Pull request merged**
