### PR TITLE
Use isPublished field to control whether a Resource is exposed in pycsw

### PR DESCRIPTION
**Pull request by tomkralidis**
As per #2332

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@tomkralidis can you check the failing test?

**Comment by jj0hns0n** [comment]
@tomkralidis can you try to address the failing test before we merge?

**Comment by tomkralidis** [comment]
The failing test is due to a resulting change to the workflow. I'll look deeper but we shouldn't merge this just yet b

**Comment by jj0hns0n** [comment]
Simone fixed it. Feel free to advise if it is not a good solution

**Comment by jj0hns0n** [comment]
@tomkralidis can you give an update on this ?

**Pull request merged**
