### PR TITLE
[Fixes #6952] Layer UUID handler

### LINKED ISSUE #6952: Layer UUID hook
The current generation of the `UUID` for the `Layers` is based on those two lines:

`instance.uuid = str(uuid.uuid1())` in [geonode/geonode/layers/models.py](https://github.com/geosolutions-it/geonode/blob/0a82a14f39d9545e9206d6f4cd5ae0fe68d4673f/geonode/layers/models.py#L620)
`layer_uuid = str(uuid.uuid1())` in [geonode/geonode/upload/upload.py](https://github.com/geosolutions-it/geonode/blob/0a82a14f39d9545e9206d6f4cd5ae0fe68d4673f/geonode/upload/upload.py#L596)

We want to let the UUID creation be pluggable and let the user use his own UUID generator based on their needs.

```
if hasattr(settings, 'LAYER_UUID_HANDLER') and settings.LAYER_UUID_HANDLER != '':
        from geonode.layers.utils import get_uuid_handler
        instance.uuid = get_uuid_handler()(instance).create_uuid()
```

And is enough to add this config in `settings.py` by specifying the object that is responsible to manage the new UUID
```
LAYER_UUID_HANDLER = "mymodule.myfile.MyObject"
```
More information related to the configuration are available in this [PR](https://github.com/GeoNode/geonode/pull/6953)

Documentation PR at this [link](https://github.com/GeoNode/documentation/pull/78)

### PR DESCRIPTION
**Pull request by mattiagiupponi**
Resolves issue [6952](https://github.com/GeoNode/geonode/issues/6952) by introducing a hook for manage the uuid
Documentation [PR](https://github.com/GeoNode/documentation/pull/78)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — COMMENTED** [review]
@mattiagiupponi ok with the implementation, missing a couple of things:

1. A smoke test that demonstrate the hook of the UUID and how it works
2. The title of the PR must be changed like `[Fixes #6952] Layer UUID handler`

**Comment by afabiani** [comment]
@mattiagiupponi please ignore my comments about the failing test, I guess I found the culprit.

**Comment by mattiagiupponi** [comment]
@afabiani Do you mean the test in the Thesaurus pr? (https://github.com/GeoNode/geonode/pull/6951)

**Comment by afabiani** [comment]
@mattiagiupponi yes, sorry

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi ok with the implementation, missing a couple of things:
> 
> 1. A smoke test that demonstrate the hook of the UUID and how it works
> 2. The title of the PR must be changed like `[Fixes #6952] Layer UUID handler`

@afabiani thanks for the comments, I have just pushed the changes requested.

- Smoke test added [here](https://github.com/GeoNode/geonode/blob/bb65e04b02ffd9530239f624295c8846354c5bf4/geonode/layers/tests.py#L1556), it's just a simple test to show how the custom uuidhandler will take care of updating the UUID on pre-save method.
- Title of the issue updated

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
We have two constant test failures which are not related to this PR, so, merging for time being. We will need to spot those failures on a dedicated branch.

**Pull request merged**
