### PR TITLE
Adding the createlayer contrib application, as per GNIP #3269

### PR DESCRIPTION
**Pull request by capooti**
This pull request implement GNIP #3269

The PR provides the createlayer contrib application with its related createvectorlayer django administrative commands.

Tests and documentation are included. To run tests you need to follow the instructions provided at the top of the createlayer/tests.py file

Here is the createlayer application in action: http://recordit.co/anFE0BQRYr

### CODE REVIEW

**Comment by francbartoli** [comment]
+1 like a lot, thanks @capooti

**Comment by afabiani** [comment]
Thanks @capooti very cool features. @simod in general I would agree with you, my only concern is if this works assuming GeoServer as backend or can be extended to other servers too. However +1 for the PR

**Comment by kalxas** [comment]
Big +1 from me!
Thanks @capooti

**Comment by davekennewell** [comment]
+1 This is great - I would also love to see it in the core, I've often needed this and used workarounds.

**Comment by capooti** [comment]
@simod what do you mean with adding to the core? Moving the code out from contrib and enabling the application in INSTALLED_APPS by default?

This could be done but:
* we need to disable the application when datastore is not based on PostGIS
* we need to find out a way to run tests, they require the PostGIS datastore
* we need to disable the application when OGC server is not GeoServer, as it creates the layer using the GeoServer REST API (though it should be pretty trivial to change that code and run SQL to create the layer)

I have a question for you guys in charge of the release process: now this application is in master: do I need to send PR vs 2.7.x? It should be relatively easy also to merge vs 2.6.x but at this point I am not sure if for 2.6.x new features are accepted?

**Comment by simod** [comment]
I see your points Paolo, maybe we will add to the core when all the tests will be running on postgres and postgres will be the default db, still it would be good to have a  check for geoserver anyway.

I think you could reissue the PR also for 2.7 while for 2.6 I wouldn't, this is not a minor feature. :)

**Pull request merged**
