### PR TITLE
Use GeoServer 2.14.4 for SPCGeoNode

### LINKED ISSUE #4522: GeoServer 2.14.4
Minor release update.

http://blog.geoserver.org/2019/06/13/geoserver-2-14-4-released/

### PR DESCRIPTION
**Pull request by frafra**
Fixes #4522.

We should probably update https://github.com/GeoNode/geoserver-docker, that is currently using 2.15.x instead of 2.14.x, even if on this repository we reverted that change back.

It would probably make sense to have these Docker repositories as submodules of the main Geonode repository or just copy them inside, as we do for SPCGeoNode.

### CODE REVIEW

**Comment by gannebamm** [comment]
+1 for incorporating the docker repositories into the main repo.

**Comment by afabiani** [comment]
@frafra @gannebamm what it the status of this PR? So, spcgeonode now uses geoserver 2.14.4?

**Comment by frafra** [comment]
@afabiani GeoNode uses GeoServer 2.14.x at the moment, so it seemed natural to me to update to the latest minor release. Nothing really critical. It would be better to coordinate this kind of upgrades, but I cannot update both standard and spc geonode setups because the standard dockerfiles are in another repository, that's all.

Feel free to accept or to drop it if we are going straight to 2.15.x.

**Comment by afabiani** [comment]
> @afabiani GeoNode uses GeoServer 2.14.x at the moment, so it seemed natural to me to update to the latest minor release. Nothing really critical. It would be better to coordinate this kind of upgrades, but I cannot update both standard and spc geonode setups because the standard dockerfiles are in another repository, that's all.
> 
> Feel free to accept or to drop it if we are going straight to 2.15.x.

Not a big issue on my side to update to 2.14.4. I was a bit resilient because of the imminent release. I don't think we will have enough time to deeply test GeoNode 2.10 with GeoServer 2.14.4 or 2.15.1

The thing is... GeoServer 2.14.4 has some dependencies updates (see the [changelog](https://osgeo-org.atlassian.net/jira/secure/ReleaseNote.jspa?projectId=10000&version=16755)) and this what worries me since GeoNode still relies on a few community modules which are not always in line with the official extensions.

I'm going to prepare the WARs, branches and docker images. If we are able to test them for at least a week, I would say that we can take the risk of releasing GeoNode 2.10 with GeoServer 2.14.4.

**Comment by afabiani** [comment]
@frafra @gannebamm builds created, branches created and docker images created
 - [x] 2.14.3
 - [x] 2.14.4

**Comment by afabiani** [comment]
@frafra @gannebamm please check https://github.com/GeoNode/geonode/pull/4556

**Comment by afabiani** [comment]
We confirmed a regression on GeoServer 2.14.4 affecting the REST SLDController.

We'll need to wait for the next minor or, better, switch to 2.15.1.

**Pull request closed without merging**
