### PR TITLE
[Fixes #5049] Thumbnails are generated with a point style for line/polygon layers

### LINKED ISSUE #5049: Thumbnails are generated with a point style for line/polygon layers
## Expected Behavior

A thumbnail for a line or polygon layer should be generated with a correct line or polygon style.

## Actual Behavior

Under some circumstances (large GS with many layers?) I have seen this bug happening on different instances.

## Steps to Reproduce the Problem

Not reproducible using a standard GeoNode installation.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

### PR DESCRIPTION
**Pull request by capooti**
This PR fixes the bug in the title #5049 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by capooti** [comment]
@afabiani I understand your points, but for the instance which I am in charge of this PR fixed the issue. If we cannot include this in the release will need to fork it unfortunately until we don't find a better way.
While I agree with you that this should be a minor issue, it seems to be perceived as a major one from the users.

**Comment by afabiani** [comment]
@capooti I'm just saying that I'm not fully comfortable with the solution proposed.
The issue seems to be related to the fact that the default style on GeoServer is not correctly setup somehow. Please check the other PR which might fix this issue already.
About sending the "styles" parameter to the thumbnail generator, I fully agree, but this is a feature which, imho, must be detailed a bit more.
In any case, we will need to create an issue describing exactly what we want to achieve.

**Comment by capooti** [comment]
dear @afabiani 
I can definitely see if other PRs fixes the issue before we decide to do with this one.
In any case, I am not sure what problem would this causes. The style is added to the GetMap request only if a default style exists for the layer, otherwise an empty style is used as the current code base does:

```python
if hasattr(instance, 'default_style'):
                                if instance.default_style:
                                    request_body['styles'] = instance.default_style.name
```

**Comment by capooti** [comment]
by the way we should do something with the "manage styles" page at some point, as it is really slow for instances which have thousands of styles. Maybe rather then loading the whole list we should have a textbox to search styles? what do you think?

**Comment by afabiani** [comment]
@capooti  let's work here https://github.com/GeoNode/geonode/pull/5116

**Pull request closed without merging**
