### PR TITLE
[Fixes #7718] Permissions assignments on Remote Services

### LINKED ISSUE #7718: Permissions assignments on Remote Services
**Is your feature request related to a problem? Please describe.**
Implement a basic usage of the permissions system for the remote-services

**Describe the solution you'd like**
Following the actual implementation of permissions for other resources, also the remote service should follow the same logic

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mattiagiupponi**
Basic implementation of permissions on remote services

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by giohappy — CHANGES_REQUESTED** [review]
@mattiagiupponi 

- we should remove the visibily to Anonymous users when a new Service is created, otherwise any user can see other's services.
- "Add Remote Service" layer is not available anymore. It ust be restored for any registered user (contributor).

image

**Review by afabiani — CHANGES_REQUESTED** [review]
There are PEP-8 issues

`^@^@geonode/services/views.py:104:1: W293 blank line contains whitespace`

**Comment by giohappy** [comment]
@mattiagiupponi unfortunately it looks there's still something to be fixed.
My normal user doesn't see the "Add Remote Service" button yet. I guess it's because the contributors group doesn't have the requested permission assigned. I guess we need a fixture that assign the permission to the group if it doesn't exist.

image

image

**Comment by mattiagiupponi** [comment]
@giohappy The issue was caused by the permissions used to understand if an user can add a resource or not.
I used the `base.add_resourcebase` permission, while by default the contributors has the `auth.addresourcebase` permission (the custom created by us). The PR now contains the check with the `auth.addresourcebase`, please let me know if we need to use the `base.add_resourcebase` and add it to the group by default or use the custom permission `auth.addresourcebase`

@afabiani pep8 issue fixed

**Comment by giohappy** [comment]
@mattiagiupponi as agreed we're going to revert the creation of the custom base_addresourcebase permission done in https://github.com/GeoNode/geonode/pull/7364.
We can simply use the default add_resourcebase permission created automatically by Django.

**Review by giohappy — APPROVED** [review]

**Review by afabiani — CHANGES_REQUESTED** [review]
Unfortunately the docker containers do not start anymore. Most probably this is caused by wrong migrations. We will need to fix this before merging.

**Comment by mattiagiupponi** [comment]
> Unfortunately the docker containers do not start anymore. Most probably this is caused by wrong migrations. We will need to fix this before merging.

Migration fixed, I thought that the Django default permissions were applied before the other app migrations.

**Comment by afabiani** [comment]
@giohappy @mattiagiupponi I was testing the PR... I'm not sure if this could be a regression or it is something still not implemented, but:

- By creating a new user and removing it from the "contributors" group, shouldn't be supposed to be unable to create new resources at all?
image

I currently see it not being able to create new Remote Services only.

Can you please provide more details on that? About the rest it looks good to me.

**Comment by afabiani** [comment]
What's exactly the meaning of the perm `add_resource_from_service`? As a contributor I cannot see the existing Remote Services
image

Moreover, if I try to create a Remote Service with the same URL I'll get and error
image

**Comment by mattiagiupponi** [comment]
Well as far as I see, looks like more something that is not implemented yet.
Looking at the code, the `Upload Layer` button is enabled if the user is logged in. There are no checks regarding any kind of checks related to any kind of group.

https://github.com/GeoNode/geonode/blob/1fdfb47fb7737c761357fdc06e79f92b9c71d913/geonode/templates/base.html#L300-L307

https://github.com/GeoNode/geonode/blob/1fdfb47fb7737c761357fdc06e79f92b9c71d913/geonode/layers/templates/layers/layer_list_default.html#L11-L13

You do not see the remote service only because you are not logged in as a superuser or staff member:

https://github.com/GeoNode/geonode/blob/1fdfb47fb7737c761357fdc06e79f92b9c71d913/geonode/templates/base.html#L308-L312

Maybe it is worth taking a look at all the templates and finding a common way to handle them.

About `add_resource_from_service` is meant to let the user import resources once the service is registered (you have to click on it and you will see a button named "import resources" (or similar)

And regarding that as a contributor you are not seeing the services, requested that only the owner of the resource should be able to see them (as admin you can see all the resources). 
Ad there was already a check that will raise an error if you try to register the same service 2 times:

https://github.com/GeoNode/geonode/blob/1fdfb47fb7737c761357fdc06e79f92b9c71d913/geonode/services/forms.py#L67-L74

**Comment by afabiani** [comment]
But what's the meaning of creating a Remote Service that is visible only to the owner and than prevent him to add resources?

**Comment by afabiani** [comment]
@mattiagiupponi can you please check if this error https://app.circleci.com/pipelines/github/GeoNode/geonode/3426/workflows/01b1c1e1-7c1f-4076-9940-f0ea7f827a8d/jobs/10259 is related to the PR?

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi can you please check if this error https://app.circleci.com/pipelines/github/GeoNode/geonode/3426/workflows/01b1c1e1-7c1f-4076-9940-f0ea7f827a8d/jobs/10259 is related to the PR?

i don't know, but I'm gonna check it

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi can you please check if this error https://app.circleci.com/pipelines/github/GeoNode/geonode/3426/workflows/01b1c1e1-7c1f-4076-9940-f0ea7f827a8d/jobs/10259 is related to the PR?

I made some researches and looks like that is a bug in Django:
https://code.djangoproject.com/ticket/10827

Looks like that the [solution ](https://code.djangoproject.com/ticket/10827#comment:30) is:
>If I move 'django.contrib.contenttypes' before 'django.contrib.auth' in INSTALLED_APPS, it works.

Or drop the actual DB and create a new one.
@afabiani I think that we can try by moving the installed apps before dropping the DB, do you agree?

**Review by giohappy — CHANGES_REQUESTED** [review]
https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/251#issuecomment-872849224

**Comment by afabiani** [comment]
> > @mattiagiupponi can you please check if this error https://app.circleci.com/pipelines/github/GeoNode/geonode/3426/workflows/01b1c1e1-7c1f-4076-9940-f0ea7f827a8d/jobs/10259 is related to the PR?
> 
> I made some researches and looks like that was a bug in Django:
> https://code.djangoproject.com/ticket/10827
> 
> Looks like that the [solution ](https://code.djangoproject.com/ticket/10827#comment:30) is:
> 
> > If I move 'django.contrib.contenttypes' before 'django.contrib.auth' in INSTALLED_APPS, it works.
> 
> Or drop the actual DB and create a new one.
> @afabiani I think that we can try by moving the installed apps before dropping the DB, do you agree?

Oh wow!
Ok... let's move the 'django.contrib.contenttypes' before 'django.contrib.auth' in INSTALLED_APPS then!

**Review by giohappy — APPROVED** [review]

**Review by afabiani — CHANGES_REQUESTED** [review]
Almost good, just a small issue.
The counter of the ingested resources still counts all of them
image
image

**Comment by mattiagiupponi** [comment]
> Almost good, just a small issue.
> The counter of the ingested resources still counts all of them
Fixed :)

**Pull request merged**
