### PR TITLE
Add UPDATE_THUMBS_ON_STYLE_CHANGE setting - refs #4092

### PR DESCRIPTION
**Pull request by capooti**

### CODE REVIEW

**Comment by afabiani** [comment]
So I added few comments... nevertheless I'm not sure to fully understand the goal of this PR.
It seems to avoid to save the layers accordingly to a variable, but the thumbnails are created on a post-save signal only if the resource has been just created, accordingly to my previous PR.

Are you sure this affects the thumbnail creation and addresses the issue connected to this PR?

**Comment by capooti** [comment]
I can't find your comments @afabiani 
in any case while you are right that now the thumbnail is not generated anymore (thus the name for this variable is inappropriate), it is still very slow a change of style action (even a few seconds) as the layer with current code is saved twice (1755 in helpers.py and 554 in geoserver.views) and for a style change doesn't need to be saved at all as nothing changes in django db, so I would rather suggest to remove that part of the code: what do you think?

To recap, I would remove this line (first unneeded save, as layer will be still saved at 555 in geoserver.views):
https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L1755

Also I would be inclined to remove the save here:
https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/views.py#L556

If this is required for updating the thumbnails, I would then suggest to return None in affected_layers if we just update a style.

In our instance the difference is dramatic after this change: style editor now works properly, before it was faulty and many times didn't work - particularly when making continue changes in the style editor.

**Comment by afabiani** [comment]
@capooti I agree with you about removing redundant saves. I would close this one and do the changes directly on the lines you indicated above.

**Comment by capooti** [comment]
thanks @afabiani it definitely makes more sense not to have that variable and just remove the unneeded calls.

**Pull request merged**
