### PR TITLE
[Fixes: #7105] Remove HTML tags from visualization

### PR DESCRIPTION
**Pull request by mattiagiupponi**
In order to remove the html tags from the visualization, the django utils `strip_tags` is used.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — CHANGES_REQUESTED** [review]
1. Let's please use `_remove_html_tags` instead of `strip_tags` or either remove `_remove_html_tags` everywhere
2. Why you assign `raw*` values to the resouce in catalog views? Isn't better to modify the XSL instead?

**Comment by mattiagiupponi** [comment]
> 1. Let's please use `_remove_html_tags` instead of `strip_tags` or either remove `_remove_html_tags` everywhere
> 2. Why you assign `raw*` values to the resouce in catalog views? Isn't better to modify the XSL instead?

1) Looks like that using only `_remove_html_tags` or `strip_tags` is not always enough.
Here is an example:

By default the text area add some `<p></p>`. Since i can add html to the text box, i can do something like this:  `<p>Abstract value & some text</p>`
In the Database the value will be saved as follow: `<p>&lt;p&gt;Abstract value &amp; some text&lt;/p&gt;</p>`
By using only  `_remove_html_tags`  i'll get this: `<p>No abstract & provided</p>` and as you can see, the second tags (the one that i put manually in the text area) are still present in the string, by adding also the `strip_html` i'm going to obtain the expected string -> `No abstract & provided`.
This issue is more frequent  with the Upload metadata feature, since (usually) the tags are converted.
By adding only the `strip_html`, we will have the same result.

Here is a small unittest to prove it (i'm gonna add it to the PR)
With only `_remove_html`
```python
    def test_converted_html_in_tags_with_only_remove_html_or_strip_html(self):
        tagged_value = """<p>&lt;p&gt;Abstract value &amp; some text&lt;/p&gt;</p>"""
        attribute_target_value = """Abstract value & some text"""
        r = ResourceBase()
        filtered_value = r._remove_html_tags(tagged_value)
        self.assertEqual(filtered_value, attribute_target_value)

AssertionError: '<p>Abstract value & some text</p>' != 'Abstract value & some text'
- <p>Abstract value & some text</p>
? ---                          ----
+ Abstract value & some text
```

With `strip_tags`:
```python
    def test_converted_html_in_tags(self):
        tagged_value = """<p>&lt;p&gt;Abstract value &amp; some text&lt;/p&gt;</p>"""
        attribute_target_value = """Abstract value & some text"""
        r = ResourceBase()
        filtered_value = strip_tags(tagged_value)
        self.assertEqual(filtered_value, attribute_target_value)

- &lt;p&gt;Abstract value &amp; some text&lt;/p&gt;
+ Abstract value & some text
```



With both:
```python

    def test_converted_html_in_tags(self):
        tagged_value = """<p>&lt;p&gt;Abstract value &amp; some text&lt;/p&gt;</p>"""
        attribute_target_value = """Abstract value & some text"""
        r = ResourceBase()
        filtered_value = strip_tags(r._remove_html_tags(tagged_value))
        self.assertEqual(filtered_value, attribute_target_value)

.
----------------------------------------------------------------------
Ran 1 test in 0.002s
```


2) No particular reason, i thought that was just the best place to do it. I'm gonna change and do it in the xsl

**Comment by afabiani** [comment]
I see, so please let's put `strip_tags` inside `_remove_html_tags`, just before returning the final value

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
@mattiagiupponi can you update the backport PRs too?

**Pull request merged**
