### PR TITLE
 [FIXES #7126] multi word iso category strings will not get translated 

### LINKED ISSUE #7126: multi word iso category strings will not get translated
## Expected Behavior
The iso category strings will get translated into the selected language.

## Actual Behavior
Categories with more than one word will not get translated:
grafik

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: master, 3.2.x, 3.1.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

The https://github.com/GeoNode/geonode/blob/master/geonode/custom_translations.py file does list the multi-word categories as one-word strings.

### PR DESCRIPTION
**Pull request by gannebamm**
fixed custom_translation.py errors and rebuild the translation files. **Only the german .po file was compiled to .mo**. The new translation strings must be translated by the respective native speakers.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [x] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by gannebamm** [comment]
@afabiani @t-book maybe we shall get the major languages covered in this PR? Like Italian, Spanish and French? I am not proficient in any of those, sorry.

**Comment by afabiani** [comment]
@gannebamm I agree... I can help only with Italian though :(

**Comment by t-book** [comment]
@gannebamm agree! Learning Spanish is on my Todo List. for a long time. Unfortunately, until now I can only help with german.

**Comment by dpadron** [comment]
I could collaborate with the Spanish translation. Can you tell me the steps to follow?

**Comment by gannebamm** [comment]
> I could collaborate with the Spanish translation. Can you tell me the steps to follow?

You can download the django.po file for spanisch localisation and upload it again somewhere. I will cover the rest.
Please use this file of this pull requests (not Master branch) 
geonode/locale/es/LC_MESSAGES/django.po

**Comment by afabiani** [comment]
@gannebamm I guess you will need to push also the *.mo files in order to see the translations on GeoNode.

**Comment by audetrobergem** [comment]
@gannebamm Here are the French translation files. I corrected some mistakes and added translations where there were none. I also corrected the isotopic categories. Let me know if there is anything that is not working. Cheers!
[geonode_french_translation.zip](https://github.com/GeoNode/geonode/files/6198313/geonode_french_translation.zip)

**Review by afabiani — APPROVED** [review]

**Comment by gannebamm** [comment]
@afabiani Thanks, for taking care of this! Sorry that I 'staled' this PR. I was on vacation and lost track of some of my open work here.

**Pull request merged**
