### PR TITLE
Added Ubuntu development installation instructions

### PR DESCRIPTION
**Pull request by capooti**
## Whart does this PR do?
Adds Ubuntu development installation instructions in readme and quick_install documentation

## Screenshot

Not applicatble.

## Related Issue

Apparently not issues are open about this.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@capooti Are these up to date for 16.04?

**Comment by capooti** [comment]
They are for 14.04 LTS

**Comment by jj0hns0n** [comment]
Ok, lets update for 16.04 asap (@kalxas can help with this)

**Comment by kalxas** [comment]
I am working on this.

**Comment by afabiani** [comment]
Could this be useful?

[Ubuntu 16.04 Server Complete Setup - shell instructions](http://pastebin.com/4SEpFFq1)

**Comment by kalxas** [comment]
Thanks @afabiani

**Pull request merged**
