### PR TITLE
Geosites, geonode multi-tenacy

### PR DESCRIPTION
**Pull request by simod**
This PR is sponsored by ICRAF http://landscapeportal.org/, adds a contrib app named geosites.
Geosites enables the geonode multi-tenancy through the use of the Django Site Framework.
Geosites enables multiple websites powered by the same geonode and geoserver with separate resources and users. There is a "master" site that has access to all the resources.

It is an update of the Portals app from the version 2.0.

thanks a lot to @matthewhanson !

### CODE REVIEW

**Comment by garnertb** [comment]
Mind squashing this?

**Comment by simod** [comment]
sorry, did it.

**Comment by garnertb** [comment]
Thanks, @simod.  This implementation looks good to me.  +1

**Comment by simod** [comment]
Also, this will be fully functional also on the geoserver side when https://github.com/GeoNode/geoserver-geonode-ext/pull/40 will be pulled in.

**Pull request merged**
