### PR TITLE
[Fixes #8136] Review advanced workflow

### LINKED ISSUE #8136: Review advanced workflow
Advanced workflow should work as descripted in the issues #3564, #6551, #7135.

- [ ] review functionalities
- [ ] implement test cases

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: at least 3.3.x

### PR DESCRIPTION
**Pull request by mattiagiupponi**
Major changes:
- Fix `set_permissions` in order to add default permissions to the `GroupManager` and `GroupMembers` if the advanced workflow is enabled
- Test to verify that the permissions are correctly set

Minor changes:
- settings `MONITORING_ENABLED=False` in `env_dev` file, otherwise raise errors
- add `owner` as param in `create_single_layer` test utils

**Acceptance criteria:**

**Scenario**: Advanced workflow is not active
Given `RESOURCE_PUBLISHING=False and ADMIN_MODERATE_UPLOADS=False`
When the user uploads a new resource
Then the user gets all the owner permissions (publish resource included)

**Scenario**: Advanced workflow is active
Given `RESOURCE_PUBLISHING=True and ADMIN_MODERATE_UPLOADS=False`
When the user uploads a new resource
Then the user gets all the owner permissions (`publish_resource` and `change_resourcebase_permissions` excluded)
And the GroupManager of the user's groups will get the owner permissions (`publish_resource` excluded)
And the GroupMember of the user's group will get the `view_resourcebase` permission
And the GroupMember of the resource's group will get the `view_resourcebase` permission

**Scenario**: Advanced workflow is active
Given `RESOURCE_PUBLISHING=False and ADMIN_MODERATE_UPLOADS=True`
When the user uploads a new resource
Then the user gets all the owner permissions (`publish_resource` and `change_resourcebase_permissions` excluded)
And the GroupManager of the user's groups will get the owner permissions (`publish_resource` excluded)

**Scenario**: Advanced workflow is active
Given `RESOURCE_PUBLISHING=True and ADMIN_MODERATE_UPLOADS=True`
When the user uploads a new resource
Then the user gets all the owner permissions (`publish_resource` and `change_resourcebase_permissions` excluded)
And the GroupManager of the user's groups will get the owner permissions (`publish_resource` excluded)
And the GroupMember of the user's group will get the `view_resourcebase` permission
And the GroupMember of the resource's group will get the `view_resourcebase` permission

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by etj — APPROVED** [review]

**Comment by etj** [comment]
Test with
```
export RESOURCE_PUBLISHING=False
export ADMIN_MODERATE_UPLOADS=False
```
Permissions on a just created resource:
image

Test with
```
export RESOURCE_PUBLISHING=True
export ADMIN_MODERATE_UPLOADS=False
```
image


Test with
```
export RESOURCE_PUBLISHING=True
export ADMIN_MODERATE_UPLOADS=True
```
image

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi @etj any chance to update the documentation also as part of this work? 

Yes, I'm going to update the doc as soon as I can

> Also, I see the PR includes a change to the `MONITORING` settings, is that intentional?

Yes, only in the `ENV_DEV`, by keeping `MONITORING_ENABLED=True` is raising issues on startup

**Comment by giohappy** [comment]
@etj regarding test for ADVANCED_WORKFLOW I don't see the permissions for anonymous user. Are they cut from the screenshot? If they're not initially set how "Any" is supposed to get them once the resource has been approved?

**Comment by etj** [comment]
@giohappy the tests above only shows records after the resource has been created. 

Client side, that's what we get:
image

-----
After the approval, we get:
image

image

-----
After the publication we get:
image

Ok @giohappy , something's missing indeed :|

**Comment by etj** [comment]
@giohappy 
I repeated the test with the code before the fix.
The results show that permissions have only been added, so the anonymous/any permission handling is not changed. 

 image

**Comment by giohappy** [comment]
@etj how are the following settings configured in your tests?
https://github.com/GeoNode/geonode/blob/2164b024c9746359ed7077e97364301dc4fed43d/geonode/settings.py?plain=1#L896-L901

**Pull request merged**
