### PR TITLE
Add postgis v10 fixes Issue #4354

### PR DESCRIPTION
**Pull request by gannebamm**
added postgis v10, switched to geonode/postgis image (and added it to the dockerimage folders for spc), added a second spatially enabled database inside the db-container, made passwords configurable in the .env file, added a second pg_dumper container for the geo-db, updated both pg_dumpers to use alpine3.8, swtiched to geonode.importer instead of rest.importer to enable shp to postgis ingestion.

selenium test will fail caused by #4497

### CODE REVIEW

**Comment by francbartoli** [comment]
I've merged the change with the lowercase suffix, let's see what happens

**Comment by gannebamm** [comment]
From Travis
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-9.6-postgis-2.4 nginx" failed and exited with 100 during .

Seems not related to my changes and btw geonode core does use postgis 10 and spc with my changes in this pr, too. Can't see why anything should pull postgres 9.6

**Comment by gannebamm** [comment]
Failed with

Unable to locate element: //button[contains(., 'Editing Tools')]


Again not related to my code

**Comment by frafra** [comment]
Everything is working on Travis CI. I have seen that error on the regular Docker setup, not with SPC, that is the one currently used by Travis.

**Comment by gannebamm** [comment]
triggered an merge with master. As frafra said the Travis CI checks were successfull last time.

**Comment by frafra** [comment]
What about importing existing files? Is there an easy way to digest previously inserted layers?

**Comment by afabiani** [comment]
@gannebamm tests have passed but I still see a pending comment from @frafra

**Comment by gannebamm** [comment]
@frafra about transforming the shape file layers to postgis ones:

I would like to make a gnip for that which is able to pull the layers info and data from one geonode and ingest it into an other. This would make an easy reingest of the files working. What do you think?

**Comment by frafra** [comment]
> @frafra about transforming the shape file layers to postgis ones:
> 
> I would like to make a gnip for that which is able to pull the layers info and data from one geonode and ingest it into an other. This would make an easy reingest of the files working. What do you think?

I think that being able to easily import and export layer would be a feature that could be used in many different scenarios 👍

**Pull request merged**
