### PR TITLE
[Fixes #12049] Adapt the SLD and XML upload forms to the new progress API

### LINKED ISSUE #12049: Temporary fix to SLD and Metadatata upload forms
The legacy backend to track the progress of SLD and XML uploads for datasets has been removed, breaking the behavior of the legacy forms.
We're planning to replace the legacy form with a new UI (https://github.com/GeoNode/geonode-mapstore-client/issues/1559). Meanwhile, a small adaptation in the legacy form must be implemented to use the new `executionrequests` endpoint to track the progress and redirect to the dataset once the upload is completed.

### PR DESCRIPTION
**Pull request by giohappy**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by giohappy** [comment]
@maabdelghaffar this depends on https://github.com/GeoNode/geonode-importer/pull/230

**Review by mattiagiupponi — CHANGES_REQUESTED** [review]
@giohappy it works in `sync` but not in `async`. The second call for getting the status raises an error (see screenshot). Looks like that from the second call, the `execution_data` is empty

image

**Comment by giohappy** [comment]
>@giohappy it works in sync but not in async. The second call for getting the status raises an error (see screenshot). Looks like that from the second call, the execution_data is empty as is the execution_id

@mattiagiupponi I'm not sure what you mean. If the `requests` array is not empty I expected that [exec_id was always available](https://github.com/GeoNode/geonode/pull/12050/files#diff-6d8a5453157bbb94ee88852ada8d0805875d51cf42eea01a1278f6fb49c6a00cR501). Do we have cases where a `request` can be returned without an execution id?

https://github.com/GeoNode/geonode/pull/12050/files#diff-6d8a5453157bbb94ee88852ada8d0805875d51cf42eea01a1278f6fb49c6a00cR501-R502

**Comment by giohappy** [comment]
So, the issue was inside the polling, where the execution_id wasn't forwarded to subsequent calls.

**Review by mattiagiupponi — APPROVED** [review]

**Pull request merged**
