### PR TITLE
[3.3.x][Fixes #8736] Align importlayers command to the new upload interface

### LINKED ISSUE #8736: Align importlayers command to the new upload interface
`importlayers` must be upgrade both for 3.3.x and master in light of the changes to te upload interface, including the support for remote files (https://github.com/GeoNode/geonode/issues/8667).

 - **3.3.x:** currently it still uses the old REST API
 - **master**: the old upload method was renamed to `upload_legacy` to maintain the compatibility with imporlayers. The `upload_legacy` method will be dropped

### PR DESCRIPTION
**Pull request by italogsfernandes**
references: #8736

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by mattiagiupponi** [comment]
The PR overall is good, just as decided with @giohappy, we want to backport the importlayers from master to `33x` to align this function between the versions

**Review by mattiagiupponi — APPROVED** [review]

**Comment by italogsfernandes** [comment]
@mattiagiupponi The command is backported, commit [36a525e](https://github.com/GeoNode/geonode/pull/8815/commits/36a525e0b45f9e7945521d527f99923717aa942c)

**Review by mattiagiupponi — CHANGES_REQUESTED** [review]
@italogsfernandes while doing some integration tests, after the upload (with the `not_interactive=True`) I'm calling the `api/v2/uploads/upload ` and I'm facing the following error. Looks like that the state of the layer is not set during the `not_interactive` upload

NOTE: the upload from UI works smoothly

```python
Internal Server Error: /api/v2/uploads/
Traceback (most recent call last):
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/bases.py", line 21, in wrapper
    self._resettable_cached_properties[func.__name__] = func(self)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 90, in data
    data = super(DynamicListSerializer, self).data
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 69, in to_representation
    return [self.child.to_representation(item) for item in iterable]
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 69, in <listcomp>
    return [self.child.to_representation(item) for item in iterable]
  File "/opt/core/geonode/geonode/base/api/serializers.py", line 66, in to_representation
    data = super().to_representation(instance)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 691, in to_representation
    self.obj_cache[pk] = self._to_representation(instance)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 646, in _to_representation
    representation = self._faster_to_representation(instance)
  File "/home/mattia/.virtualenvs/geonode33x/lib/python3.8/site-packages/dynamic_rest/serializers.py", line 623, in _faster_to_representation
    attribute = field.get_attribute(instance)
  File "/opt/core/geonode/geonode/upload/api/serializers.py", line 174, in get_attribute
    return instance.progress
  File "/opt/core/geonode/geonode/upload/models.py", line 219, in progress
    if self.layer and self.layer.processed and self.layer.state == Upload.STATE_PROCESSED:
AttributeError: 'Layer' object has no attribute 'state'
"GET /api/v2/uploads/ HTTP/1.1" 500 61151
```

**Comment by italogsfernandes** [comment]
@mattiagiupponi The backport is ready

**Review by mattiagiupponi — APPROVED** [review]

**Review by afabiani — APPROVED** [review]

**Pull request merged**
