### PR TITLE
[Fixes #8737] Errors in devcontainer and docker

### LINKED ISSUE #8737: Errors in devcontainer
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by italogsfernandes**
references #8737 

## What was done
* Some errors in the devcontainer and development docker-compose were fixed.
* Connection with geoserver is working.
* Nginx service is up again (it was not running).
* Updates in the .env file.
* Updates in the entrypoint: The `development` option was not working. 

## How to use
* Documentation:  https://docs.geonode.org/en/master/devel/docker/index.html

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by italogsfernandes** [comment]
As discussed with @mattiagiupponi, changed to draft while we find a better solution to the geoserver access.
* [ ] Set geoserver proxy url as `localhost:8080/geoserver` instead of `geoserver:8080/geoserver`
* [ ] Change the related .env variables.
* [ ] Update the docker setup to update the geoserver automatically, using a custom Docker image inherited from geonode/geoserver:2.19.
* [ ] Use paver to setup the data when initializing, instead of manually migrating and loading the fixture data.
* [ ] Setup docker to make possible to the owslib to access `localhost:8080` in the get map method and others (https://github.com/geopython/OWSLib/blob/master/owslib/map/wms111.py#L70).

**Comment by giohappy** [comment]
@italogsfernandes why do we need to run the migrate and loaddata commands manually? Aren't they [run automatically by the entrypoint.sh](https://github.com/GeoNode/geonode/blob/master/entrypoint.sh#L53-L55)

**Comment by italogsfernandes** [comment]
> @italogsfernandes why do we need to run the migrate and loaddata commands manually? Aren't they [run automatically by the entrypoint.sh](https://github.com/GeoNode/geonode/blob/master/entrypoint.sh#L53-L55)

Yes, this should happen automatically, but for some reason it's not.
There are also some issues with the communication between django and geoserver.
After looking for the reason why it's not working, I didn't find any. I'll ask @afabiani for help.

**Comment by italogsfernandes** [comment]
Ready for review

**Review by afabiani — APPROVED** [review]

**Comment by italogsfernandes** [comment]
> @italogsfernandes I guess this one should be backported to `3.3.x` also.

ok

**Comment by mattiagiupponi** [comment]
Is the error on the thumbnail fixed?

**Comment by afabiani** [comment]
@mattiagiupponi @italogsfernandes about the thumbnail issue the problem is that probably those URLs are not reachable from the container.

```
GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/
GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
```

Let's maybe try to set those to

```
GEOSERVER_WEB_UI_LOCATION=http://geoserver:8080/geoserver/
GEOSERVER_PUBLIC_LOCATION=http://geoserver:8080/geoserver/
```

If still not working there's probably no much we can do except maybe try to pass through the GeoNode internal proxy

```
GEOSERVER_WEB_UI_LOCATION=http://localhost:8000/gs/
GEOSERVER_PUBLIC_LOCATION=http://localhost:8000/gs/
```

**Comment by italogsfernandes** [comment]
@afabiani changing the .env variable is not working. It calls the geoserver service with no problems for the first call, but geoserver returns the proxy_url (localhost:80/geoserver) unrecheable from inside the django container. The following calls of the owslib makes uses of this url returned by geoserver.

https://github.com/geopython/OWSLib/blob/master/owslib/map/wms111.py#L70

**Comment by giohappy** [comment]
@afabiani @italogsfernandes regarding Geoserver URLs I don't understand why they're so problematic in this context, given that we deploy GeoNode in production with no issue in this regard. What's so different inside a dev container context?

**Comment by afabiani** [comment]
@giohappy `localhost` is different for every container, so, unless you do not use IP or names it is not possible to resolve the machines.

**Comment by giohappy** [comment]
@afabiani but this is true even for the usual prduction deployments we do. My question is why this part is so different for a dev setup?

**Comment by afabiani** [comment]
@giohappy in a production environment cannot be like this of course, however, after some more testing, if we change the GeoServer `proxy base url` to `http://geoserver:8080/geoserver` the `django` container will be able to reach the GeoServer one and render the thumbnail.

I also noticed that the documentation page is incomplete, the `oauth2` configuration must be also changed in order to make GeoServer and GeoNode communicate correctly.

I will push some updates shortly.

**Comment by giohappy** [comment]
@afabiani I trust you but I still cannot understand why the public base urls are taking the docker hosts in this context instead of "http://localhost" (as we have in production, of course with a real host in that case).

Anyway, the important thing is to have all this documented if manual changes are strictly required...

**Comment by afabiani** [comment]
@giohappy the `localhost` case is a special case. Unfortunately `localhost` is something different for any container, not sure if you see my point.

**Comment by afabiani** [comment]
@giohappy nope, let me provide you an example:

 - let's say GeoServer declares it is exposed on `http://localhost/geoserver` via its `proxyBaseUrl`
 - the `django` container then tries to create a thumbnail by making queries to the `WMS`
 - any request will fail because `http://localhost/geoserver/wms` it wont be correctly resolved from inside the `django` container

**Pull request merged**
