### PR TITLE
Geosites: search/groups and working test cases

### PR DESCRIPTION
**Pull request by ahmednoureldeen**

### CODE REVIEW

**Comment by ahmednoureldeen** [comment]
I see that it fails in test cases not related to geosites, @afabiani  can you help ?!

**Comment by afabiani** [comment]
@ahmednoureldeen yes, I'll take a look. Thanks for the PR

**Comment by afabiani** [comment]
Hello, it looks like there are code formatting issues

flake8 geonode
```
geonode/contrib/geosites/admin.py:35:1: E302 expected 2 blank lines, found 1
geonode/contrib/geosites/admin.py:43:1: W391 blank line at end of file
geonode/contrib/geosites/api.py:174:1: W391 blank line at end of file
geonode/contrib/geosites/autocomplete_light_registry.py:26:1: E302 expected 2 blank lines, found 1
geonode/contrib/geosites/autocomplete_light_registry.py:41:1: E302 expected 2 blank lines, found 1
geonode/contrib/geosites/autocomplete_light_registry.py:72:1: W391 blank line at end of file
geonode/contrib/geosites/views.py:216:13: E225 missing whitespace around operator
geonode/contrib/geosites/views.py:238:16: F821 undefined name 'ImmediateHttpResponse'
```

**Comment by ahmednoureldeen** [comment]
Thank for your support.
but it failed 
`The command "pip install -r requirements.txt" failed and exited with 2 during .`

**Comment by afabiani** [comment]
Keep getting segmentation fault on smoke tests, but currently I cannot figure out why!
I'll try to take a look tomorrow.

**Comment by afabiani** [comment]
So... after struggling almost a day with this, I am 100% sure this code causing issues to the model (should be something related to the signals).

Activating this module systematically causes "Segmentation Fault" (at least with sqldb).

The whole module needs a deep testing and refactoring. I really don't feel comfortable to merge this at this stage.

**Comment by ahmednoureldeen** [comment]
closed in favor of #4287

**Pull request closed without merging**
