### PR TITLE
Added `{{ block.super}}` to all `{% block extra_script %}`

### PR DESCRIPTION
**Pull request by gonrial**
As these templates extended from base if you want to add anaylics the script was not
included in all the site

Solves: https://github.com/GeoNode/geonode/issues/2937

### CODE REVIEW

**Comment by simod** [comment]
Hi, I see the point but what about if in the site_base.html you put the analytics just outside the extra_script block?

**Comment by gonrial** [comment]
I've checked and it's not showing. As `site_base.html` extends `base.html` all the code outside the block sections is not rendered.

**Comment by simod** [comment]
Sorry, I meant in base.html. site_base is just a mute page

**Comment by gonrial** [comment]
Yes I could do it, but the idea is not to copy a hole file just to add a simple script. Next release and I need to rewrite the hole theme.

**Comment by simod** [comment]
I can't see the difference though, even with "super" you will have to add your analytic script in the base.html inside the extra_script block no?
Sorry I'm asking this clarification because if the use case is correct then it is worth having this also in master. Thanks

**Comment by simod** [comment]
makes sense. Could you do a similar one on 2.6.x and master?

**Comment by gonrial** [comment]
2.5.x??

**Pull request merged**
