### PR TITLE
Fix for upload of zipped shapefiles. Closes #2220.

### LINKED ISSUE #2220: Zipped shapefile upload fails if .shp.xml file present
An error in the handling of the cleaned data fields prevents zipped shapefiles to be added to geonode.

### PR DESCRIPTION
**Pull request by etj**

### CODE REVIEW

**Comment by etj** [comment]
Sorry, forgot a logger initialization in there.

**Comment by simod** [comment]
https://travis-ci.org/GeoNode/geonode/builds/70093546#L1918

**Comment by jj0hns0n** [comment]
@etj can we get this fixed and merged (or is it good to merge now?) I ran into an issue with failed zip uploads today and woul be nice to get this in for 2.4RC1

**Comment by etj** [comment]
@jj0hns0n In b28ead5 I cleaned up the code according to the comments, so it should be fine now. Dunno why travis is failing though.

**Pull request merged**
