### PR TITLE
[Fixes: #6509] Broken diacritics in Geoserver style

### PR DESCRIPTION
**Pull request by t-book**
It looks following is happening.

open() decodes the bytes in the file to Unicode text (default encoding)
etree() reads the starting `<?xml version="1.0" encoding="UTF-8"?>` and likes to interpret the string but can't  as it's already decoded to a Unicode string.

My fix opens the file in binary which successfully interprets the demo sld from the tickets

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — APPROVED** [review]
That makes a lot of sense!

**Comment by t-book** [comment]
@afabiani :
@obersupermega reported that it did not work with docker (I've checked with paver). Before merging I will try to test it myself with docker.

**Comment by obersupermega** [comment]
Now I cloned the master fresh and then edited the helpers.py on the lines. Then I build it and run the spcgeonode stack. Unfortunately everything as before. @t-book Perhaps you can try it my way and look what happens for you?

**Comment by t-book** [comment]
Ehm … strange really strange. Haven't touched SPC for a long time. I cannot explain why it shouldn't work there but can try to test it

**Comment by afabiani** [comment]
@obersupermega if you rebuild the stack your changes will get lost

**Comment by obersupermega** [comment]
I think now I am completely confused. So far I have made all changes (added own subpages, added translations to many files, changed the index page and the layer list page completely) and after that I have done a docker-compose -f docker-compose.yml --build and all my changes were active. Why should it not work here now? Please enlighten me :-)

**Comment by t-book** [comment]
@obersupermega My bad. Yes you should end up with your local image. I did not remember how SPC defines the build context and was worried you end up with a container from docker hub. Long story short. I will now test with SPC.

**Comment by t-book** [comment]
@obersupermega @afabiani For me this patch works for SPC as well. This is how I did:

- Set `DEBUG=True` in .env
- Started SPC `up --build`
- entered django container and checked locale: `$locale` # all fine
- logout from container
Uploaded test files and checked log of django `docker-compose logs -f django`:

```
django_1          | The uploaded SLD file is not valid XML
django_1          | Traceback (most recent call last):
django_1          |   File "./geonode/geoserver/helpers.py", line 349, in set_layer_style
django_1          |     etree.XML(sld)
django_1          |   File "src/lxml/etree.pyx", line 3216, in lxml.etree.XML
django_1          |   File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
django_1          | ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
=> Legend broken

- Logged into the container again
- installed an editor: apt update; apt install vim
- edited `/spcgeonode/geonode/geoserver/helpers.py` as my patch suggest
- uploaded the SLD 
=> Legend working

(Interesting as no pyc files are written ?!)

Anyways I would say this can be merged but @obersupermega it would be nice if you can test again as shown.

**Comment by afabiani** [comment]
@t-book since this is a small patch and does not introduce for sure any regression, I would merge it.

I will also took the occasion to test this with the different installation methods as soon as I can. Thanks!

**Comment by t-book** [comment]
+1. go for it. Thanks.

**Comment by afabiani** [comment]
@obersupermega merging, feel free to reopen the issue if the problem is still there.

**Pull request merged**
