### PR TITLE
[Fixes #6412] Nav Toolbar Issue

### LINKED ISSUE #6412: Nav Toolbar gets distorted when multiple nav bar items are added by the admin
## Expected Behavior
The navbar should not hide some of the page content under all situations

## Actual Behavior
When multiple navbar menu items are added to the navbar by the admin, the height of the fixed navbar gets increased thereby hiding some of the page content from view.

navbar

## Steps to Reproduce the Problem

  1.  On the menu item, navigate to the menu page and create about three menu's with very long titles
  2. For each menu create, create at lease on menu item
  3. when you open the home page and all other pages that display the menu on a smaller screen (about 1000 px), the menu is distorted

## Specifications

  - 3.1.0.dev1599060531
  - manual
  - macOS Catalina

### PR DESCRIPTION
**Pull request by abulojoshua1**
Fixes distorted navbar when multiple nav bar items are added by the admin

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — APPROVED** [review]

**Comment by t-book** [comment]
@abulojoshua1 

When starting a fresh geonode project it looks like the measure of

```
$("#wrap").css("margin-top", (nav_bar_height - 20));
```

does not set the margin correctly. This is what it looks like:

Bildschirmfoto 2020-09-09 um 10 35 01

Can you kindly double-check that this is correct?

**Comment by abulojoshua1** [comment]
> @abulojoshua1
> 
> When starting a fresh geonode project it looks like the measure of
> 
> ```
> $("#wrap").css("margin-top", (nav_bar_height - 20));
> ```
> 
> does not set the margin correctly. This is what it looks like:
> 
> Bildschirmfoto 2020-09-09 um 10 35 01
> 
> Can you kindly double-check that this is correct?

@t-book, I'll double-check this

**Comment by t-book** [comment]
@afabiani I think it could be fixed with padding but instead of formerly 60px with the subtracted value:

https://github.com/GeoNode/geonode/pull/6413/files#diff-a831ccb49278853f2043c3444a7352dfR53

from the js function.

```
body {
    padding-top: 20px;
}
```

**Comment by abulojoshua1** [comment]
@afabiani, @t-book, I removed the default padding-top because when it ran together with the javascript function styling, It added extra padding that also distorted the look of the nave bar. When the navbar does not contain extra menu items, the default padding works well, but when the height of the navbar changes when for example the search input field is in focus and it takes up more space, the JS function comes in handy. I will try creating a fresh geonode project and investigate for a possible fix.

**Comment by t-book** [comment]
@abulojoshua1 Why do you need the -20px in your js function? Wouldn't it be fine without it?

**Comment by afabiani** [comment]
@t-book @abulojoshua1 I fixed it through https://github.com/GeoNode/geonode/commit/abc48720f685e4dc8a31567f0dd57a06c5d0c964

**Comment by t-book** [comment]
@afabiani thanks, this again raises my question

> Why do you need the -20px in your js function? Wouldn't it be fine without it?

But I do currently as you do. which works fine.

**Comment by afabiani** [comment]
It's a fix whenever your navbar gorws more than one line, e.g.:

image

**Comment by t-book** [comment]
I'm absolutely fine with the js snippet of @abulojoshua1  .

---

 Just for a possible refactoring in future. 
I think with Bootstrap 4 this has been fixed with class [fixed-top](https://getbootstrap.com/docs/4.0/utilities/position/#fixed-top). which is just `position: sticky`. Even if we do not go to bs4 we could still add it to navbar. A quick example: https://codepen.io/t-book/pen/qBZyXgZ the margin of body fits even if the menu grows: `.menu li { width: 45%;}`

---

last but not least. thanks @afabiani for your fix +1

**Pull request merged**
