### PR TITLE
Allow for https as public protocol

### PR DESCRIPTION
**Pull request by jondoig**
Read the protocol from new GEONODE_LB_PROTOCOL environment variable. If not set, default to http.

### CODE REVIEW

**Comment by jondoig** [comment]
Thanks @francbartoli. Changes made as requested to:
* [docker/env/production](https://github.com/UNSW-CFRC/geonode/tree/master/scripts/docker/env/production) files on UNSW-CFRC:master
* [entrypoint.sh](https://github.com/GeoNode/geoserver-docker/pull/56/commits/a6d09ef884541a72e23a35c5e62ee6cc7e65540a) on geoserver-docker (PR 56 there)

**Comment by francbartoli** [comment]
Thanks, I have requested a small change in there, also I think your branch has to be updated.

**Comment by francbartoli** [comment]
@afabiani I'm a little bit concerned about this merge until we won't have that PR merged from geoserver-docker. It might be we have to revert

**Comment by afabiani** [comment]
Ah sorry, I thought it was done. Feel free to revert.

Il ven 17 mag 2019, 22:18 Francesco Bartoli <notifications@github.com> ha
scritto:

**Pull request merged**
