### PR TITLE
[Fixes #6182] GNIP 77 - GetFeatureInfo Templating For GeoNode

### LINKED ISSUE #6182: GNIP 77 - GetFeatureInfo Templating For GeoNode
# GNIP 77 - GetFeatureInfo Templating For GeoNode

## Overview

This proposal aims to improve the way GeoNode injects a “GetFeatureInfo” Template into the maps created with MapStore2.

What is a “GetFeatureInfo” Template and how is it working now?

When “clicking” over a feature of a Layer into a GeoNode Map, an info window popups showing a formatted representation of the raw data identified by the coordinates (see Fig. 1)

image

The way how such information is presented to the user is defined by what we call “GetFeatureInfo Template”. The latter is basically an HTML snippet containing some placeholders and special inline codes that instruct GeoServer on how to generate the raw data output.

The outcome is a rendered HTML snippet with the real values replacing the placeholders of the Template.

Currently, GeoNode allows a very simple mechanism to customize the “GetFeatureInfo Template” of a Layer.

It is possible, through the Layer Metadata Editor Wizard, to assign a name and a label to the attributes we want to display on the GetFeatureInfo output.

Notice that the attributes without a label and name, in case others are present, won’t be rendered at all.

As an instance, by using the example above, we can customize a bit the Layer Metadata as shown in Fig. 2

image

The “GetFeatureInfo” output will change accordingly as shown in Fig. 3

image

### Proposed By

@afabiani 

### Assigned to Release

This proposal is for GeoNode 3.1.

### State

* [x] Under Discussion
* [x] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Current GetFeatureInfo Templates are limited to labels and order. The idea would be to allow GetFeatureInfo to be able to render also images, links, maybe other media in the future, and also to allow the user to customize the HTML template in a fancy way.

### Implement widget based visualization of attributes for GetFeatureInfo response

1. Add a new "Widget" column to the Dataset Attributes step of the Metadata Wizard, where "Link" or "Image" widgets can be selected (see Fig. 4).

2. GeoNode already inflates an HTML template if custom dataset attributes are defined. We need to extend this automatically created template to include HTML fragment to show the selected widget.

This is a simplified approach, which assumes that the specific attribute value is directly usable as a `<a href="value">` or a ``.

In both cases, we assume absolute URLs.

image

### Implement custom HTML template for visualization of GetFeatureInfo response

As an alternative to the use of aliases and widgets (see above) for the visualization of GetFeatureInfo response, we implement the option to configure a template as HTML code.

A textarea for the editing of the template will be placed below the table of attributes inside the Dataset Attributes step of the Metadata Wizard

In this case, GeoNode will not generate the GetFeatureInfo template for MapStore itself, rather the custom HTML will be used.

**NOTICE**: Attributes configurations and HTML templates are mutually exclusive options.

image

### Backwards Compatibility

No backward compatibility.

## Future evolution

 - Move the template editor on the GIS client in order to make easier the access to the UI.
 - Allow the GetFeatureInfo template to render other media types like videos and sounds.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani: +1
* Francesco Bartoli: +1 (mail in dev list)
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner: +1
* Florian Hoedt: +1

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

### PR DESCRIPTION
**Pull request by afabiani**
Full discussion [here](https://github.com/GeoNode/geonode/issues/6182)

Depends on:

 - [x] "django-mapstore-adapter" release
 - [x] Tests
 - [x] [Documentation](https://github.com/GeoNode/documentation/pull/42)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
@t-book @giohappy 

 - Docs available [here](https://github.com/GeoNode/documentation/pull/42)
 - Verified that dangerous javascript code is stripped out by the `Django HTMLField`

**Comment by t-book** [comment]
@afabiani  really nice, thanks! I also took some time to test xss vectors. looks good and I do feel comfortable with your solution 👍

**Comment by t-book** [comment]
Menubar of tinymce:  For example, the print button is not needed?

It should work to overwrite  the toolbar this in our settings file: 
```
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,anchor,"
    "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
    "code,help,wordcount",
    "toolbar": "undo redo | formatselect | "
    "bold italic backcolor | alignleft aligncenter "
    "alignright alignjustify | bullist numlist outdent indent | "
    "removeformat | help",
}
```
https://django-tinymce.readthedocs.io/en/latest/installation.html#configuration

( also `TINYMCE_COMPRESSOR` reads useful.)

in case we decide to not add tinymce settings into geonode.settings we should consider mentioning this source in docs.

Bildschirmfoto 2020-06-12 um 07 29 07

**Comment by afabiani** [comment]
@t-book nice catch. Easy improvement that can be added to the current PR.

**Comment by alban-doko** [comment]
This is a very nice addition for GetFeatureInfo.
 Is it possible to install highcharts in tinymce so we can also plot charts with feature info data?

**Pull request merged**
