### PR TITLE
update geosites contrib app to be work with geonode 2.10

### PR DESCRIPTION
**Pull request by ahmednoureldeen**
fixes to be compatible with geonode 2.10

### CODE REVIEW

**Comment by ahmednoureldeen** [comment]
@afabiani It is ready.

**Comment by afabiani** [comment]
@ahmednoureldeen can you mark this as [DRAFT] until the commits are finished?

**Comment by ahmednoureldeen** [comment]
@afabiani I don't have access rights to mark it as [DRAFT], 
and I needed to check travis build as I have problem with sqlite3 version in travis test containers.
For now I pushed all commits I have.

**Comment by afabiani** [comment]
@ahmednoureldeen is it possible to update the documentation too? (or add if missing?)

**Comment by ahmednoureldeen** [comment]
@afabiani so, can we proceed with this PR?! I suggest to get it working even if contrib apps moved out of geonode repo.

**Comment by francbartoli** [comment]
> @ahmednoureldeen This is a great contribution, a piece which was so much requested in the community! I believe we should improve the tests section with additional bdd or selenium ones though.
> 
> Also squashing the commits would help to review

@ahmednoureldeen I believe these changes haven't been covered

**Comment by ahmednoureldeen** [comment]
@francbartoli I am afraid that I don't have much time next days to do additional tests , but I will do my best.

**Comment by afabiani** [comment]
@ahmednoureldeen have you finished with this PR? My intention here would be to merge this first, since it is confined into contrib module only, and then extract it to a dedicated repo.

Any objections? @francbartoli comments?

**Comment by francbartoli** [comment]
@afabiani it is fine then to add more tests later if it will be moved into a separated repo.

**Comment by ahmednoureldeen** [comment]
@afabiani go ahead

**Pull request merged**
