### PR TITLE
[Fixes #7012]: CSW prefiltering

### LINKED ISSUE #7012: CSW prefiltering
**Is your feature request related to a problem? Please describe.**

We may want CSW endpoints returning only a subset of the catalog.
Such subsets may not be statically defined, e.g. we may want only the metadata of layers belonging to a certain group, so that whenever i create a new group, I can ask for its metadata by querying `csw/{group_slug}`.

**Describe the solution you'd like**
The simplest yet flexible solution would be to pass an optional filter class/function to `csw_global_dispatch`.
If such a filter is defined, the Layers passed to the csw local backend would be filtered by it.

**Describe alternatives you've considered**
Copy and modifiy the `csw_global_dispatch` in apps that may be an option, but that mean to have a lot of code duplicated, while implementing a pre-filtering in the original function would save a lot of code, while offering a simple point of extension.

**Additional context**
The foreseen solution is only aimed at the `pycsw_local` backend. Also, the authorization logic already in geonode only targets the local backend, so the other ones would not be included in this feature implementation as well.

### PR DESCRIPTION
**Pull request by mattiagiupponi**
In order to implement the feature requested in #7012 , this pr will introduce:
- changes in `csw_global_dispatch` in order to let the user inject (if needed) a function to `prefiltering` the data for `pycsw`

This change is totaly retro-compatible since by default this new feature is set to `None`

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by etj** [comment]
Pls add some tests

**Comment by mattiagiupponi** [comment]
> Pls add some tests

@etj tests added, moved `to ready for review` to trigger build/tests checks

**Review by afabiani — DISMISSED** [review]

**Comment by afabiani** [comment]
@etj @mattiagiupponi test failing

```
======================================================================
ERROR: test_given_a_request_for_multiple_layer_should_return_empty_value_in_xml_with_layer_filter (geonode.catalogue.tests.TestCswGlobalDispatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/catalogue/tests.py", line 98, in test_given_a_request_for_multiple_layer_should_return_empty_value_in_xml_with_layer_filter
    actual = root.find("{http://www.opengis.net/cat/csw/2.0.2}SearchResults").attrib["numberOfRecordsReturned"]
AttributeError: 'NoneType' object has no attribute 'attrib'

======================================================================
ERROR: test_given_a_request_for_multiple_layer_should_return_multiple_value_in_xml_with_layer_filter (geonode.catalogue.tests.TestCswGlobalDispatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/catalogue/tests.py", line 105, in test_given_a_request_for_multiple_layer_should_return_multiple_value_in_xml_with_layer_filter
    actual = root.find("{http://www.opengis.net/cat/csw/2.0.2}SearchResults").attrib["numberOfRecordsReturned"]
AttributeError: 'NoneType' object has no attribute 'attrib'

======================================================================
FAIL: test_given_a_request_for_a_single_layer_should_return_empty_value_in_xml_with_layer_filter (geonode.catalogue.tests.TestCswGlobalDispatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/catalogue/tests.py", line 92, in test_given_a_request_for_a_single_layer_should_return_empty_value_in_xml_with_layer_filter
    self.assertEqual(0, actual)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 311 tests in 4026.616s
```

**Comment by mattiagiupponi** [comment]
@afabiani Failing tests resolved. The failure was caused by an improper string formatting

**Pull request merged**
