### PR TITLE
[Fixes #7838] Make get_download_response manage remote documents

### LINKED ISSUE #7838: Make get_download_response manage remote documents
## Expected Behavior
Downloads and embeds should work for remote documents

## Actual Behavior

In case of a remote document [get_download_response](https://github.com/GeoNode/geonode/blob/dd84cf6aacb748cfab3ece13998a9dfa89dca8fa/geonode/documents/utils.py?plain=1#L64) must provide the document `href` value instead of the document link,

image

## Steps to Reproduce the Problem

  1. Upload document using url
  2. View document

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by marthamareal**
<Include a few sentences describing the overall goals for this Pull Request>
References #7838

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by afabiani** [comment]
Can we add a simple test case?

**Review by giohappy — CHANGES_REQUESTED** [review]
A quick recap of the (too many?!) document links:

 - [document.href](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/models.py?plain=1#L88): it either returns the `document.doc_url` if available or the reverse url of "document_download" -> [get_download_response](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/utils.py?plain=1#L64) with attachment True
 - [document.embed_url](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/models.py?plain=1#L127) -> reverse "document_link" -> [get_download_response](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/utils.py?plain=1#L64) with attachment False

`document.doc_url` is either populated manually when the deocument is created, or [from harvesters](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/harvesting/harvesters/geonode.py?plain=1#L268).

Problems with this PR:

 - if `document.doc_url` you call `document.href()`, which in turn checks `document.doc_url` and, if it's populated, it returns it. It's clearly wasted work.
 - why do you use a `redirect` here @marthamareal. The purpose of the issue is to make embed_url return the original doc url, not to perform a redirect

In the `document.embed_url` could be a proxy to `document.href`, since this already covers the case for remote documents.

**Comment by giohappy** [comment]
A quick recap of the (too many?!) document links:

 - [document.href](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/models.py?plain=1#L88): it either returns the `document.doc_url` if available or the reverse url of "document_download" -> [get_download_response](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/utils.py?plain=1#L64) with attachment True
 - [document.embed_url](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/models.py?plain=1#L127) -> reverse "document_link" -> [get_download_response](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/documents/utils.py?plain=1#L64) with attachment False

`document.doc_url` is either populated manually when the deocument is created, or [from harvesters](https://github.com/GeoNode/geonode/blob/2de253570b7e1a502ccc4d43bb3fcc7747e2dfdc/geonode/harvesting/harvesters/geonode.py?plain=1#L268).

Problems with this PR:

 - if `document.doc_url` is populated it calls `document.href()`, which again checks `document.doc_url` and, i populated, it returns it. Of course this is wated work.
 - why do you use a `redirect` here @marthamareal. The purpose of the issue is to make embed_url return the original doc url, not to perform a redirect

**Comment by marthamareal** [comment]
@giohappy @afabiani I have updated the PR.

**Review by giohappy — APPROVED** [review]

**Pull request merged**
