### PR TITLE
Initial celery integration.

### PR DESCRIPTION
**Pull request by garnertb**
This PR moves some of the blocking calls in GeoNode responses to celery tasks so that they can be performed outside of the request/response cycle.  By default, this functionality is disabled but can be enabled when the administrator changes the `CELERY_ALWAYS_EAGER` setting to `False`.  

@simod, @ingenieroariel, @capooti, @ischneider : Please let me know if any of you think this is a bridge too far for this release.  I'm happy to put this in an external app for now if so.

### CODE REVIEW

**Comment by simod** [comment]
@garnertb I like this. There is a pending PR https://github.com/GeoNode/geonode/pull/1884 that we wanted to merge and will clash with yours. If we merge this one before I'll update the other one.

**Comment by capooti** [comment]
@garnertb I like it, and looking forward to see a task for the upload. +1 here

**Comment by state-hiu** [comment]
Does the Celery daemon start with GeoNode automatically or do you need to execute separate init script?

**Comment by garnertb** [comment]
I've been managing the celery worker daemon in a separate init script (everything you need should be here https://github.com/garnertb/geonode/tree/celery-rebase/scripts/celery)

**Comment by jj0hns0n** [comment]
@garnertb Lets figure out where we are at on this

**Comment by garnertb** [comment]
@jj0hns0n, this is good to be merged.

**Comment by state-hiu** [comment]
Could you please add text or links to external pages as needed to the documentation, such as http://celery.readthedocs.org/en/latest/tutorials/daemonizing.html#daemonizing.  Although definitively worth the benefits, this will require additional instructions for sysadmins.

**Comment by jj0hns0n** [comment]
@state-hiu can you file a documentation issue for this.

**Pull request merged**
