### PR TITLE
Updated instruction for configure ssl on geonode: with version 2.4 

### PR DESCRIPTION
**Pull request by amefad**
closes https://github.com/GeoNode/geonode/issues/2570

some paths are changed

and is not necessary the step regarding python and java configuration because ssl is managed by apache mod_wsgi

### CODE REVIEW

**Comment by francbartoli** [comment]
@amefad please note that you PR cannot be merged unless you sign the [CLA](http://www.clahub.com/agreements/GeoNode/geonode)

**Comment by amefad** [comment]
CLA signed, should I make a new PR?

**Comment by jj0hns0n** [comment]
You should not need to, I'll check in a bit when I'm on the laptop

**Comment by ingenieroariel** [comment]
When this PR was created master was not passing tests. It needs to be updated to latest master so it has a correct .travis.yml file. Sorry for the inconvenience.

**Comment by jj0hns0n** [comment]
@amefad can you pull latest master onto this branch and update it? We can no-longer do that for you.

**Comment by amefad** [comment]
Ok done.

**Pull request merged**
