### PR TITLE
Support for QGIS Server backend.

### PR DESCRIPTION
**Pull request by ismailsunni**

### CODE REVIEW

**Comment by simod** [comment]
@ismailsunni the qgis server support is a very important stuff that the geonode ecosystem could benefit from. This PR is interesting and very big! Besides the tests failures, which can be fixed, I think that the approach of adding things to the geonode core is getting unsustainable in the long term and is the main reason why we are all building contrib or external app that can be enabled or pulled in easily (maybe with an ansible script). GeoNode should become as small as possible and new apps can be optional satellites so I would approve such PR if contains a self contained, documented and optional application. As a small note, references to any copyright or author in the code must be avoided and every new file should contain the geonode licence in the top https://github.com/GeoNode/geonode/blob/master/geonode/views.py#L1.

I ask other devs to give a comment as well.

Thanks for the very interesting job!

ps, it's also a good practice to squash the commits in one so to not pollute the commit history with too many atomic additions.

**Comment by timlinux** [comment]
Hi @simod Thanks for your comments. In general we have tried to follow the approach that the QGIS Server backed can be a contributed module. However there are also quite a few places where there are implicit assumptions that GeoServer is the backend.

I really like the idea of making GeoNode a small core and then plugging in extra functionality to it. Could we work with you to make the core workable for cases where people want to add new backends? We really didn't like putting in logic like https://github.com/GeoNode/geonode/pull/2491/files#diff-d72a1da91b74bd369f1b5f178877a80dR170 so it would be nice to find ways to avoid this backend specific logic.

We are going to update this PR with architecture diagrams etc. and some more details so please treat it as a discussion starter - we are happy to go away and refactor things to get them implemented in a way that meets the goals of the project. In the mean time, here is a generalised overview of what we have built.

screen shot 2016-06-08 at 09 56 53

**Comment by afabiani** [comment]
The stuff is quite interesting and the work done looks great... but I agree on what stated by Simone. Moreover, as a dev, I would like to see first improvement proposals with the technical analysis, separation of commits from core APIs and new functionalities (along with their issues) and each PR must have commit squashed and the test must pass.

Personally looking at a PR like this is quite confusing and it is hard to provide feedbacks on the code and potentials conflicts with other work. 
My 2 cents.

**Comment by timlinux** [comment]
Hi @afabiani No problem we will make separate PR's for core and then a separate contrib module for the QGIS Server app. I think the first priority is just to understand how you would like our submissions / proposals made (which your and @simod 's comments are helpful for). We will withdraw this PR and come at this in a more granular way.

**Comment by timlinux** [comment]
@simod and @afabiani I've just been looking through your improvement process docs. @ismailsunni see also https://github.com/GeoNode/geonode/wiki/Review-criteria. I think lets close this PR, make a nice ticket on the GeoNode issue tracker explaining what it is we are proposing to do, the impacts on GeoNode etc. and then come back with one or more PR's once the ticket has been thumbs upped by the GeoNode devs. Does that work for you @simod and @afabiani ?

**Comment by simod** [comment]
yes +1. thanks!

**Comment by ismailsunni** [comment]
ok, I will close it.
Thanks for the feedbacks :)

**Comment by timlinux** [comment]
I should also add that we have a staging server running at http://geonode.kartoza.com which may be in different stages of usability depending on what we have pushed on to it at any given time. But it can give you a better feel of what we are building...

**Comment by capooti** [comment]
This looks wonderful @timlinux, looking forward to see GeoNode working with more and more map server engines.
Having said so, as you suggests, this would be the right time to abstract the map engine logic in GeoNode core, and give the concrete implementation for each map engine (GeoServer and QGIS Server so far) in a contrib application.

**Comment by ingenieroariel** [comment]
<insert happy face>

**Pull request closed without merging**
