### PR TITLE
[Fixes #5476] Possible typo in SPCGeonode docker-compose.yml file 

### LINKED ISSUE #5476: Possible typo in SPCGeonode docker-compose.yml file
I have spotted a possible typo in docker-compose.yml recipe of SPCGeonode installation.
I refer to the installation guide here: http://docs.geonode.org/en/master/install/spc/index.html
The mentioned docker-compose.yml file is here: 
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/docker-compose.yml
Corresponding environment file is here:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/.env

According to the guide, the environment variables can be modified in the default `.env` file.
For specific database connection URL for Django and Geodatabase databases, devops can change corresponding credentials via `GEONODE_DATABASE_USER` and `GEONODE_GEODATABASE_USER` value in `.env` files.
However, by scanning `docker-compose.yml`, these value is not used anywhere and I suspect this is just a typo.
Currently the value of `GEONODE_DATABASE` and `GEONODE_DATABASE_USER` are the same default value. Then `GEONODE_DATABASE` environment variable is used in the place of user credentials field in database connection URL.

I propose that we change this to use the intended environment variable, which is `GEONODE_DATABASE_USER`

## Expected Behavior

Different value of `GEONODE_DATABASE` and `GEONODE_DATABASE_USER` should work given the user and database access exists.

## Actual Behavior

`GEONODE_DATABASE_USER` value is ignored.

## Steps to Reproduce the Problem

  1. Modify `.env` file to use different value of existing user but with different name than the database name. There should be no user with the same name with the database to reproduce this problem.
  2. Spin up containers using docker-compose
  3. Django and Geoserver will fail to start/hang because the database connection URL is wrong.

## Specifications

  - GeoNode version: master branch
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode Docer
  - Platform: Any docker engine installed OS. Currently tested on Mac.
  - Additional details:

### PR DESCRIPTION
**Pull request by lucernae**
- [Fixes #5476] Possible typo in SPCGeonode docker-compose.yml file

Change environment variable to refer GEONODE_DATABASE_USER
and GEONODE_GEODATABASE_USER respectively for user
field in database connections.

When testing GeoNode installation as described here in this document:
http://docs.geonode.org/en/master/install/spc/index.html
I did noticed that the environment variables has some typo.
The variables were defined in `.env` file but not used in `docker-compose.yml` in the appropriate location in database connection URL. Thus, I suspect this is a typo.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [X] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
Hi @lucernae 
thanks for your contribution. Would you kindly sign the CLA as explained here: https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md 

Further, open an issue for your PR

>  There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end users)

> The issue connected to the PR must have Labels and Milestone assigned

Thanks!

**Comment by lucernae** [comment]
Thank you @t-book . Previously I thought it was not required for one file small bug fix. Will do it as requested.

**Comment by t-book** [comment]
thanks @lucernae

**Comment by gannebamm** [comment]
strange, I use them and had not spotted any issues with the current env - even though I must admit they look wrong. Let´s see what the tests say.

**Comment by lucernae** [comment]
The default settings in .env have GEONODE_DATABASE and GEONODE_DATABASE_USER with the same value. So default settings works.

**Comment by gannebamm** [comment]
@lucernae Of course, my fault.
I see only selenium SPC failing on travis, which has nothing to do with these changes. I would approve them.

**Comment by lucernae** [comment]
Hi @t-book @gannebamm , I've submitted the CLA as requested to info@osgeo.org and geonode-devel@lists.osgeo.org
I've also updated PR title according to the issue.

**Pull request merged**
