### PR TITLE
QGIS Server Related PR: Add API Support for QGIS Desktop interoperability

### PR DESCRIPTION
**Pull request by lucernae**
Last phase of #3362

In this PR, we develop API changes so it can be used in QGIS to query information which is not included in CSW metadata.

Review needed to spot possible duplicate functionality/use cases which already covered in CSW.

Main changes:
- Allow to include GeoNode version on Resource based API
- Allow Layer links query
- Allow Layer details query
- Allow QGIS Style API query

### CODE REVIEW

**Comment by afabiani** [comment]
Hi @lucernae thanks for your work. I'll try to review as soon as possible, but I expect also other devs to take a look at this since it is touching GeoNode REST APIs.

**Comment by lucernae** [comment]
Thanks @afabiani , yes this PR is mainly about GeoNode REST API so it needs reviews from other devs. Feedback is appreciated 😄

**Comment by afabiani** [comment]
@lucernae any idea why this is failing on Travis?

**Comment by afabiani** [comment]
Ah flake8 issues
```
flake8 geonode
geonode/qgis_server/tasks/update.py:35:1: F811 redefinition of unused 'QGISServerLayer' from line 27
```

**Comment by lucernae** [comment]
Ah, sorry @afabiani, Thank's for fixing it. Not sure why it doesn't show up before.
Does it need something else for it to be approved?
Should I invite other developer in dev mailing lists to take a look at this one?

**Pull request merged**
