### PR TITLE
Updated New docs

### PR DESCRIPTION
**Pull request by amefad**
Just modified a few lines in core/installation (is partial overlapping with anastasi-oq PR) and started project installation description....
(At least now I'm ready to contribute)

### CODE REVIEW

**Comment by t-book** [comment]
@afabiani I would merge but would like to ask if you agree to remove:

```
  # Create the GeoNode Virtual Environment (first time only)	  # virtualenv
  sudo python -m pip install pip==9.0.1	  source $HOME/.local/bin/virtualenvwrapper.sh
  sudo pip install --upgrade pip	
  pip install --user virtualenv	Then run the ``.bashrc`` from shell
  pip install --user virtualenvwrapper
```

https://github.com/GeoNode/geonode/pull/4489/files#diff-51fc3d1e63054b7761520f0acf7db839L75

as @amefad suggests.

**Comment by afabiani** [comment]
@amefad thanks, @nastasi-oq solved some conflicts on the docs and create this new PR 

https://github.com/GeoNode/geonode/pull/4503

which substitutes this one.

**Comment by amefad** [comment]
I agree,  @nastasi-oq has done a wider work... Im not sure cause I'm
reading  from smartphone but it seems that we have lost the installation of
virtuslenv amd virtualenwerapper....

Amefad

Il gio 13 giu 2019, 15:59 Alessio Fabiani <notifications@github.com> ha
scritto:

**Comment by nastasi-oq** [comment]
> but it seems that we have lost the installation of
> virtuslenv amd virtualenwerapper....
@amefad moved in the code above:
https://github.com/GeoNode/geonode/commit/e34eebb6c315844a9e025b6df6fb3f94ba2da0d9#diff-51fc3d1e63054b7761520f0acf7db839R27

**Pull request closed without merging**
