### PR TITLE
Multiple Topic Categories

### PR DESCRIPTION
**Pull request by EduardoCastanho**
- Add Multiple Topic Categories
- New  Flag "ADD_NEW_CATEGORIES_FROM_METADATA"

### CODE REVIEW

**Comment by pjdufour** [comment]
Could you squash your commits before merging?  I'm also seeing some conflicts with master that would need to be resolved anyway.  Thanks

Squashing is a little dangerous, so I'm happy to take it on when it's time to merge if needed.  It'll go something like this:

```
git rebase -i HEAD~5
git push -f origin Geonode_Multiple_Topic_Categories
```

**Comment by EduardoCastanho** [comment]
Done!

**Comment by pjdufour** [comment]
Thanks!

**Comment by jj0hns0n** [comment]
@tomkralidis @simod can you guys weigh in on this one?

**Comment by tomkralidis** [comment]
@EduardoCastanho thanks for this.  Comments:

- ensure you are detecting multiple topic categories when uploading data with a metadata document
- at some point we'll need migrations given the changes to `geonode.base.models.ResourceBase`

**Comment by jj0hns0n** [comment]
@EduardoCastanho can you update to master and sign the CLA so we can merge this. @tomkralidis can you merge when all your concerns are addressed.

**Comment by tomkralidis** [comment]
@EduardoCastanho per @jj0hns0n's comment, can you update the PR and address my comments on multiple topic categories?

**Pull request closed without merging**
