### PR TITLE
Update migrations

### PR DESCRIPTION
**Pull request by ingenieroariel**
Master seems to be missing some migrations. If anyone has more insight, please comment.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@ingenieroariel why does flake8 cry about the migrations?

**Comment by ingenieroariel** [comment]
I don't know but we should probably turn flake8 off for migrations. Last time I had to update them by hand for tests to pass. autoflake and autopep did not fix it.

**Comment by pjdufour** [comment]
These aren't duplicates of the ones done in https://github.com/GeoNode/geonode/pull/2617.

I used `# flake8: noqa` as the second line in migration files to turn off pep8 checks.

**Comment by ingenieroariel** [comment]
@pjdufour my system today generated the following migration automatically

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160825_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='keywords',
            field=taggit.managers.TaggableManager(to='base.HierarchicalKeyword', through='base.TaggedContentItem', blank=True, help_text='commonly used word(s) or formalised word(s) or phrase(s) used to describe the subject (space or comma-separated', verbose_name='keywords'),
        ),
    ]
```

**Pull request closed without merging**
