### PR TITLE
GNIP 89: Architecture Design - Resource and Storage Manager Modules

### PR DESCRIPTION
**Pull request by afabiani**
Refererences: [GNIP 89: Architecture Design - Resource and Storage Manager Modules](https://github.com/GeoNode/geonode/issues/7664)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by gannebamm** [comment]
I am testing this PR with a minio S3 based storage manager here:
https://github.com/gannebamm/geonode/tree/storage_test

It does seem like the migrations are somehow broken?
```
  File "/usr/src/geonode/geonode/geoserver/migrations/00001_convert_layer_storetype.py", line 15, in change_value
    for l in ll:

...
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column layers_layer.use_featureinfo_custom_template does not exist
LINE 1: ...r"."remote_service_id", "layers_layer"."charset", "layers_la...
```

**Comment by afabiani** [comment]
> I am testing this PR with a minio S3 based storage manager here:
> https://github.com/gannebamm/geonode/tree/storage_test
> 
> It does seem like the migrations are somehow broken?
> 
> ```
>   File "/usr/src/geonode/geonode/geoserver/migrations/00001_convert_layer_storetype.py", line 15, in change_value
>     for l in ll:
> 
> ...
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> django.db.utils.ProgrammingError: column layers_layer.use_featureinfo_custom_template does not exist
> LINE 1: ...r"."remote_service_id", "layers_layer"."charset", "layers_la...
> ```

@mattiagiupponi can you take a look?

**Comment by mattiagiupponi** [comment]
> I am testing this PR with a minio S3 based storage manager here:
> https://github.com/gannebamm/geonode/tree/storage_test
> 
> It does seem like the migrations are somehow broken?
> 
> ```
>   File "/usr/src/geonode/geonode/geoserver/migrations/00001_convert_layer_storetype.py", line 15, in change_value
>     for l in ll:
> 
> ...
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> django.db.utils.ProgrammingError: column layers_layer.use_featureinfo_custom_template does not exist
> LINE 1: ...r"."remote_service_id", "layers_layer"."charset", "layers_la...
> ```
Hi @gannebamm,
I had already found this error, I have already opened a PR (with some other development) which contains the fix for this issue too.
Meanwhile, the PR is not merged, if you want to try to continue your test, can you please try to replace the content of the migration file with this one? https://github.com/geosolutions-it/geonode/blob/5666b285fc7750806af0bdddbc744fa397281839/geonode/geoserver/migrations/00001_convert_layer_storetype.py

Please, let me know if it works!

**Comment by gannebamm** [comment]
Hi @mattiagiupponi,
The composition does successfully start and I am able to upload a shapefile. Uploading an image (or any other document) will fail for an aws storage manager due to a not defined bucket name. See:
```

Request Method: 	POST
Request URL: 	http://localhost/documents/upload
Django Version: 	3.2.4
Exception Type: 	ParamValidationError
Exception Value: 	

Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

Exception Location: 	/usr/local/lib/python3.8/site-packages/botocore/handlers.py, line 236, in validate_bucket_name


  File "./geonode/documents/views.py", line 246, in form_valid
    filepath = storage_manager.save(f"{dirname}/{file.name}", file)
  File "./geonode/storage/manager.py", line 102, in save
    return self._concrete_storage_manager.save(name, content, max_length=max_length)
  File "./geonode/storage/aws.py", line 49, in save
    return self._aws.save(name, content)
```

I have added the `AWS_STORAGE_BUCKET_NAME=geonode` to .env

**Comment by mattiagiupponi** [comment]
> Hi @mattiagiupponi,
> The composition does successfully start and I am able to upload a shapefile. Uploading an image (or any other document) will fail for an aws storage manager due to a not defined bucket name. See:
> 
> ```
> 
> Request Method: 	POST
> Request URL: 	http://localhost/documents/upload
> Django Version: 	3.2.4
> Exception Type: 	ParamValidationError
> Exception Value: 	
> 
> Parameter validation failed:
> Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
> 
> Exception Location: 	/usr/local/lib/python3.8/site-packages/botocore/handlers.py, line 236, in validate_bucket_name
> 
> 
>   File "./geonode/documents/views.py", line 246, in form_valid
>     filepath = storage_manager.save(f"{dirname}/{file.name}", file)
>   File "./geonode/storage/manager.py", line 102, in save
>     return self._concrete_storage_manager.save(name, content, max_length=max_length)
>   File "./geonode/storage/aws.py", line 49, in save
>     return self._aws.save(name, content)
> ```
> 
> I have added the `AWS_STORAGE_BUCKET_NAME=geonode` to .env

Ok great, maybe was not mentioned, but the storages are based on this library [django_storages](https://django-storages.readthedocs.io/en/latest/) which (based on the storage that you want to use) requires some different configuration.
The doc for the AWS is [here](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html)
I'm ensuring to add this to the doc PR when will be ready

**Pull request merged**
