### PR TITLE
[Fixes #6525] changed order of layers and services in fixtures-list.

### LINKED ISSUE #6525: Error when using "python manage.py backup ..." and "python managy.py restore" in combination with postgres (foreign key constraint)
## Expected Behavior
restore a backup from "python manage.py backup ..."

## Actual Behavior
Errors on restore because layers rely on spcific services that are not yet restored.

From gitter:

> Once again I have an issue. This time I am testing the backup-restore function of GeoNode. I do a backup within a geonode-project based docker-environment, moving the backup-files to a the same environment on another server and restoring the backup-zip there from within the running (and newly created, empty) docker environment. In gerneral I think this is the way it is supposed to work.
> Sadly, I am getting an traceback while restoring. This is the log: https://gist.github.com/jannefleischer/01f7a8d4af1bda3b2988e2b96a6825ee
> I am guessing the order of the restore is wrong. When processing layers.json the seem to be a link to services.json which hasn't been processed at that time, so a forein key constraint won't work.

## Steps to Reproduce the Problem

  1. no clue.
  2. But: There is a PR that fixes it, at east for me:  #6517 

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 18.04 to 20.04
  - Additional details:

### PR DESCRIPTION
**Pull request by jannefleischer**
So constraints on layers to services won't invalidate in django-db-check. 

Also added a convenience function, for listing all first invalid entries in all fixtures (instead of just abort after first invalid fixture)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation) - **TINY PR - Not necessary (hopefully)**
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by jannefleischer** [comment]
@t-book Is this a pull request that is ok? You asked for it on gitter.

**Comment by t-book** [comment]
@jannefleischer thanks. 
For every PR it's important to open an issue which explains why code changes are needed.
`Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"`

Further, if you do plan future contribution please sign the cla (https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) If not (and this is a single fix for now), I can submit your PR. As I'm not using BR I would further kindly ask @afabiani for a review.

**Comment by afabiani** [comment]
The patch makes sense. It would be good to have an issue describing what's the problem for this so that people can find the solution on the web in the future.

**Review by afabiani — APPROVED** [review]

**Comment by t-book** [comment]
@jannefleischer this PR is ready to be merged. One thing missing. Can you kindly sign the CLA and afterward drop me a line?

**Comment by jannefleischer** [comment]
I sent it this morning.

**Comment by afabiani** [comment]
@jannefleischer perfect thanks, I added you to the CLA list.

**Pull request merged**
