### PR TITLE
Adding Greek code 'gre' into Language field in admin layer's form

### PR DESCRIPTION
**Pull request by Gpetrak**
I tried to upload shapefiles with xml metadata catalogues but after uploading, the layer detail page raised 500 internal error. I realized that the problem came from the language code because the LanguageCode tag in the xml file, had the codeListValue="gre" (Greek language code) while the Language field in admin Layer metadata form didn't contain that code. As a result, the system assigned as language code the first choice from the list (Abkhazian). So, I added the 'gre' code in geonode/base/enumerations.py and the problem solved.

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @Gpetrak

**Comment by afabiani** [comment]
2.6.x build keeps failing in Travis, but I don't know exactly why. Most probably the travis.yml should be updated.

**Comment by kalxas** [comment]
Perhaps we should first apply this on master and see what happens

**Comment by Gpetrak** [comment]
Thanks  for the idea @kalxas. I will make a pull request for that on master

**Pull request closed without merging**
