### PR TITLE
fix Object of type Map is not JSON serializable

### PR DESCRIPTION
**Pull request by hishamkaram**

### CODE REVIEW

**Comment by hishamkaram** [comment]
@afabiani fix for Object of type Map is not JSON serializable (celery4)

**Comment by afabiani** [comment]
oh! Thanks @hishamkaram 

this is why tests are important and very welcome!

**Comment by hishamkaram** [comment]
@afabiani you are right

**Comment by simboss** [comment]
...and where are tests in this case?

**Pull request merged**
