### PR TITLE
[Fixes #5318] Wrong sections disposition on Welcome page

### LINKED ISSUE #5318: Wrong sections disposition on Welcome page
## Expected Behavior
 - `Features Datasets` should appear only if actually there are some of them
 - `Features Datasets` title is printed above GeoNode statistics, which seems to be wrong
 - The link `Explore all datasets` is already covered by the `Advanced Search` one

I'd expect to see something like this if there are actually some `Features Datasets`
image

and something like this if don't
image

## Actual Behavior
image

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

### PR DESCRIPTION
**Pull request by afabiani**
- Fixes #5318 : Wrong sections disposition on Welcome page

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
@afabiani this will conflict with: https://github.com/GeoNode/geonode/pull/5317 How about merging those or we merge yours and I update mine ...

**Comment by afabiani** [comment]
@t-book I'll merge your one and then fix the conflicts on mine

**Comment by t-book** [comment]
@afabiani okay thanks. If you're busy drop me a line and I can do for you ...

**Comment by t-book** [comment]
@afabiani  if you don't mind I would suggest that we add this Frontend-change to your commit as well https://github.com/GeoNode/geonode/pull/5301 the author is not responding but the change seems advisable. ...

**Pull request merged**
