### PR TITLE
[Fixes #10482] Upload ISO-19115 xml metadata via the API

### LINKED ISSUE #10482: Upload ISO-19115 xml metadata via the API
**Is your feature request related to a problem? Please describe.**
ISO-19115 XML metadata can be uploaded via the UI but the API does not support uploading the XML metadata via the API.

**Describe the solution you'd like**
An XML metadata should be allowed to be uploaded via the PUT /api/v2/dataset/metadata endpoint.

**Describe alternatives you've considered**
The alternative is to upload via the UI, but uploading via API is a welcome addition.

**Additional context**
Not applicable.

### PR DESCRIPTION
**Pull request by ahmdthr**
References: #10482

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [x] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by ahmdthr** [comment]
Related PR to the GeoNode documentation: https://github.com/GeoNode/documentation/pull/267

**Comment by afabiani** [comment]
Dear @ahmdthr thank you for your Pull Request.

In order to be able to merge this one we need few things:

1. You sign the CLA and send to OSGEO, whenever you have done this, please let us know so we can update the `clabot` and make your PR valid
2. Create an `issue` explaining what you want to achieve and reference this one into the PR title

Thank you for your support!

**Comment by ahmdthr** [comment]
> Dear @ahmdthr thank you for your Pull Request.
> 
> In order to be able to merge this one we need few things:
> 
> 1. You sign the CLA and send to OSGEO, whenever you have done this, please let us know so we can update the `clabot` and make your PR valid
> 2. Create an `issue` explaining what you want to achieve and reference this one into the PR title
> 
> Thank you for your support!

Hi,

1- I have sign the CLA and sent it to OSGEO already and I got the confirmation that my name has been added to the database.
2- The related issue is (https://github.com/GeoNode/geonode/issues/10482). I apologize, I thought I already have referenced the issue.

I hope now my PR can be merged. Thank you very much. Best regards.

**Comment by afabiani** [comment]
@ahmdthr very well, thanks so much. I'll take care of updating both the `clabot` and the PR links.

**Review by afabiani — CHANGES_REQUESTED** [review]
So far so good, but we are missing the permissions checks on the resource.

The `@action` should contain a `permission_classes` list like the following one (and the tests should prove this is actually working):

```
permission_classes=[
            IsAuthenticated, UserHasPerms(
                perms_dict={
                    "default": {
                        "PUT": ['base.change_resourcebase_metadata']
                    }
                }
            )
        ])
```

**Review by afabiani — APPROVED** [review]

**Pull request merged**
