### PR TITLE
submission of new readme for github

### PR DESCRIPTION
**Pull request by t-book**
As announced on the dev list find here my submission for a new github readme. The motivation for this PR is as the current readme / github startpage is outdated and not rendered correctly. It leaves an insufficient impression to visitors which does not comply with the great community effort of the project.

To see it in live just visit my fork: https://github.com/t-book/geonode

My approach is to keep the readme simple hence easier to manage. F.e. Instead of providing code explaining an installation the readme points to the official documentation. Besides, the new readme tries to organize the topics in a meaningful order and adds some eyes candys like new bagdes and tables.

This PR includes comments & suggestions from
- @ppasq
- @francbartoli

Further I´ve copied text from the offical documentation. So who ever is the author, credits goes to the one –  to Paolo Pasquali and Francesco Bartoli !

**Don´t forget, this is a start and meant to be improved by the community.**

### CODE REVIEW

**Comment by t-book** [comment]
@francbartoli  Hi Francesco, thanks for informing me! What do you suggest? As far as I know github expects either md or rst for a readme. Is it better to convert my markdown file to rst (without extension?!) or to change the setup. If so can you point me to the right line?

**Comment by francbartoli** [comment]
@t-book Yes I would convert the content to rst and modify the extension accordingly. Please change also [this line](https://github.com/GeoNode/geonode/blob/master/setup.py#L40)

**Comment by t-book** [comment]
@francbartoli Hi Francesco, I´ve rewritten the markdown to rst, added the extension and changed the setup.py (added .rst). Hope it´s okay like this. thank you very much!

**Comment by t-book** [comment]
@francbartoli travis fails but this does not look like connected to the readme:

`Could not open /home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/gisdata/data/good/vector/points_epsg2249_no_prj.dbf. Make sure you are using a valid file`

**Comment by francbartoli** [comment]
@t-book I have no idea why just one is failing, I have restarted the job let's see if it continues to fail

**Comment by t-book** [comment]
@francbartoli 

>  I have restarted the job let's see if it continues to fail

+1

**Comment by francbartoli** [comment]
no luck...can you verify why this file `/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/gisdata/data/good/vector/points_epsg2249_no_prj.dbf` is not found?

**Comment by t-book** [comment]
@francbartoli really strange. I´ve double checked my commit. `points_epsg2249_no_prj.dbf` has not been touched at all. let me think about for a minute.

**Comment by t-book** [comment]
@francbartoli okay Francesco the minute is over. Today when working at the readme I´ve recognized that the build badge failed for some time. Is it possible that travis failed before my PR? the message indicates it has to to with upload. Without wanting to accuse someone can you see if this could be connected to this PR 7 hours ago? https://github.com/GeoNode/geonode/pull/3862

**Comment by t-book** [comment]
@francbartoli check: I think it´s caused by this PR some hours ago.
https://travis-ci.org/GeoNode/geonode/jobs/407975438

**Comment by afabiani** [comment]
@t-book @francbartoli I'm on it. Will fix it in a few. Sorry for the noise.

**Comment by t-book** [comment]
@afabiani 
> Good cooking takes time. If you are made to wait, it is to 
serve j/ou better, and to please you. 

_MENU OF RESTAURANT ANTOINE, NEW ORLEANS_ 
:)

**Comment by francbartoli** [comment]
@t-book good catch! Thanks @afabiani

**Pull request merged**
