### PR TITLE
Updatelayer command

### PR DESCRIPTION
**Pull request by Thom03**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by t-book** [comment]
> There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)

?

**Comment by gannebamm** [comment]
@Thom03 Does this add an admin button to execute the updatelayers paver command? If yes, nice!
Nonetheless I would like echo @t-book request: Please create a short issue for it, describing the feature.

**Comment by afabiani** [comment]
The checklist should be complete for a PR to be accepted unless it is a well recognizable special case.

In this case, we need all the checks to be asserted.

**Comment by Thom03** [comment]
> geonode/templates/base.html
> 
> > <a class="navbar-brand" href="{% url "home" %}">Test
> 
> why is GeoNode renamed to test. This does not look correct to me.


I Was testing the deployment on my machine and forgot to return on 'Home'

**Comment by t-book** [comment]
@Thom03 Do you have the chance to complete the tests as @afabiani suggests?

**Comment by francbartoli** [comment]
I second @afabiani because also I cannot figure out what is the scope of this pull request and eventually the proposed solution to be implemented. From a quick look, I'm seeing a lack of logic about who has permissions to run the command and also the user passed to the command option `--user`

**Comment by afabiani** [comment]
Closing this as it seems to be stale

**Pull request closed without merging**
