### PR TITLE
[Fixes #8403]  Drop GXP* classes from Map / MapLayer models and views

### LINKED ISSUE #8403: Drop GXP* classes from Map / MapLayer models and views
## Context
After the improvements of https://github.com/GeoNode/geonode/pull/8395, it's possible now to completely remove hundreds of even thousands of lines  that are no more needed.

## To do
* [x] Simplify the big [`dataset_detail`](https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L337) view (currently with >300 lines), so it will only:
     * [x] Get the dataset.
     * [x] Get the access token.
     * [x] Populate the context only with `access_token` and `resource`.
     * [x] Handle the Event.
     * [x] Also look for whether there is more responsibilities that we should not drop.
* [x] Simplify the [`map_embed`](https://github.com/GeoNode/geonode/blob/master/geonode/maps/views.py#L341) view:
     * [x] `config`, `default_map_config` and `map_obj.viewer_json` are not needed.
* [x] Update [client_lib_tags.py](https://github.com/GeoNode/geonode/blob/master/geonode/client/templatetags/client_lib_tags.py) so that the hookset don't need to be called any more. It can directly return the template path without calling all the convoluted context processing methods.
* [x] Remove the GXP* from the [`Map`](https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L44) and [`MapLayer`](https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L384) models. Pay attention to:
    * [x] Remove the models' inheritance from the GXP classes.
    * [x] Check in the methods for methods that depends on this classes, if they are used, where they are used and if they can be deleted.
    * [x] Check the legacy fields/columns, and remove the unused.
    * [x] In that part it will be needed to pay more attention to the path of the code and its relations.
* [x] Verify the path of the code, list and drop the unused methods/functions.
* [x] To finish, runs a [vulture](https://pypi.org/project/vulture/) analysis to verify whether there is uncalled code. 

## Questions
1. @giohappy The update to `client_lib_tags.py` should be done here in geonode or in mapstore?
2. @giohappy We are not using the MapLayer's model any more, it would not be better to delete this model instead of keeping an unused table on the database?

### PR DESCRIPTION
**Pull request by italogsfernandes**
references: #8403 

### Changes summary
In each commit message, it has a topic description of what was removed/changed.
You can also read this file:
[notes_PR_8417.md](https://github.com/GeoNode/geonode/files/7603124/notes_PR_8417.md)

The following steps were done:
* First Part: Simplifying
    * [x] Remove hookset dataset_detail_template and map_embed calls  https://github.com/GeoNode/geonode/pull/8417/commits/845f747876a88f0d8c97b61abead602e05b5d239
    * [x] Simplify map_embed view https://github.com/GeoNode/geonode/pull/8417/commits/1848400cc8c9ae7a6dd782aba5ec8e62f96b93ab
    * [x] Simplify dataset_detail view https://github.com/GeoNode/geonode/pull/8417/commits/8b5840b9b2a2786a1d2483f9060ae7871d125792
    * [x] Simplify dataset_metadata view by removing viewer from view context. https://github.com/GeoNode/geonode/pull/8417/commits/7ad3a80f7bbcfdf837b4e9babb84ab875030b28e
* Second Part: Removing usages of GXPMap and GXPLayer. ⚠️ Important ⚠️: Some views were removed here.
    * Usage of default_map_config: default_map_config depends on GXPMapBase.viewer_json and vice-versa.
        * [x] Remove new_map_json view to reduce dependency on GXP* classes https://github.com/GeoNode/geonode/pull/8417/commits/f74a2ba4e77670d943f113fbc8c9efa532b94a53
        * [x] Remove Map.create_from_dataset_list to reduce dependency on GXP* classes https://github.com/GeoNode/geonode/pull/8417/commits/76301add442ec5495c6115d12c5a69f80b2496a3
    * Usage of  GXPMapBase.viewer_json: GXPMapBase.viewer_json depends on default_map_config and vice-versa. 
        * [x] Remove maps_json view and config from map_metadata view context. https://github.com/GeoNode/geonode/pull/8417/commits/cefa9d2e45ec40ab2bec8db055dada301919cf92
* Third Part: Drop GXP* classes.
     * Now we are free to delete default_map_config and GXPMapBase.viewer_json:
         *  [x] Remove GXPMap https://github.com/GeoNode/geonode/pull/8417/commits/a6d0ed5b5936f6c09e80266a465750d1d61366be
     * And them the GXPLayer:
         * [x] Remove GXPLayer https://github.com/GeoNode/geonode/pull/8417/commits/ff9d452623e695d90f7bcd0acb605f2a3bf87cdc
     * After it, some code became unused:
         * [x] Remove unused code, including maps hook and hookset https://github.com/GeoNode/geonode/pull/8417/commits/57e61d2621b1cd8c3f4af9a634c3f91475b2ecaf
*   Forth Part: Remove Legacy Fields from Models.
     * [x] Remove MapLayer legacy fields and its uses. https://github.com/GeoNode/geonode/pull/8417/commits/4127603cd4479227db1936803fae8f1c4b6097c5
     * [x] Remove Map legacy fields and its uses.  https://github.com/GeoNode/geonode/pull/8417/commits/244cd8891efa69c5ef72c3856c0113295aa4a11e ⚠️ Important ⚠️: haversting and resource app modified.

### More Notes
* GXPLayerBase and GXPMapBase weren't deleted to avoid changing the maps initial migration.
    * This would break ORM processes.
    * In this case, GXPLayerBase and GXPMapBase where declared without nothing.
* `map_ol2.html` and `map_ol3.html` were not modified but may presents unexpected behaviour:
    * They are imported inside map_metadata view.
    * Legacy fields are used in these files. (center_x, center_y, zoom)
    * Also, `config` was removed from `map_metadata` context, and it's referred inside these templates.
    * But happily, `map_metadata` view still works when manually tested, and no error messages in logs (client and server). 
* dataset_detail
    * `map.projection` is used in `dataset_detail.html:135`.
    * The field was removed, but the `dataset_embed` is still working.
    * `dataset_detail.html` was not changed, and still refers to map.projection inside it.

* Geoapps inconsistency:
   * In `geonode/geoapps/forms.py` the code refer to geoapp `zoom`, `projection`, `center_x` and `center_y`.
   * Where are they defined?
   * They seem to be removed in `geoapps/migrations/0005_auto_20210705_1121.py` but their references were forgotten.
---------------

### Questions
* Some management command may become unnecessary after this PR:
    * `migrate_baseurl` mngmt cmd needs to be changed, it uses dataset_params fiedls
     * `changemaplayertitle` mngmt cmd also needs to be changed, it uses dataset_params fields.
     * `fix_baselayers` mngmt cmd is still relevant? It was using some legacy fields, and it was changed.
     * Should they be deleted?
* Settings value `DEFAULT_MS2_BACKGROUNDS` has some legacy field in it, should it be removed?
    * It also is not used by geonode utils with the removal of GXP* classes.
* `MapLayer.get_legend` does not seems to be used besides test_get_legend
  * Can it be deleted?
* Legacy field maybe is still being in use by: `geonode/maps/templates/maps/wmc.xml` may be using `lc.visibility`
    * This is being used by map_wmc view. Is that view being called by some client?

* `Dataset.attribute_config`: May be removed in near future
    * It was used before by MapLayer.dataset_config, and MapLayer.dataset_config was removed.
* `inverse_mercator`: Used only bv mercator_to_llbbox that is not used anywhere else.
    * It was used before by default_map_config, and default_map_config was removed.
* `forward_mercator`: Used by llbbox_to_mercator that is used in `config` for dataset_metadata.
    * It was used before by default_map_config, and default_map_config was removed.
    * `config` can be removed from dataset_metadata?
* `set_bounds_from_bbox` --> Used by metadata_post_save
    * Inside it the `set_center_zoom` method, uses the legacy `self.center_x` and `self.center_y` fields that is not presented in Map object anymore.   
    * It was used by Map.update_from_viewer, and Map.update_from_viewer was removed.
* `geonode/maps/views.py:clean_config` is no more used
* `Map.get_bbox_from_datasets` is no more used
* `Map.json` seems possible to be removed (not sure).

---------------

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by italogsfernandes** [comment]
>  This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
CircleCI is still receiving two erros, they occur also in other branches.

```
* FAIL: test_add_duplicate_remote_service_url (geonode.services.tests.WmsServiceHandlerTestCase)
* FAIL: test_local_user_cant_delete_service (geonode.services.tests.WmsServiceHandlerTestCase)
FAILED (failures=2)
```
Inspecting `form.errors` we find that this is probably not related to this PR:
```
{'__all__': ['Could not connect to the service at https://demo.geo-solutions.it/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities']}
```
For a strange reason, and maybe unrelated, it appeared after https://github.com/GeoNode/geonode/commit/42300382f3a8054c7e79dced32651fc80f745cfa

**Comment by italogsfernandes** [comment]
Converted to draft while waiting for https://github.com/GeoNode/geonode/pull/8433

**Comment by giohappy** [comment]
@afabiani what's your opinion on the following?

>GXPLayerBase and GXPMapBase weren't deleted to avoid changing the maps initial migration.
>
>- This would break ORM processes.
>- In this case, GXPLayerBase and GXPMapBase where declared without nothing.

Indeed it's referenced as a bse inside [24_initial.py](https://github.com/GeoNode/geonode/blob/495aba9a5d0ec103c96945818dc071c152646f8e/geonode/maps/migrations/24_initial.py#L60). Isn't there any clean way to remove it without breaking the migration?

**Comment by afabiani** [comment]
> @afabiani what's your opinion on the following?
> 
> > GXPLayerBase and GXPMapBase weren't deleted to avoid changing the maps initial migration.
> > 
> > * This would break ORM processes.
> > * In this case, GXPLayerBase and GXPMapBase where declared without nothing.
> 
> Indeed it's referenced as a base inside [24_initial.py](https://github.com/GeoNode/geonode/blob/495aba9a5d0ec103c96945818dc071c152646f8e/geonode/maps/migrations/24_initial.py#L60). Isn't there any clean way to remove it without breaking the migration?

Unfortunately not, however the migrations are broken already with the removal of django-celery-beat and the harvester, so we can get rid of that IMHO.

**Comment by giohappy** [comment]
@afabiani @italogsfernandes after thinking more on this, I think we have to do all our best to avoid breaking the migratios, because any other solution for the upgrade fro 3.3.x would be complex and a mess.

From a discussion with @etj I think that we should change the previous migrations that reference the GXP* classes. This will not cause any issue because:

 - for existing 3.x instances, the migrations are already applied, so changes to old migrations won't affect them
 - new installs can execute the migrations without the GXP* bases

Something similar will need to be done for the break introduced by the removal of django-celey-beat @afabiani

**Pull request merged**
