### PR TITLE
Upgrade Taggit dependency

### PR DESCRIPTION
**Pull request by gbassiere**
Hi,

I suggest to upgrade django-taggit library to the latest version.

It seems possible to just upgrade to the latest django-taggit version without changing any code.

From django-taggit's changelog:
* Taggit v2.0.0 introduces backward incompatible changes on `TaggableManager.set()` method. In GeoNode, `TaggableManager` are used for `keywords` attribute of `GroupProfile`, `Profile` and `ResourceBase`. I haven't found any occurence of `keyword.set()` in GeoNode's code.
* Taggit v3.0.0 introduces backward incompatible changes regarding slugification but they say explicitly: "this should not require action on your part as a library user". I tried to upgrade to Taggit v3 on an instance having existing unicode tags and didn't noticed any problems. Old-fashioned slugs coexists with newer ones.
* Taggit v4 just removed Django 4.0 support (but retained Django 3.2 and 4.1).

I've run a GeoNode instance with taggit v4 and didn't noticed any problem. Unfortunately, I haven't been able to run the test suite (see #11588).

Context :
We developped a website based on geonode 3.2.4. In this project, we've integrated editorial contents managed by wagtail (v2.13.5). We're now willing to upgrade to the latest version of GeoNode but unfortunately GeoNode 4 requires Django 3.2.22 and django-taggit 1.5.1 (among various other dependencies). There is no version of wagtail which accepts the same combination of versions. Since django-taggit 1.5 is rather obsolete, it seemed natural to work on GeoNode in order to upgrade its dependency to taggit rather than wagtail to extend its support of older taggit version.

### CODE REVIEW

**Comment by giohappy** [comment]
Thanks @gbassiere. Let's wait for the tests to pass and then we will also make some tests with the upgraded version. It is a big jump and we want to be sure it doesn't break anything.

Nice to know that you're running GN 4 along with Wagtail successfully. It would be great if you could share something of your configuration with the community. It could be a wiki page.

**Comment by gbassiere** [comment]
> Nice to know that you're running GN 4 along with Wagtail successfully. It would be great if you could share something of your configuration with the community. It could be a wiki page.

I would be happy to contribute a wiki page on that subject, sure! Dependency conflicts let aside, it is not very complicated, just regular Django development: adding wagtail to your INSTALLED_APPS, adding a view, a route, etc.

Unfortunately, there are quite many dependency conflicts... For the current version of our website based on GN 3.2, I managed to find a wagtail version with compatible requirements. Now, we would like to upgrade to GN4 but it seems more tricky, hence this PR.

**Comment by gbassiere** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have the users @gbassiere on file. In order for us to review and merge your code, please contact the project maintainers to get yourself added.

I just sent my CLA to Osgeo, as per [CONTRIBUTING.md](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md). I'm not sure if I should notify anyone else?

**Comment by mattiagiupponi** [comment]
hi @gbassiere we will add you in the contributors list.
we will check the PR as soon as possible

**Comment by giohappy** [comment]
@gbassiere before doing this change, can you confirm this is the only upgrade needed to run GeoNode alongside Wagtail.
If more work is required I would wait to have everything in one PR

**Comment by gbassiere** [comment]
> @gbassiere before doing this change, can you confirm this is the only upgrade needed to run GeoNode alongside Wagtail. If more work is required I would wait to have everything in one PR

There was another conflict with `beautifulsoup4` (`==4.12.2` vs. `>=4.8,<4.12`) but the developers of Wagtail just bumped it to `>=4.8,<4.13` (a week ago).

So, as of today, master branch of wagtail is compatible with this branch/PR of Geonode. It is still a bit fragile, I can just hope that both project will remain compatible until each has released a new version.

**Comment by mattiagiupponi** [comment]
Hi @gbassiere 
With the last merge in master due this issue https://github.com/GeoNode/geonode/issues/11821 the dependecy has been upgraded to `version 5.0.1`

I'm going to close this issue, please feel free to open a new issue if you find some problem

Thanks

**Pull request closed without merging**
