### PR TITLE
[Fixes #9698] Allow admin access from whitelisted IPs

### LINKED ISSUE #9698: Allow admin access from whitelisted IPs
**Is your feature request related to a problem? Please describe.**
There are deployment contexts where elevated access to an application must be allowed only from a list of controlled IPs.
GeoNode and Django don't provide a built-in solution for this requirement.

**Describe the solution you'd like**
An optional mechanism will be implemented to enable admin access only from a list of whitelisted IPs.
A new `ADMIN_IP_WHITELIST` list variable will be created. If empty or if it contains a "*" the mechanism won't be enforced.
If the list is populated with one or more IPs, a dedicated middleware will be loaded.
The middleware will verify if the user issuing any request is an admin. In that case, it will verify if the user IP is inside the `ADMIN_IP_WHITELIST` list, otherwise, the request will be forbidden.

**Describe alternatives you've considered**
An alternative could be the implementation of a custom Authentication backend, but we think the task isn't worth it.

### PR DESCRIPTION
**Pull request by giohappy**
ref #9698 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — DISMISSED** [review]

**Comment by t-book** [comment]
From what I see, the definition of a IP range is not implemented but might be a nice addition. For example as postgres does it  in pg_hba

> An IP address range is specified using standard numeric notation for the range's starting address, then a slash (/) and a CIDR mask length.

f.e. `172.20.143.0/24`

**Review by mattiagiupponi — APPROVED** [review]

**Comment by afabiani** [comment]
@giohappy I agree with @t-book I guess considering a netmask would be a mandatory addition

**Comment by giohappy** [comment]
@t-book done in https://github.com/GeoNode/geonode/pull/9710/commits/a6aa790529fd5900e7d0ea7d677df2f307b8204a

**Comment by t-book** [comment]
wonderful thanks @giohappy !

**Comment by afabiani** [comment]
@giohappy can you fix the LGTM issues?

**Pull request merged**
