### PR TITLE
QGIS Server Enabler (#117)

### PR DESCRIPTION
**Pull request by ismailsunni**
This PR will make geonode able to use QGIS Server as Backend. It will need [geonode_qgis_server app](https://github.com/ismailsunni/geonode_qgis_server/) to be installed by pip.

The situation that we encounter is, the current geonode is very attached to geoserver. That's why we add some hacky part to make it work also with QGIS Server. Perhaps, in the future we can make abstraction for the backend.

The architecture : 

QGIS Server Backend Architecture

QGIS Server Backend -  Layer View

QGIS Server Backend - Map View

Contents:
- Modify some settings and code to make geonode able to use QGIS Server as backend.
- Add some views, templates and resources to make geonode able to use QGIS Server as backend.
- Add sample setting to use QGIS Server backend.

cc @jj0hns0n @ingenieroariel @timlinux @gustry @lucernae

### CODE REVIEW

**Comment by afabiani** [comment]
Very cool, the PR also looks good, it is squashed and clean, good work, but
travis checks failed.

Can I ask how the security has been integrated with the server?
How QGis Server retrieves authorities from GeoNode?

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by timlinux** [comment]
Just to clarify @ismailsunni's statement about hacky bits: he is referring specifically to logic like this:

https://github.com/GeoNode/geonode/pull/2589/files#diff-d72a1da91b74bd369f1b5f178877a80dR190

Where we have conditionals to test whether the geoserver or QGIS server backends are present.

I can see the possibility to easily add other server backends (UMN Mapserver being an obvious choice) and it would be good to move backend specific code out of the core geocode app into the backend specific app in the future. For now the hack is just to add conditionals and hand of requests to the configured backend where appropriate.

@afabiani we will update the PR so the tests pass.

@afabiani the QGIS Server backend uses a simple view to proxy tile requests. Since this is handled by a view, any permissions assigned to the map or layer object should be applied before the request will be carried out. I haven't tested this yet though so we may need to have a play with it. @ismailsunni can you make a ticket in the qgis_server_app repo so that we can verify this is the behaviour?

**Comment by jj0hns0n** [comment]
@ismailsunni  @timlinux all ok on the 'hacky' front. We need to take a good hard look at the codebase in light of PRs like this and refactor the strong dependence on GeoServer.

Insofar as security. You might take a look at work we have been doing in a repo called django-mapproxy https://github.com/terranodo/django-mapproxy which uses django guardian to enforce permissions on the services via mapproxy. Ideally we push all requests (including to geoserver) through this proxy.

@simod @ingenieroariel @sarasafavi @BerryDaniel @pjdufour can you guys take a look and lets discuss during the sprint.

See you all in a few hours ... after some coffee!

**Comment by ingenieroariel** [comment]
@ismailsunni Can you sign the contributor agreement in clahub?

**Comment by ismailsunni** [comment]
Hi @afabiani 

Sorry, I got stuck to make travis pass. I couldn't run test in my local, since I always got
```
django.db.utils.OperationalError: no such table: people_profile
```
I thought, it was the one that make my test in travis failed. I couldn't get rid off it in the end.
After some long checking around, I can make the travis pass. The real problem was the flake8. I have fixed it, and my PR is green now.

The problem that I found in local actually also occurs in travis, for example https://travis-ci.org/GeoNode/geonode/builds/154521479#L2825. But, somehow travis ignore it, and no one report the same problem when running test locally. cc @ingenieroariel 

I will check about the permission, and come back again after I have made sure that it also have been covered.

**Comment by ingenieroariel** [comment]
This is making Travis pass.

I am not a fan of the `if 'geoserver' in INSTALLED_APPS` or `if qgis in INSTALLED_APPS` approach but we don't have a better option to support custom backends. I expect this code to come into GeoNode only to let us find later a better way to let it live in a third party app or entirely within the app module and not scattered.

Thanks a lot @ismailsunni and @timlinux.

**Comment by timlinux** [comment]
@ingenieroariel 
> I am not a fan of the if 'geoserver' in INSTALLED_APPS or if qgis in INSTALLED_APPS approach but we don't have a better option to support custom backends

Totally agreed!  Thanks for sorting out the merge!

**Pull request merged**
