### PR TITLE
[Fixes #10041] Review the thumbnail scaling process

### LINKED ISSUE #10041: Review the thumbnail scaling process
## Expected Behavior

The system should downscale images once.
Increasing `THUMBNAIL_GENERATOR_DEFAULT_SIZE` to 480x400(doubling the current default). This should be enough to avoid the blurring effect when the client scales the card in the responsive layout.

## Actual Behavior

The system [is downscaling](https://github.com/GeoNode/geonode/blob/master/geonode/documents/tasks.py#L94) the image to a fixed size of (200, 100), and afterward, [rescales](https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L1745) it again to the `THUMBNAIL_GENERATOR_DEFAULT_SIZE`

## Steps to Reproduce the Problem

  1. Upload a document
  2. Notice that the thumbnail generated is blurred

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
## Additional details:
  Avoid calling [generate_thumbnail_content](https://github.com/GeoNode/geonode/blob/master/geonode/documents/renderers.py#L93) inside the [create_document_thumbnail](https://github.com/GeoNode/geonode/blob/master/geonode/documents/tasks.py#L47) task. [Here](https://github.com/GeoNode/geonode/blob/master/geonode/documents/tasks.py#L94) we are downscaling the image to a fixed size of (200, 100), and afterward we rescale it again to the THUMBNAIL_GENERATOR_DEFAULT_SIZE [here](https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L1745). It ends up doing a useless job and creating a blurred thumbnail.

### PR DESCRIPTION
**Pull request by marthamareal**
ref #10041

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by giohappy — COMMENTED** [review]
@marthamareal is this code already covered with tests?

**Comment by marthamareal** [comment]
> @marthamareal is this code already covered with tests?

The `create_document_thumbnail` is patched in some tests, however am going to add some tests for the size configured in settings and also thumbnail for non-image docs

**Review by mattiagiupponi — CHANGES_REQUESTED** [review]
Hi @marthamareal, follows questions:
- In the issue, only the downscale from the document parts is mentioned, but I guess that changing the settings will have an impact also on the other resources. Can you confirm this?
- I guess that re-specify the default value in the models is redundant. The setting is static (which means that is always coded in the file) and already has defaulted, so in the future, if we need to change the default size, we can rely only on the settings without changing in other parts of the code
- The LGTM bot is raising a couple of issues with the variable names
- Can you please add a couple of tests to verify that is working as expected and that there aren't regressions for the other resources?

**Comment by marthamareal** [comment]
> Hi @marthamareal, follows questions:
> 
> * In the issue, only the downscale from the document parts is mentioned, but I guess that changing the settings will have an impact also on the other resources. Can you confirm this?
> * I guess that re-specify the default value in the models is redundant. The setting is static (which means that is always coded in the file) and already has defaulted, so in the future, if we need to change the default size, we can rely only on the settings without changing in other parts of the code
> * The LGTM bot is raising a couple of issues with the variable names
> * Can you please add a couple of tests to verify that is working as expected and that there aren't regressions for the other resources?

@mattiagiupponi I have updated the PR with tests and suggested changes. Changing the settings has no effect because the setting which was being used `THUMBNAIL_GENERATOR_DEFAULT_SIZE` does not exist so the code was always using the default given. The LGTM shows fixed issues no new issues. Other resources are not affected because they have tests regarding thumbs and are passing. (also tested manually).

**Comment by giohappy** [comment]
As a note for future, we're dropping [unoconv renderer](https://github.com/GeoNode/geonode/blob/master/geonode/documents/renderers.py#L51) since [it's not maintained anymore](https://github.com/unoconv/unoconv#unoconv-is-deprecated), so it's unlikely that it will ever be installed.

**Review by mattiagiupponi — APPROVED** [review]

**Comment by mattiagiupponi** [comment]
note: LGTM raise an issue, but actually is fixed:
image

**Pull request merged**
