### PR TITLE
New rebuilt Leaflet hookset/template

### PR DESCRIPTION
**Pull request by dejansamardzic**
Dear comunity,

We have rebuilt Leaflet hookset/template, so now Leaflet client is fully functional and prepared for adding new plugins. We have inclueded plugins for: Full screen, measurement tool, printing tools, layer contoler with multiple base layers, transparency slider, scale bar, drawing tools - useful for pointing some objects or areas before printing, locate me option, leaflet hash...

Known limitations:

- Bounding box for map thumbnail creation doesn't focus as it should be

- Problem with GeoWeb Cache: Uploading new layers results with wrong bounding boxes in Geoserver. In order to make GeoWeb Cache to work, layer needs to be removed from Cache and added again. This clears problem with wrong bounding box defined during upload and turn it into "dynamic".

- Embeded maps are focused on Montenegro.

- To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container

- Plugin "Locate me" works only through https.

Best regards,
Dejan Samardzic

### CODE REVIEW

**Comment by t-book** [comment]
Hi Dejan,

thanks a lot for this. One question would it work for you to change the inital map extent that it´s not centered to Montenegro but to the specific resource bounds?  If I remember correctly you should get it from resource.bbox_string or have a look at the previous implementation: https://github.com/GeoNode/geonode/blob/5a7e86f73af13ec927e4b1ac0ea893cf5ad1a68a/geonode/client/templates/leaflet/maps/map_view.html#L196

**Comment by t-book** [comment]
I´ve just tested Dejans PR. Leaflet is back again. Thanks @dejansamardzic 
As already commented I would welcome a change that maps initially zoom on it´s resource. Further I´ve got following error when saving a layer Thumbnail:

```
geonode:tiger_roads_1:353 Uncaught TypeError: map.getBounds is not a function
    at createMapThumbnail (geonode:tiger_roads_1:353)
    at HTMLAnchorElement.<anonymous> (geonode:tiger_roads_1:2014)
    at HTMLAnchorElement.dispatch (assets.min.js?v=2.10rc4:4)
    at HTMLAnchorElement.q.handle (assets.min.js?v=2.10rc4:4)

```
I´m unsure regarding changes to files which are not specific to leaflet like
* geonode/geoserver/signals.py
* geonode/layers/utils.py
* geonode/maps/views.py
* geonode/templates/base.html (why is the licence removed?)
* ...
where I would wait for travis to finish and ask @afabiani or @francbartoli for their review.

**Comment by dejansamardzic** [comment]
Dear comunity,

We have made final modifications on Leaflet hookset/template, so now Leaflet client is fully functional and prepared for adding new plugins. We have inclueded plugins for: Full screen, measurement tool, printing tools, layer contoler with multiple base layers, transparency slider, scale bar, drawing tools - useful for pointing some objects or areas before printing, locate me option, leaflet hash, geocoding...

Known limitations:

Bounding box for map thumbnail creation doesn't focus as it should be

Problem with GeoWeb Cache: Uploading new layers results with wrong bounding boxes in Geoserver. In order to make GeoWeb Cache to work, layer needs to be removed from Cache and added again. This clears problem with wrong bounding box defined during upload and turn it into "dynamic".

Embeded maps are focused on Montenegro - we have corrected this to use bounding box from map.

To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container

Plugin "Locate me" works only through https. We have corrected embeded maps to be completely functional through https. Guide for importing Let's Encrypt SSL certificate you can find in attachment
[SSL guide for geonode 2.10 docker.txt](https://github.com/GeoNode/geonode/files/2949556/SSL.guide.for.geonode.2.10.docker.txt)


Best regards,
Dejan Samardzic

**Comment by dejansamardzic** [comment]
Dear comunity,

We have made final modifications on Leaflet hookset/template, so now Leaflet client is fully functional and prepared for adding new plugins. We have included plugins for: Full screen, measurement tool, printing tools, layer contoler with multiple base layers, transparency slider, scale bar, drawing tools - useful for pointing some objects or areas before printing, locate me option, leaflet hash, geocoding...

Known limitations:

Bounding box for map thumbnail creation doesn't focus as it should be. Thumbnail generation on layer/map doesn't work from Editting tools > Set Thumbnail, but work on layer/map creation.

Problem with GeoWeb Cache: Uploading new layers results with wrong bounding boxes in Geoserver. In order to make GeoWeb Cache to work, layer needs to be removed from Cache and added again. This clears problem with wrong bounding box defined during upload and turn it into "dynamic".

Embeded maps are focused on Montenegro - we have corrected this to use bounding box from map.

To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container

Plugin "Locate me" works only through https. We have corrected embeded maps to be completely functional through https. Guide for importing Let's Encrypt SSL certificate you can find in attachment
SSL guide for geonode 2.10 docker.txt

We have modified py filed by your request.

Best regards,
Dejan Samardzic

**Comment by t-book** [comment]
@dejansamardzic you have conflicts in two files. 

- geonode/geoserver/signals.py
- geonode/layers/utils.py

please pull those files from master and resolve conflicts.

**Comment by dejansamardzic** [comment]
We have resolved conflicts....
regards,
Dejan

**Comment by afabiani** [comment]
Uhm, overall the idea is good, but there is still something that does not convince me at all:

1. Changes to base and core templates; why we need those ones? This PR should affect only Leaflet stuff
2. We need to clean up assets and move the static stuff related to leaflet inside the leaflet client hook
3. Would be desirable (I know it is not easy to achieve) to put at least few bdd or selenium tests using the leaflet hookset

**Comment by francbartoli** [comment]
Totally agree with @afabiani. If there is the need to change some files from the core then that should happen separately in a new pull request. I second also the request for e2e tests with this web mapping client

**Comment by dejansamardzic** [comment]
Dear Mr. Alessio,

It would be really important for us if our PR become part of future official Geonode release.
Our recources are pretty exhausted (we had spent 63 man/days rebuilding Leaflet client). We do understand your concerns (to change only Leaflet client not entire platfom). We suggest the following: 
- we will resolve this limitiation: "To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container"
- in order to determine that changes made outside of the Leaflet client doesn't affect other clients, we are prepared to make detailed analysis about it. 
- we hope that the Geonode Development Team will take over all future activities related to the merging of our PR into the official Geonode release.

Please, Mr. Alessio we are waiting for your comment.

Regards,
Dejan Samardžić

**Comment by afabiani** [comment]
@dejansamardzic sure, this is a very good contribution, even though we are moving towards react bases clients, which may support both OpenLayers and Leaflet without having specific hooksets.

However, I will dedicate some time on my side to refine this PR.

**Comment by francbartoli** [comment]
> Dear Mr. Alessio,
> 
> It would be really important for us if our PR become part of future official Geonode release.
> Our recources are pretty exhausted (we had spent 63 man/days rebuilding Leaflet client). We do understand your concerns (to change only Leaflet client not entire platfom). We suggest the following:
> 
> * we will resolve this limitiation: "To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container"
> * in order to determine that changes made outside of the Leaflet client doesn't affect other clients, we are prepared to make detailed analysis about it.
> * we hope that the Geonode Development Team will take over all future activities related to the merging of our PR into the official Geonode release.

This might happen from the version 2.10 onwards as long as that piece of code would have a maintainer which means somebody can provide time to support it in the community (GitHub issues, gitter channel, users and devel list)

> 
> Please, Mr. Alessio we are waiting for your comment.
> 
> Regards,
> Dejan Samardžić

**Comment by dejansamardzic** [comment]
@afabiani perfect. We will try to resolve limitation and make detailed description till the end of March.

**Comment by dejansamardzic** [comment]
Dear @afabiani,
we have managed to resolve limitiation: "To switch between GeoExplorer and Leaflet client you have to modify (in addition to settings.py) file /usr/src/app/geonode/maps/templates/maps/map_new.html within Django container". 
Now, switching between Leaflet and other clients requires to change only settings.py file.

Following is a list of Geonode core files (outside of Leaflet template folder) we have changed, previously, and explainations of those changes, as a proof that they are influencing only Leaflet functionalities:

- **geonode/client/hookset.py** changes are done to Leaflet part only, to correctly link html pages with urls.

- **geonode/geoserver/signals.py** - On several places we have called "create_gs_thumbnail" because it couldn't create thumbnails without it. Changes regarding ows to wms service you may discard, and it is not critical for system functioning.

- **geonode/layers/utils.py** - we made only one change, that refreshed instance values, becouse values were not synchronised with database values. This is probably needed for other clients also.

- **geonode/maps/templates/maps/map_detail.html** we deleted only one empty row, so you can discard this change as well

- **geonode/maps/templates/maps/map_edit.html** - you can discard this changes.  Known limitation: editing map without this changes work, but navigation manu does not.

- **geonode/maps/views.py** - Main changes are regardind adding rest service call for list of Geoserver group layers (url = "%srest/layergroups" % (settings.GEOSERVER_PUBLIC_LOCATION)) and sending informations about map and layers object back to templates.

- **geonode/templates/base.htm**l - file reverted to original. All changes can be discarded.

It would be really important for us if our PR become part of future official Geonode release.

Regards,
Dejan

**Comment by t-book** [comment]
@dejansamardzic 

> Conflicting files
> geonode/geoserver/signals.py
> geonode/maps/views.py

Can you resolve?

**Comment by dejansamardzic** [comment]
Dear @afabiani ,

We have modified conflict files and resolved limitation on geonode/maps/templates/maps/map_edit.html. Now Leaflet with default file map_edit.html works without limitations,

Best regards,
Dejan

**Comment by t-book** [comment]
Let´s try again to solve this PR. @dejansamardzic I had a look at the travis logs. They f.e. fail  when testing new map creation. 

```
ERROR: test_new_map_page (geonode.tests.smoke.GeoNodeSmokeTests)
Test New Map page renders.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GeoNode/geonode/geonode/tests/smoke.py", line 114, in ...
----------------------------------------------------------------------
Ran 115 tests in 1452.244s

```

This might be caused as you haven´t reverted the changed files ouside of 'leaflet hookset' as mentioned here https://github.com/GeoNode/geonode/pull/4261#issuecomment-478259596 ?

In other words your PR would still change all of these files (views.py, signals etc...):

Bildschirmfoto 2019-04-14 um 13 38 13

- To make a long story short. Make sure your PR only contains what is really needed. ( If it’s easier for you reset and commit only needed files again)
- Try to run the tests locally by use of paver or create a travis account which runs test from your fork.
- Further, take note of the requested test in https://github.com/GeoNode/geonode/pull/4261#issuecomment-474280083 which is missing in your PR

**Comment by afabiani** [comment]
@dejansamardzic I'm closing this PR in favor of this one https://github.com/GeoNode/geonode/pull/4390
which correctly:

a) Refers to issues on GeoNode
b) Is made against a specific branch on main repo which can be updated by developers also

**Pull request closed without merging**
