### PR TITLE
Fix for ISSUE #3130: Batch edit

### LINKED ISSUE #3130: Batch edit of resources

### PR DESCRIPTION
**Pull request by mekanix**
close #3130

### CODE REVIEW

**Comment by simod** [comment]
Could you describe what this does?

**Comment by capooti** [comment]
It would be also helpful if the PR would contain documentation.

**Comment by mekanix** [comment]
I wanted to do the docs and forgot. Sorry! I'll add it in the morning.

**Comment by capooti** [comment]
Great! Thanks

**Comment by mekanix** [comment]
I amended the commit with documentation

**Comment by capooti** [comment]
great, thanks!

**Pull request merged**
