### PR TITLE
[3.3.x][Fixes #8667] Implement the upload of files from remote locations

### LINKED ISSUE #8667: Implement the upload of files from remote locations
The current implementation of the `upload` view, and in particular the [save_step_view](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/views.py#L133), only supports files uploaded as multipart data through `LayerUploadForm`.

We want to extend it to accept paths to a remote location, from which the file can be read and uploaded to Geoserver.

The high level requirements are:

 - for the moment we only implement support to filesystem paths (that of course are visible to GeoNode), but we want to make it generic to support additional implementations for other types of remote storages (S3, etc.). [smart_open](https://github.com/RaRe-Technologies/smart_open) could be a nice solution to be considered.
 - we don't want to make local copies of the remote file, including temporary copies.
 - files will be [uploaded directly through the gs_uploader instance](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/upload.py#L358) . I guess that the file interface should make it mostly transparent, without any modification.

GeoNode doesn't rely much on local copies of uploaded files. In 3.3.x, if available, a direct link for their download is provided, but it's not a prerequisite for the functionality of GeoNode. However we have to check all the steps in the upload procedure, in case in some place they expect to have the files copied to local locations. 

Notice that in this moment the support for mosaic granules is not well maintained (a new issue will be created for this), so this must be taken into account in implementing and testing this requirements.

This task targets both master and 3.3.x. The upload that is affected should still be the same (or very similar) on both branches. The big differences happen at the end of the import, where the GeoNode resource is finalized and created (master uses the Resource Manager, which doesn't exist in 3.3.x).

### PR DESCRIPTION
**Pull request by italogsfernandes**
references: #8667

Backport of  #8731

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [x] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by italogsfernandes** [comment]
Converted to draft, it need to pass the tests...

**Comment by italogsfernandes** [comment]
Ready for review

**Review by afabiani — CHANGES_REQUESTED** [review]
There something odd in this PR, `DataItemRetriever` should be part of the `geonode.upload` package.

Please, make sure the code is aligned with the one pushed on `master`

**Comment by italogsfernandes** [comment]
@afabiani It's updated.
Changes to the following files are different in the backport. This happens due to the different implementation in the 3.3.x code, how should I proceed with that part? It's working but I'm not sure about the process related to the `store_spatial_files` option and cleaning in the 3.3.x.
* geonode/resource/manager.py: https://github.com/GeoNode/geonode/pull/8731/files#diff-64a2aaa5de6e1fea66f83b8a29d7148d0fd47814c00dea7b5460de75b427baa6R286-R287
* geonode/upload/models.py:  https://github.com/GeoNode/geonode/pull/8731/files#diff-a2bccf9e0cea1b8db1dcc77dd0e0c6c5a19b8f94f23678c00104043365bb598eR166-R171

**Pull request merged**
