### PR TITLE
Add new env variable GEOIP_DATABASE_URL

### PR DESCRIPTION
**Pull request by NyakudyaA**
Fixes https://github.com/GeoNode/geonode/issues/11263

Even though you can a database and use the env variable `GEOIP_PATH=/mnt/volumes/statics/geoip.db` when deploying using CDI i.e Argo CD you have no option to mount volumes with a local DB

### CODE REVIEW

**Comment by giohappy** [comment]
@NyakudyaA the `updategeoip` functionality was just dropped since it was a very old method that is not allowed anymore by MaxMind EULA.
I think the `GEOIP_PATH` should be enough to reference the DB location, isn't it?

**Comment by giohappy** [comment]
>Not in all cases, in our case we are deploying through ArgoCD and we cannot mount the DB so we would prefer to have a working link to download the DB and if the link is not available/working we can still provide our own custom link to download the DB

Out of curiosity:

 - are you using the monitoring module?
 - do you need to execute regular updates of the GeoIP DB?

**Comment by NyakudyaA** [comment]
> > Not in all cases, in our case we are deploying through ArgoCD and we cannot mount the DB so we would prefer to have a working link to download the DB and if the link is not available/working we can still provide our own custom link to download the DB
> 
> Out of curiosity:
> 
>     * are you using the monitoring module?
> 
>     * do you need to execute regular updates of the GeoIP DB?

We do use monitoring module. We rarely execute updates on the GeoIP DB. If the `updategeoip` method has been dropped maybe I can take a look and see if we still need this. Maybe if you can fix the URL to be correct then we can close this PR

**Comment by giohappy** [comment]
>Maybe if you can fix the URL to be correct then we can close this PR

@NyakudyaA the GeoIP 2 DB can not be shared, it violates MaxMind EULA. You need your own copy of the DB and set the GEOIP_PATH to your convenience.
If you don't need to do frequent updates you could ship it inside your Docker image.

**Comment by NyakudyaA** [comment]
No longer useful since monitoring has been dropped

**Pull request closed without merging**
