### PR TITLE
Full docker support (docker toolbox limited) for devs who are using the old authentication system

### PR DESCRIPTION
**Pull request by francbartoli**
I've tried to move the 2.5.x branch up to a commit before the merge of the AA security GNIP and then added the docker stuff. At the moment this is limited just for developers still using docker toolbox.
Next step will be the support for all versions of docker (Docker for Mac, Docker for Windows, etc) by introducing [docker-py](https://github.com/docker/docker-py) to programmatically fetch the docker host ip address and remove bash variables for that.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
Im a little confused about the scope of this PR now. Can we squash it and send it against master?

**Comment by francbartoli** [comment]
@jj0hns0n actually not, this would be scoped just for 2.5.x before the merge of advance authentication security system. Squash could be possible even if I don't know keeping the history of all commits also for this branch would make sense

**Comment by jj0hns0n** [comment]
Its just a huge number of unrelated commits. Im not sure what has actually
changed now.

On Thu, Dec 29, 2016 at 3:05 PM, Francesco Bartoli <notifications@github.com

**Comment by francbartoli** [comment]
I understand the problem but let's consider this branch was at an older commit than master and it could be definitively useful for developers who need to stay with the old authentication system. Now I'm considering master diverging from 2.5.x after the end of summit when [#2755](https://github.com/GeoNode/geonode/pull/2755) was merged. Then I added the docker stuff with a couple of its commits still coming from master.
I know the new security AA system is gone to 2.5.6 but I'd rather considering that as a beta 2.6.0 imho.

**Comment by francbartoli** [comment]
@jj0hns0n can we freeze somehow a branch that still maintains the old authentication system? Then I would be able to provide a new PR with sole commits about docker stuff

**Comment by jj0hns0n** [comment]
@afabiani can you help with this? It looks to me like its about here 49be1ba3aef568b19ecf863d470c98d410d0ecb1

**Comment by afabiani** [comment]
GeoNode-GeoServer TAG using old auth system is already available here

https://github.com/GeoNode/geoserver-geonode-ext/tree/2.9.1

tags/2.9.1

Should I take care of creating a GeoNode tag too? Is there someone already in charge of creating GeoNode tags following specific policies?

**Comment by francbartoli** [comment]
@afabiani There is already a [2.5.5](https://github.com/GeoNode/geonode/releases/tag/2.5.5) tag with the associated commit [04d2a06](https://github.com/GeoNode/geonode/commit/04d2a063ecb6ed071ca51e352ab352c4224a9f85) but the GeoNode-GeoServer tag comes much later.
I don't know if it would be useful to have a new branch 2.5.5 or to just align the branch 2.5.x more or less [here](https://github.com/GeoNode/geonode/commit/f7d41c6e2f92cb00729bcadc9c79350db8efe1f4).

The first would break the policy of branches while the latter would not allow the propagation through the 2.5.6.

@jj0hns0n thoughts?

**Comment by jj0hns0n** [comment]
I dont have a strong opinion on this. Whatever works for you guys. Perhaps
@simod or @ingenieroariel have an opinion.

**Pull request closed without merging**
