### PR TITLE
[Fixes #5089] Update index.html

### LINKED ISSUE #5089: Geoscience category button does search for farming category, too
## Expected Behavior
If you click the geoscience category button you should see only geoscience items

## Actual Behavior
You will see items which belong to geoscience **or** farming category

## Steps to Reproduce the Problem

  1. open http://master.demo.geonode.org/ and click the geoscience category
  2. check href URL (http://master.demo.geonode.org/search/?limit=100&offset=0&category__identifier__in=farming&category__identifier__in=geoscientificInformation)
  3. see https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html#L128

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode with double check on master.demo.geonode.org

### PR DESCRIPTION
**Pull request by gannebamm**
fixes #5089

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Comment by gannebamm** [comment]
regarding the CLA - did I sign it allready? The Bot says yes

**Comment by afabiani** [comment]
@gannebamm probably you followed the old automatic procedure. If not, please send the signed CLA to OSGeo as specified in the contribution file. Thanks.

Just check the checkbox when you have done.

**Comment by gannebamm** [comment]
@afabiani I sure will! 
I used this to get it signed by the head of administration of the institute - which takes some time but is one more step closer to me becoming an official psc member in the near future 😉

**Comment by gannebamm** [comment]
> 
> @gannebamm let us know when we can merge this, thanks.

@afabiani 
The CLA is signed and sent. 
You could merge this now. Codecov is a false error I guess for this simple fix in the template.

**Pull request merged**
