### PR TITLE
Enable Http API Key Auth on API

### PR DESCRIPTION
**Pull request by Vampouille**
This PR allow use of geonode API by other websites. For protected resources, you can use an API key to access API and avoid login form and cookie management. This way other websites or apps does not have to simulate connection with login form.

It use tastypie authentication with API key :
http://django-tastypie.readthedocs.io/en/latest/authentication.html#apikeyauthentication

First step is to generate keys with following command : 
```bash
$ python manage.py backfill_api_keys
```
Then you can add `api_key` and `username` as get parameter on any API url. For example: 
`/api/layers/?username=joe&api_key=xxxxxxxxxxxxxxxxxxxxx`

### CODE REVIEW

**Comment by Vampouille** [comment]
@afabiani About unit tests, I'm working on it. I need to find a way to populate api keys before running test.

**Comment by afabiani** [comment]
@Vampouille interesting feature, thanks. So the API KEYS are generated Server Side and are different for any user, am I correct?

Can you update your PR to master branch so that the failing test passes on Travis?

Do you think it would be too hard to add a test case somehow?

**Comment by Vampouille** [comment]
> So the API KEYS are generated Server Side and are different for any user, am I correct?

yes

> Can you update your PR to master branch so that the failing test passes on Travis?

I think travis error is not linked with my modification : 
```
ConnectTimeout: HTTPConnectionPool(host='metaspatial.net', port=80): Max retries exceeded with url: /cgi-bin/ogc-wms.xml?service=WMS&request=GetCapabilities&version=1.1.1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb4c2c7f8d0>, 'Connection to metaspatial.net timed out. (connect timeout=30)'))
```
Is there a way to restart travis  ?

> Do you think it would be too hard to add a test case somehow?

I don't known, I take a look at : https://github.com/GeoNode/geonode/blob/master/geonode/api/tests.py
There is already some piece of code to add one test user. I need to programmatically trigger `python manage.py backfill_api_keys`. And finally build url with `username` and `api_key` parameters.

**Comment by afabiani** [comment]
@Vampouille to fix the travis test you should do a merge of your branch GFDRR:api_key_master with GeoNode:master and push the changes again. Travis will restart automatically.

**Comment by afabiani** [comment]
@Vampouille I merged with master branch and tests are now passing.

There still a formatting issue on one file to fix:

geonode/api/authorization.py:115:1: W391 blank line at end of file

**Comment by Vampouille** [comment]
> There still a formatting issue on one file to fix:

Done with 116b479

**Comment by ismailsunni** [comment]
Hi @Vampouille, thanks so much for this feature.

I am wondering, is it possible to get/generate the key from a url / a view? *sorry, if it's a newbie question, I am not familiar with tastypie :)

**Comment by Vampouille** [comment]
> I am wondering, is it possible to get/generate the key from a url / a view? *sorry, if it's a newbie question, I am not familiar with tastypie :)

There is a dedicated signal functions in Tastypie that can be used to automatically generate key for new users:
```python
from django.contrib.auth.models import User
from django.db.models import signals
from tastypie.models import create_api_key

signals.post_save.connect(create_api_key, sender=User)
```

See : http://django-tastypie.readthedocs.io/en/latest/authentication.html#apikeyauthentication

**Pull request merged**
