### PR TITLE
Layout Changes / Group Members, Avatar Change

### PR DESCRIPTION
**Pull request by state-hiu**
Layout Changes for groups members and avatar change pages.  Added tabs to filter by role and some styling to members list (see image below).  Minor style fixes to avatar change.

image

### CODE REVIEW

**Comment by garnertb** [comment]
@state-hiu, any chance you can also fix the messed up "User identifier" select2 box in this PR?  Also, "User identifier" should be renamed to something more human friendly.  If not, go ahead and merge this, its still a big improvement.

794a1ebe-a34e-11e4-8971-3e8d25933dac

**Comment by state-hiu** [comment]
Not really sure how to fix that.  The `form-control` class at the select2-container is adding a `padding: 6px 12px;`.  When padding is 0 the input looks good.  The form is generate with: `{{ member_form|as_bootstrap }}`, so I don't have easy control over the styling.  Unless you know of an easy solution, I'd merge for now.

**Comment by teamgeode** [comment]
I think the best way to resolve this layout issue is to place https://github.com/GeoNode/geonode/blob/master/geonode/groups/templates/groups/group_members.html#L31 into a div with an id.

      <div id="add_id_user_indentifiers">
         {{ invite_form|as_bootstrap }}
      </div>

And you modify the CSS by heritage like:

      #add_id_user_indentifiers div{
         padding: 0px;
      }

**Comment by state-hiu** [comment]
The newest commit fixes the dropdown.  Can someone run the static build.  I'm not sure how to do it for release (I just use `make css`).  I've also fixed some logic (`get_or_create`) and added a check so you can't add existing members to the group.  You need to remove a member and add back if you want to elevate his/her from member to manager.

**Pull request merged**
