### PR TITLE
Exif Support

### PR DESCRIPTION
**Pull request by pjdufour**
This PR adds an Exif contrib app.  This app is disabled by default.  If enabled by the `EXIF_ENABLED` settings flag, this app parses Exif tags from JPEGs uploaded as documents and automatically generates metadata, including date, keywords, and a brief abstract.  It uses `from PIL import Image, ExifTags`, so doesn't require any changes to dependencies.

### CODE REVIEW

**Comment by simod** [comment]
@pjdufour there may be a conflict with the previous PRs here, could you fix it?

**Comment by pjdufour** [comment]
Sure thing.

**Comment by pjdufour** [comment]
Hold please.

**Comment by pjdufour** [comment]
Also, I just added in tab for document detail pages that shows a few Exif tag values.

**Comment by pjdufour** [comment]
Let me squash.

**Pull request closed without merging**
