### PR TITLE
Copied style from a similar page

### PR DESCRIPTION
**Pull request by madi**
proceeding for trial and error until rendering is optimal. Thank you

### CODE REVIEW

**Comment by simod** [comment]
@madi thanks, do you plan to do more commits on this? If yes I'll just let the Pr pending until you give us the ok.

**Comment by simod** [comment]
btw you can build the docs locally with:

  $ cd docs
  $ make html

**Comment by madi** [comment]
cool, thank you for the tip.
I'm not planning further commits on this, because i have no idea why the result is still sub optimal.
I used the same template used in http://docs.geonode.org/en/master/tutorials/devel/install_devmode/index.html#install-devmode
Thanks

**Comment by jj0hns0n** [comment]
Im going to go ahead and merge this and it can be cleaned up later during the next big docs push.

**Comment by jj0hns0n** [comment]
@madi can you fix the merge conflicts?

**Pull request closed without merging**
