### PR TITLE
[Fixes #8622] Drop CuratedThumbnail and fix the metadata wizard thumbnail widget

### LINKED ISSUE #8622: Drop CuratedThumbnail and fix the metadata wizard thumbnail widget
## Expected Behavior
Upload thumbnails using the new V2 set_thumbnail API.

## Actual Behavior

CuratedThumbnail is a concept that we're not using anymore. The new API (https://github.com/GeoNode/geonode/issues/8561) for setting thumbnails, and the resource manager, directly set the thumbnail (and the corresponding link) directly, without creating a curated thumbnail object. 

We want to 

 - remove CuratedThumbnail model (and its admin classes)
 - make the metadata wizard page widget use the new /resources/{pk}/set_thumbnail API (with form-data file upload)
 - drop [thumbnail_upload](https://github.com/GeoNode/geonode/blob/eafaf522af073bf183d45880c59a9e0907710416/geonode/base/views.py#L222) view
 - drop CuratedThumbnailForm

**NOTICE**: the migration must take care of the existing curated thumbnails. When needed the resource thumbnail_url and link must be updated, and the image files must be moved out of the "curated" folder

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

### PR DESCRIPTION
**Pull request by marthamareal**
<Include a few sentences describing the overall goals for this Pull Request>
References #8622

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [x] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

### CODE REVIEW

**Review by afabiani — CHANGES_REQUESTED** [review]
A couple of  comments:

1. When creating a `RunPython` migration, please make sure there's also the `reverse` one; if it does not applies, use the `noop` reverse method
2. When modifying `static` JS files, you need to regenerate the `assets` too by using `grunt`

**Comment by afabiani** [comment]
@marthamareal please check my comments

**Comment by marthamareal** [comment]
> 2\. When modifying `static` JS files, you need to regenerate the `assets` too by using `grunt`

@afabiani is there an example grant file to generate the assets?

**Comment by marthamareal** [comment]
@afabiani I have included the files changed using `grunt development` with grant file in `/geonode/static` folder

**Review by afabiani — APPROVED** [review]

**Pull request merged**
